import type { LessonStageDefinition, Monster } from "../../../../domain/shared/types";
import {
  biomeMonster,
  type BiomeEncounterDefinition,
} from "../shared/biome";

/** 第二层生态遭遇池：怪物数据负责候选与课程，坐标由运行时地图生成器决定。 */
export const FLOOR_TWO_BIOME_MONSTERS: readonly Monster[] = [
  biomeMonster({
    floor: 2,
    id: 15,
    lessonId: "order-by",
    roomId: 31,
    name: "水怪",
    species: "lake_beast",
    kind: "sort-drake",
    hp: 12,
    maxHp: 12,
    armor: 0,
    damage: 2,
    attackName: "浪花扑击",
    status: "surfacing",
    weakness: "descending",
    masterId: 21,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 2,
    id: 16,
    lessonId: "distinct",
    roomId: 32,
    name: "镜蛇",
    species: "water_snake",
    kind: "distinct-mimic",
    hp: 13,
    maxHp: 13,
    armor: 0,
    damage: 2,
    attackName: "水纹缠绕",
    status: "coiled",
    weakness: "unique",
    masterId: 21,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 2,
    id: 17,
    lessonId: "inner-join",
    roomId: 33,
    name: "青蛙",
    species: "swamp_frog",
    kind: "join-spider",
    hp: 13,
    maxHp: 13,
    armor: 0,
    damage: 2,
    attackName: "泥水跳击",
    status: "croaking",
    weakness: "relation",
    masterId: 22,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 2,
    id: 18,
    lessonId: "left-join",
    roomId: 34,
    name: "沼蛙",
    species: "poison_frog",
    kind: "left-join-wraith",
    hp: 16,
    maxHp: 16,
    armor: 0,
    damage: 2,
    attackName: "毒沼反击",
    status: "toxic",
    weakness: "left",
    masterId: 22,
    isBoss: false,
    rank: "elite",
  }),
  biomeMonster({
    floor: 2,
    id: 19,
    lessonId: "order-by",
    roomId: 35,
    name: "林犬",
    species: "forest_hound",
    kind: "filter-hound",
    hp: 13,
    maxHp: 13,
    armor: 0,
    damage: 2,
    attackName: "林间扑咬",
    status: "tracking",
    weakness: "descending",
    masterId: 14,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 2,
    id: 20,
    lessonId: "inner-join",
    roomId: 36,
    name: "古树精",
    species: "forest_treant",
    kind: "join-spider",
    hp: 18,
    maxHp: 18,
    armor: 1,
    damage: 2,
    attackName: "根须缠绕",
    status: "rooted",
    weakness: "relation",
    masterId: 14,
    isBoss: false,
    rank: "elite",
  }),
  biomeMonster({
    floor: 2,
    id: 21,
    lessonId: "distinct",
    roomId: 37,
    name: "湖兽",
    species: "lake_boss",
    kind: "sort-drake",
    hp: 22,
    maxHp: 22,
    armor: 1,
    damage: 3,
    attackName: "深水冲击",
    status: "submerged",
    weakness: "unique",
    masterId: null,
    isBoss: true,
    rank: "elite",
  }),
  biomeMonster({
    floor: 2,
    id: 22,
    lessonId: "left-join",
    roomId: 38,
    name: "蛙王",
    species: "frog_boss",
    kind: "left-join-wraith",
    hp: 24,
    maxHp: 24,
    armor: 1,
    damage: 3,
    attackName: "沼王重压",
    status: "ruling",
    weakness: "left",
    masterId: null,
    isBoss: true,
    rank: "elite",
  }),
] as const;

const PRACTICE_ORDER: LessonStageDefinition = {
  id: "practice-order",
  objective: "从 monster_signals 按 charge 从高到低，取出 monster_id = 15 的最强 channel。",
  queryTemplate: "",
  answerSql: "SELECT channel FROM monster_signals WHERE monster_id = 15 ORDER BY charge DESC LIMIT 1;",
  hints: [
    "从 monster_signals 读取 channel。",
    "按 charge 降序排列。",
    "只保留第一行。",
    "完整写法：SELECT channel FROM monster_signals WHERE monster_id = 15 ORDER BY charge DESC LIMIT 1;",
  ],
  locks: ["ORDER BY", "LIMIT"],
  requiredFeatures: ["order-by", "limit"],
  attackTargetIds: [15],
};

const PRACTICE_DISTINCT: LessonStageDefinition = {
  id: "practice-distinct",
  objective: "镜潮湾把同一方向复制成多条水纹。只返回 ID #016 在 monster_signals 中真正不同的 channel。",
  queryTemplate: "",
  answerSql: "SELECT DISTINCT channel FROM monster_signals WHERE monster_id = 16;",
  hints: [
    "数据表是 monster_signals。",
    "SELECT 后加入 DISTINCT。",
    "读取 channel。",
    "WHERE monster_id = 16 锁定这组水纹。",
    "完整写法：SELECT DISTINCT channel FROM monster_signals WHERE monster_id = 16;",
  ],
  locks: ["DISTINCT"],
  requiredFeatures: ["distinct"],
  attackTargetIds: [16],
};

const PRACTICE_INNER_JOIN: LessonStageDefinition = {
  id: "practice-inner-join",
  objective: "泥沼石径缺少 ID #017 的房间记录。令 monsters 为 m、rooms 为 r；用 m.room_id = r.id 连接，返回怪物主键 m.id 与房间名 r.name AS room_name，再用 m.id = 17 锁定目标。",
  queryTemplate: "",
  answerSql: "SELECT m.id, r.name AS room_name FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 17;",
  hints: [
    "monsters.room_id 对应 rooms.id。",
    "给两张表使用短别名。",
    "把 rooms.name 命名为 room_name。",
    "完整写法：SELECT m.id, r.name AS room_name FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 17;",
  ],
  locks: ["INNER JOIN", "ON"],
  requiredFeatures: ["join", "on"],
  attackTargetIds: [17],
};

const PRACTICE_LEFT_JOIN: LessonStageDefinition = {
  id: "practice-left-join",
  objective: "毒雾洼地要保留所有怪物，再找出没有装备记录的一只。返回 m.id；房间条件是 m.room_id = 34，空匹配条件是 g.monster_id IS NULL。",
  queryTemplate: "",
  answerSql: "SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id = 34 AND g.monster_id IS NULL;",
  hints: [
    "从 monsters m LEFT JOIN monster_gear g。",
    "连接条件是 m.id = g.monster_id。",
    "同时过滤 room_id 与空装备记录。",
    "完整写法：SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id = 34 AND g.monster_id IS NULL;",
  ],
  locks: ["LEFT JOIN", "IS NULL"],
  requiredFeatures: ["left-join", "is-null"],
  attackTargetIds: [18],
};

const PRACTICE_LEFT_CORE: LessonStageDefinition = {
  id: "practice-left-core",
  objective: "第二击继续使用 LEFT JOIN，并加入已学过的状态过滤。返回 ID #018 中 status = 'toxic' 且没有装备记录的 m.id。",
  queryTemplate: "",
  answerSql: "SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 18 AND m.status = 'toxic' AND g.monster_id IS NULL;",
  hints: [
    "仍从 monsters m LEFT JOIN monster_gear g。",
    "连接条件是 m.id = g.monster_id。",
    "同时检查 m.status 与 g.monster_id IS NULL。",
    "完整写法：SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 18 AND m.status = 'toxic' AND g.monster_id IS NULL;",
  ],
  locks: ["LEFT JOIN", "ON", "IS NULL", "AND"],
  requiredFeatures: ["left-join", "on", "is-null", "and"],
  attackTargetIds: [18],
};

const FOREST_ORDER: LessonStageDefinition = {
  id: "practice-forest-order",
  objective: "从 monsters 返回 id = 19 的 id 与 hp，按 hp 降序并只取一行。",
  queryTemplate: "",
  answerSql: "SELECT id, hp FROM monsters WHERE id = 19 ORDER BY hp DESC LIMIT 1;",
  hints: [
    "读取 id 与 hp。",
    "先用 WHERE 锁定 ID #019。",
    "按 hp DESC 排序并 LIMIT 1。",
    "完整写法：SELECT id, hp FROM monsters WHERE id = 19 ORDER BY hp DESC LIMIT 1;",
  ],
  locks: ["ORDER BY", "LIMIT"],
  requiredFeatures: ["order-by", "limit"],
  attackTargetIds: [19],
};

const FOREST_JOIN: LessonStageDefinition = {
  id: "practice-forest-join",
  objective: "第一击：给 monsters 使用别名 m、rooms 使用别名 r，查询 m.id = 20 的 m.id 与 room_name。",
  queryTemplate: "",
  answerSql: "SELECT m.id, r.name AS room_name FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE m.id = 20;",
  hints: [
    "连接 monsters AS m 与 rooms AS r。",
    "ON m.room_id = r.id。",
    "读取 m.id，并把 r.name 命名为 room_name。",
    "完整写法：SELECT m.id, r.name AS room_name FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE m.id = 20;",
  ],
  locks: ["INNER JOIN", "ON"],
  requiredFeatures: ["join", "on"],
  attackTargetIds: [20],
};

const FOREST_JOIN_CORE: LessonStageDefinition = {
  id: "practice-forest-join-core",
  objective: "第二击：连接 monsters AS m 与 rooms AS r，返回 m.id = 20 的 m.id，并把 r.sector 命名为 room_sector；按 r.sector 排序且只取一行。",
  queryTemplate: "",
  answerSql: "SELECT m.id, r.sector AS room_sector FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE m.id = 20 ORDER BY r.sector LIMIT 1;",
  hints: [
    "保持 monsters 与 rooms 的连接。",
    "读取 m.id，并把 r.sector 命名为 room_sector。",
    "按 r.sector 排序并 LIMIT 1。",
    "完整写法：SELECT m.id, r.sector AS room_sector FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE m.id = 20 ORDER BY r.sector LIMIT 1;",
  ],
  locks: ["INNER JOIN", "ON", "ORDER BY", "LIMIT"],
  requiredFeatures: ["join", "on", "order-by", "limit"],
  attackTargetIds: [20],
};

const LAKE_BOSS_SCAN: LessonStageDefinition = {
  id: "lake-boss-scan",
  objective: "第一击：按 charge 从高到低查询 monster_id = 21 的前两条 channel 与 charge。",
  queryTemplate: "",
  answerSql: "SELECT channel, charge FROM monster_signals WHERE monster_id = 21 ORDER BY charge DESC LIMIT 2;",
  hints: [
    "从 monster_signals 读取 channel 与 charge。",
    "用 WHERE monster_id = 21 锁定信号。",
    "按 charge DESC 排序并 LIMIT 2。",
    "完整写法：SELECT channel, charge FROM monster_signals WHERE monster_id = 21 ORDER BY charge DESC LIMIT 2;",
  ],
  locks: ["SELECT", "FROM", "WHERE"],
  requiredFeatures: ["select", "from", "where"],
  attackTargetIds: [21],
};

const LAKE_BOSS_SORT: LessonStageDefinition = {
  id: "lake-boss-sort",
  objective: "第二击：去重查询 monster_id = 21 的 channel，并按 channel 排序。",
  queryTemplate: "",
  answerSql: "SELECT DISTINCT channel FROM monster_signals WHERE monster_id = 21 ORDER BY channel;",
  hints: [
    "读取不同的 channel。",
    "使用 DISTINCT 去重。",
    "按 channel 排序。",
    "完整写法：SELECT DISTINCT channel FROM monster_signals WHERE monster_id = 21 ORDER BY channel;",
  ],
  locks: ["DISTINCT", "ORDER BY"],
  requiredFeatures: ["distinct", "order-by"],
  attackTargetIds: [21],
};

const FROG_BOSS_LEFT: LessonStageDefinition = {
  id: "frog-boss-left",
  objective: "第一击：给 monsters 使用别名 m、monster_gear 使用别名 g；LEFT JOIN 后返回 m.id = 22 且 g.monster_id 为空的 m.id。",
  queryTemplate: "",
  answerSql: "SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 22 AND g.monster_id IS NULL;",
  hints: [
    "从 monsters m LEFT JOIN monster_gear g。",
    "连接 id 与 monster_id。",
    "同时检查 m.id 与空装备记录。",
    "完整写法：SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 22 AND g.monster_id IS NULL;",
  ],
  locks: ["LEFT JOIN", "ON", "IS NULL"],
  requiredFeatures: ["left-join", "on", "is-null"],
  attackTargetIds: [22],
};

const FROG_BOSS_DISTINCT: LessonStageDefinition = {
  id: "frog-boss-distinct",
  objective: "第二击：连接 monsters AS m 与 rooms AS r，去重返回二层 m.id = 22 的 m.id，并把 r.name 命名为 room_name；按 m.id 排序。",
  queryTemplate: "",
  answerSql: "SELECT DISTINCT m.id, r.name AS room_name FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE r.floor = 2 AND m.id = 22 ORDER BY m.id;",
  hints: [
    "连接 monsters 与 rooms。",
    "用 DISTINCT 读取 m.id，并把 r.name 命名为 room_name。",
    "WHERE 限定二层和 ID #022，最后排序。",
    "完整写法：SELECT DISTINCT m.id, r.name AS room_name FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE r.floor = 2 AND m.id = 22 ORDER BY m.id;",
  ],
  locks: ["DISTINCT", "INNER JOIN", "ON", "ORDER BY"],
  requiredFeatures: ["distinct", "join", "on", "order-by"],
  attackTargetIds: [22],
};

export const FLOOR_BIOME_ENCOUNTERS = [
  { monsterId: 15, floor: 2, biome: "lake", role: "normal", randomEncounter: true, stages: [PRACTICE_ORDER] },
  { monsterId: 16, floor: 2, biome: "lake", role: "normal", randomEncounter: true, stages: [PRACTICE_DISTINCT] },
  { monsterId: 17, floor: 2, biome: "swamp", role: "normal", randomEncounter: true, stages: [PRACTICE_INNER_JOIN] },
  { monsterId: 18, floor: 2, biome: "swamp", role: "mini-elite", randomEncounter: true, stages: [PRACTICE_LEFT_JOIN, PRACTICE_LEFT_CORE] },
  { monsterId: 19, floor: 2, biome: "forest", role: "normal", randomEncounter: true, stages: [FOREST_ORDER] },
  { monsterId: 20, floor: 2, biome: "forest", role: "mini-elite", randomEncounter: true, stages: [FOREST_JOIN, FOREST_JOIN_CORE] },
  { monsterId: 21, floor: 2, biome: "lake", role: "area-boss", randomEncounter: false, stages: [LAKE_BOSS_SCAN, LAKE_BOSS_SORT] },
  { monsterId: 22, floor: 2, biome: "swamp", role: "area-boss", randomEncounter: false, stages: [FROG_BOSS_LEFT, FROG_BOSS_DISTINCT] },
] as const satisfies readonly BiomeEncounterDefinition[];
