import type { LessonStageDefinition, Monster } from "../../../../domain/shared/types";
import {
  biomeMonster,
  type BiomeEncounterDefinition,
} from "../shared/biome";

export const FLOOR_SIX_BIOME_MONSTERS: readonly Monster[] = [
  biomeMonster({
    floor: 6,
    id: 62,
    lessonId: "f6-insert",
    roomId: 77,
    name: "小龙",
    species: "nest_hatchling",
    kind: "hatchling",
    hp: 20,
    maxHp: 20,
    armor: 0,
    damage: 4,
    attackName: "幼焰喷吐",
    status: "restless",
    weakness: "insert",
    masterId: 66,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 6,
    id: 63,
    lessonId: "f6-update",
    roomId: 79,
    name: "翼龙",
    species: "magma_wyvern",
    kind: "wyvern",
    hp: 22,
    maxHp: 22,
    armor: 0,
    damage: 4,
    attackName: "翼爪扫击",
    status: "circling",
    weakness: "update",
    masterId: 66,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 6,
    id: 64,
    lessonId: "f6-transaction",
    roomId: 79,
    name: "电龙",
    species: "cavern_thunder_drake",
    kind: "dragon",
    hp: 29,
    maxHp: 29,
    armor: 1,
    damage: 4,
    attackName: "雷息",
    status: "charged",
    weakness: "rollback",
    masterId: 66,
    isBoss: false,
    rank: "elite",
  }),
  biomeMonster({
    floor: 6,
    id: 65,
    lessonId: "f6-constraint",
    roomId: 78,
    name: "矿龙",
    species: "cavern_crystal_drake",
    kind: "dragon",
    hp: 23,
    maxHp: 23,
    armor: 0,
    damage: 4,
    attackName: "晶片飞射",
    status: "crystallized",
    weakness: "constraint",
    masterId: 66,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 6,
    id: 66,
    lessonId: "f6-savepoint",
    roomId: 80,
    name: "古龙",
    species: "ancient_cave_dragon",
    kind: "dragon-king",
    hp: 40,
    maxHp: 40,
    armor: 2,
    damage: 5,
    attackName: "古焰轰击",
    status: "ancient",
    weakness: "savepoint",
    masterId: 61,
    isBoss: true,
    rank: "elite",
  }),
] as const;

const PRACTICE_HATCHLING: LessonStageDefinition = {
  id: "practice-hatchling",
  objective: "向 repair_queue 写入 id = 7、item = 'ember'、quantity = 1、status = 'ready'。",
  queryTemplate: "",
  answerSql: "INSERT INTO repair_queue(id, item, quantity, status) VALUES (7, 'ember', 1, 'ready');",
  hints: [
    "使用 INSERT INTO repair_queue。",
    "明确写出四个字段。",
    "值是 7、'ember'、1、'ready'。",
    "完整写法：INSERT INTO repair_queue(id, item, quantity, status) VALUES (7, 'ember', 1, 'ready');",
  ],
  locks: ["INSERT"],
  requiredFeatures: ["insert"],
  attackTargetIds: [62],
};

const PRACTICE_WYVERN: LessonStageDefinition = {
  id: "practice-wyvern",
  objective: "把 repair_queue 中 id = 1 的 quantity 更新为 3。",
  queryTemplate: "",
  answerSql: "UPDATE repair_queue SET quantity = 3 WHERE id = 1;",
  hints: [
    "使用 UPDATE repair_queue。",
    "SET quantity = 3。",
    "WHERE id = 1。",
    "完整写法：UPDATE repair_queue SET quantity = 3 WHERE id = 1;",
  ],
  locks: ["UPDATE", "WHERE"],
  requiredFeatures: ["update", "where"],
  attackTargetIds: [63],
};

const PRACTICE_THUNDER_DRAKE: LessonStageDefinition = {
  id: "practice-thunder-drake",
  objective: "BEGIN 后把 id = 1 的 quantity 改成 8，再 ROLLBACK。",
  queryTemplate: "",
  answerSql: "BEGIN; UPDATE repair_queue SET quantity = 8 WHERE id = 1; ROLLBACK;",
  hints: [
    "第一条是 BEGIN。",
    "中间 UPDATE id = 1。",
    "最后 ROLLBACK。",
    "完整写法：BEGIN; UPDATE repair_queue SET quantity = 8 WHERE id = 1; ROLLBACK;",
  ],
  locks: ["BEGIN", "UPDATE", "ROLLBACK"],
  requiredFeatures: ["transaction", "update", "rollback"],
  attackTargetIds: [64],
};

const PRACTICE_CRYSTAL_DRAKE: LessonStageDefinition = {
  id: "practice-crystal-drake",
  objective: "用 INSERT OR IGNORE 尝试写入 quantity = -2 的无效 id = 7，保持沙箱不变。",
  queryTemplate: "",
  answerSql: "INSERT OR IGNORE INTO repair_queue(id, item, quantity, status) VALUES (7, 'bad', -2, 'ready');",
  hints: [
    "使用 INSERT OR IGNORE。",
    "目标表是 repair_queue。",
    "无效 quantity 是 -2。",
    "完整写法：INSERT OR IGNORE INTO repair_queue(id, item, quantity, status) VALUES (7, 'bad', -2, 'ready');",
  ],
  locks: ["INSERT", "OR IGNORE"],
  requiredFeatures: ["insert", "constraint"],
  attackTargetIds: [65],
};

const DRAGON_BOSS_SCAN: LessonStageDefinition = {
  id: "dragon-boss-scan",
  objective: "区域首领第一击：在隔离沙箱中只删除 repair_queue 的 id = 4。",
  queryTemplate: "",
  answerSql: "DELETE FROM repair_queue WHERE id = 4;",
  hints: [
    "使用 DELETE FROM repair_queue。",
    "必须带 WHERE。",
    "只锁定 id = 4。",
    "完整写法：DELETE FROM repair_queue WHERE id = 4;",
  ],
  locks: ["DELETE", "WHERE"],
  requiredFeatures: ["delete", "where"],
  attackTargetIds: [66],
};

const DRAGON_BOSS_CORE: LessonStageDefinition = {
  id: "dragon-boss-core",
  objective: "区域首领第二击：用 INSERT OR IGNORE 尝试写入 quantity = -2 的 id = 9，证明 CHECK 约束会拒绝无效记录。",
  queryTemplate: "",
  answerSql: "INSERT OR IGNORE INTO repair_queue(id, item, quantity, status) VALUES(9, 'broken-scale', -2, 'ready');",
  hints: [
    "使用 INSERT OR IGNORE。",
    "明确写出 id、item、quantity、status。",
    "quantity = -2 会违反 CHECK，沙箱应保持不变。",
    "完整写法：INSERT OR IGNORE INTO repair_queue(id, item, quantity, status) VALUES(9, 'broken-scale', -2, 'ready');",
  ],
  locks: ["INSERT", "CONSTRAINT"],
  requiredFeatures: ["insert", "constraint"],
  attackTargetIds: [66],
};

export const FLOOR_BIOME_ENCOUNTERS = [
  { monsterId: 62, floor: 6, biome: "magma-nest", role: "normal", randomEncounter: true, stages: [PRACTICE_HATCHLING] },
  { monsterId: 63, floor: 6, biome: "dragon-throne", role: "normal", randomEncounter: true, stages: [PRACTICE_WYVERN] },
  { monsterId: 64, floor: 6, biome: "dragon-throne", role: "mini-elite", randomEncounter: true, stages: [PRACTICE_THUNDER_DRAKE] },
  { monsterId: 65, floor: 6, biome: "crystal-cavern", role: "normal", randomEncounter: true, stages: [PRACTICE_CRYSTAL_DRAKE] },
  { monsterId: 66, floor: 6, biome: "crystal-cavern", role: "area-boss", randomEncounter: false, stages: [DRAGON_BOSS_SCAN, DRAGON_BOSS_CORE] },
] as const satisfies readonly BiomeEncounterDefinition[];
