import type {
  FloorAnchorDefinition,
  FloorExperienceDefinition,
  FloorLandmarkDefinition,
} from "./types";

function anchor(
  roomNodeId: string,
  x: number,
  y: number,
  facing: FloorAnchorDefinition["facing"] = "south",
  width = 3,
  height = 3,
): FloorAnchorDefinition {
  return { roomNodeId, position: { x, y }, facing, clearance: { width, height } };
}

function landmark(
  input: Omit<FloorLandmarkDefinition, "minimapIcon"> & { minimapIcon?: string },
): FloorLandmarkDefinition {
  return { ...input, minimapIcon: input.minimapIcon ?? "landmark" };
}

export const FLOOR_TWO_EXPERIENCE: FloorExperienceDefinition = {
  id: "floor-02-tidal-archipelago",
  floor: 2,
  title: "月潮群岛",
  subtitle: "同一段恢复轨迹，从七片水域归来",
  version: 1,
  signature: "可见海面、短船程、沉水村落、中央船闸与覆盖少数记录的孤塔",
  assetPack: {
    id: "floor-02-tidal-archipelago-assets",
    version: 1,
    manifestPath: "/assets/floors/02-tidal-archipelago/manifest.json",
    assets: [
      {
        key: "f02-cc0-puny-overworld",
        kind: "tileset",
        path: "/assets/floors/02-tidal-archipelago/sources/shade-puny-world/overworld-16x16.png",
        fallback: "coast-geometric",
      },
      {
        key: "f02-cc0-scallywag-water",
        kind: "tileset",
        path: "/assets/floors/02-tidal-archipelago/sources/foozle-scallywag-water-islands/water-and-islands-16x16.png",
        fallback: "animated-water",
      },
    ],
  },
  regions: [
    {
      id: "f2-coast",
      navigationRegion: "front",
      name: "潮汐码头与白沙浅滩",
      purpose: "用排序点亮航线，并提供可反复返回的中央枢纽",
      lessonIds: ["order-by"],
      material: "浅色木栈桥、湿沙、蓝绿近岸水",
      ambience: "轻快弦乐、柔和海浪与船绳",
      landmarkIds: ["f2-spawn-light", "f2-scribe-station", "f2-ranked-beacons", "f2-middle-fire"],
    },
    {
      id: "f2-lake",
      navigationRegion: "front",
      name: "月影湖与沉水村落",
      purpose: "以 DISTINCT 识别七处水纹；湖兽是前区可选挑战，退潮只开放额外探索",
      lessonIds: ["distinct"],
      material: "深蓝湖水、屋顶、旧钟架和芦苇",
      ambience: "低频水流、远钟与缓慢木管",
      landmarkIds: ["f2-drowned-village", "f2-wreck-ledger", "f2-lake-beast", "f2-ship-lock"],
    },
    {
      id: "f2-forest-swamp",
      navigationRegion: "middle",
      name: "古树桥与芦苇沼泽",
      purpose: "通过根系连接和缺失装备记录教授 INNER / LEFT JOIN；蛙王是通往后区灯塔的主线硬门",
      lessonIds: ["inner-join", "left-join"],
      material: "粗大树根、青苔石、浅泥与芦苇",
      ambience: "温暖中提琴、湿地昆虫与不尖锐的鼓点",
      landmarkIds: ["f2-root-bridge", "f2-rear-fire", "f2-frog-court"],
    },
    {
      id: "f2-lighthouse",
      navigationRegion: "rear",
      name: "灯塔岛",
      purpose: "用综合 JOIN 推翻只保留多数记录的规则",
      lessonIds: ["join-boss"],
      material: "风化白石、铜质灯室、黑蓝深海",
      ambience: "圆号、低弦与缓慢扩张的庄严和声",
      landmarkIds: ["f2-sql-seal", "f2-lighthouse-arena", "f2-north-ferry"],
    },
  ],
  landmarks: [
    landmark({
      id: "f2-spawn-light",
      name: "码头导航灯",
      kind: "spawn-anchor",
      regionId: "f2-coast",
      anchor: anchor("floor-2-entry", 0.18, 0.6, "east"),
      assetKey: "f02-cc0-scallywag-water",
      fallback: "small-beacon",
      interaction: null,
      stateKeys: ["always"],
    }),
    landmark({
      id: "f2-scribe-station",
      name: "抄写员码头记录台",
      kind: "story",
      regionId: "f2-coast",
      anchor: anchor("floor-2-entry", 0.56, 0.36, "south", 4, 3),
      assetKey: "f02-cc0-puny-overworld",
      fallback: "wet-pages-desk",
      interaction: "查看七份湿记录",
      stateKeys: ["unranked", "ranked", "seven-pages"],
      minimapIcon: "npc",
    }),
    landmark({
      id: "f2-ranked-beacons",
      name: "七盏月潮浮标",
      kind: "world-machine",
      regionId: "f2-coast",
      anchor: anchor("floor-2-order", 0.72, 0.28, "north", 7, 4),
      assetKey: "f02-cc0-scallywag-water",
      fallback: "seven-beacons",
      interaction: "读取信号强度",
      stateKeys: ["dark", "ranked", "seven-reflections"],
      minimapIcon: "beacon",
    }),
    landmark({
      id: "f2-middle-fire",
      name: "浅滩篝火",
      kind: "campfire",
      regionId: "f2-coast",
      anchor: anchor("floor-2-rest", 0.54, 0.62),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f2-drowned-village",
      name: "沉水村落",
      kind: "vista",
      regionId: "f2-lake",
      anchor: anchor("floor-2-distinct", 0.56, 0.72, "south", 9, 6),
      assetKey: "f02-cc0-puny-overworld",
      fallback: "submerged-roofs",
      interaction: "调查水下门牌",
      stateKeys: ["submerged", "revealed"],
      minimapIcon: "village",
    }),
    landmark({
      id: "f2-wreck-ledger",
      name: "沉船记录舱",
      kind: "story",
      regionId: "f2-lake",
      anchor: anchor("floor-2-treasure", 0.5, 0.4, "south", 6, 5),
      assetKey: "f02-cc0-scallywag-water",
      fallback: "moonlit-wreck-ledger",
      interaction: "读取七只防水匣",
      stateKeys: ["sealed", "discovered"],
      minimapIcon: "secret",
    }),
    landmark({
      id: "f2-lake-beast",
      name: "深水影潭",
      kind: "boss-arena",
      regionId: "f2-lake",
      anchor: anchor("floor-2-treasure", 0.5, 0.5, "north", 7, 7),
      assetKey: "f02-cc0-scallywag-water",
      fallback: "deep-water-ring",
      interaction: "前区可选挑战 ID #021",
      stateKeys: ["high-tide", "defeated"],
      minimapIcon: "area-boss",
    }),
    landmark({
      id: "f2-ship-lock",
      name: "中央月潮船闸",
      kind: "shortcut",
      regionId: "f2-lake",
      anchor: anchor("floor-2-event", 0.5, 0.5, "west", 5, 5),
      assetKey: "f02-cc0-scallywag-water",
      fallback: "timber-lock",
      interaction: "退潮后开启额外探索捷径",
      stateKeys: ["closed", "open"],
      minimapIcon: "shortcut",
    }),
    landmark({
      id: "f2-root-bridge",
      name: "双端古树根桥",
      kind: "world-machine",
      regionId: "f2-forest-swamp",
      anchor: anchor("floor-2-inner-join", 0.54, 0.42, "east", 8, 4),
      assetKey: "f02-cc0-scallywag-water",
      fallback: "root-bridge",
      interaction: "连接怪物与房间记录",
      stateKeys: ["severed", "linked"],
      minimapIcon: "bridge",
    }),
    landmark({
      id: "f2-rear-fire",
      name: "古树篝火",
      kind: "campfire",
      regionId: "f2-forest-swamp",
      anchor: anchor("floor-2-event", 0.77, 0.72),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或本层答案复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f2-frog-court",
      name: "泥冠宫",
      kind: "boss-arena",
      regionId: "f2-forest-swamp",
      anchor: anchor("floor-2-join-elite", 0.34, 0.62, "north", 6, 6),
      assetKey: "f02-cc0-puny-overworld",
      fallback: "reed-throne",
      interaction: "主线硬门 ID #022 · 击败后开放灯塔道路",
      stateKeys: ["hidden", "available", "defeated"],
      minimapIcon: "area-boss",
    }),
    landmark({
      id: "f2-sql-seal",
      name: "七源密文门",
      kind: "sql-seal",
      regionId: "f2-lighthouse",
      anchor: anchor("floor-2-boss", 0.18, 0.56, "east", 3, 4),
      assetKey: "f02-cc0-puny-overworld",
      fallback: "query-seal",
      interaction: "用关系查询提前校准灯塔侧门",
      stateKeys: ["sealed", "decoded"],
      minimapIcon: "query",
    }),
    landmark({
      id: "f2-lighthouse-arena",
      name: "月潮灯塔",
      kind: "boss-arena",
      regionId: "f2-lighthouse",
      anchor: anchor("floor-2-boss", 0.5, 0.42, "north", 9, 8),
      assetKey: "f02-cc0-puny-overworld",
      fallback: "lighthouse-silhouette",
      interaction: "挑战 ID #014",
      stateKeys: ["overwriting", "preserving"],
      minimapIcon: "boss",
    }),
    landmark({
      id: "f2-north-ferry",
      name: "北岸渡船",
      kind: "transit",
      regionId: "f2-lighthouse",
      anchor: anchor("floor-2-boss", 0.82, 0.72, "east", 5, 3),
      assetKey: "f02-cc0-scallywag-water",
      fallback: "small-skiff",
      interaction: "前往结霜北岸",
      stateKeys: ["away", "docked"],
      minimapIcon: "ascent",
    }),
  ],
  npcPlacements: [
    {
      id: "npc-scribe-f2",
      name: "抄写员",
      role: "把七份相似记录分别保存的连续引导者",
      regionId: "f2-coast",
      anchor: anchor("floor-2-entry", 0.48, 0.38, "south", 2, 2),
      assetKey: "shared.actor.scribe",
      alwaysShowName: true,
    },
  ],
  hiddenAreas: [
    {
      id: "f2-hidden-wreck-ledger",
      title: "沉船记录舱",
      roomNodeId: "floor-2-treasure",
      gateId: "gate:floor-2-treasure",
      landmarkId: "f2-wreck-ledger",
      requiredLessonIds: ["order-by", "distinct"],
      sealedPrompt: "E  调查退潮后露出的船腹裂口",
      sealedMessage: "裂口后传来纸匣碰撞声。先用 ORDER BY 排清航线，再用 DISTINCT 分清重复水纹与不同来源。",
      openPrompt: "E  钻入沉船记录舱",
      openedMessage: "船腹裂口已经能通过。舷窗下排着七只防水匣，每一只都标着不同港口。",
      discoveryEventId: "f2-story-wreck-ledger",
    },
  ],
  storyEvents: [
    {
      id: "f2-story-seven-wet-pages",
      title: "潮声有顺序",
      trigger: "floor-entered",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "music-state", state: "f2-open-coast" },
        { type: "camera-focus", landmarkId: "f2-ranked-beacons" },
        { type: "dialogue", speaker: "抄写员", lines: ["同一段恢复轨迹回来了七次。", "先别把它们叫作重复。"] },
      ],
      completionFact: "story:f2:entry-seen",
    },
    {
      id: "f2-story-wreck-ledger",
      title: "七只防水匣",
      trigger: "gate:floor-2-treasure:opened",
      repeat: "once",
      priority: 85,
      actions: [
        { type: "camera-focus", landmarkId: "f2-wreck-ledger" },
        { type: "world-effect", effect: "f2-wreck-ledger-open" },
        { type: "dialogue", speaker: "抄写员", lines: ["七只匣子共享恢复印，却分别来自七个港口。", "把相似的记录放在一起，不等于可以扔掉其中六份。"] },
      ],
      completionFact: "story:f2:wreck-ledger",
    },
    {
      id: "f2-story-first-route",
      title: "第一条航线",
      trigger: "lesson:order-by:completed",
      repeat: "once",
      priority: 80,
      actions: [
        { type: "camera-focus", landmarkId: "f2-ranked-beacons" },
        { type: "world-effect", effect: "f2-route-ranked" },
        { type: "banner", text: "最强信号已排序 · 短船靠岸" },
      ],
      completionFact: "story:f2:first-route",
    },
    {
      id: "f2-story-low-tide",
      title: "湖兽与退潮",
      trigger: "monster:21:defeated",
      repeat: "once",
      priority: 90,
      actions: [
        { type: "camera-focus", landmarkId: "f2-drowned-village" },
        { type: "world-effect", effect: "f2-tide-low" },
        { type: "banner", text: "潮位下降 · 村落与船闸露出" },
      ],
      completionFact: "story:f2:low-tide",
    },
    {
      id: "f2-story-frog-court",
      title: "泥冠硬门解除",
      trigger: "monster:22:defeated",
      repeat: "once",
      priority: 95,
      actions: [
        { type: "camera-focus", landmarkId: "f2-frog-court" },
        { type: "world-effect", effect: "f2-frog-court-open" },
        { type: "banner", text: "泥冠硬门解除 · 灯塔后区开放" },
        { type: "dialogue", speaker: "抄写员", lines: ["未匹配，不等于不存在。", "这一次，沼泽不能再替王城把他们留下。"] },
      ],
      completionFact: "story:f2:frog-court",
    },
    {
      id: "f2-story-seven-reflections",
      title: "七个倒影",
      trigger: "gate:shortcut:2:return:opened",
      repeat: "once",
      priority: 90,
      actions: [
        { type: "camera-focus", landmarkId: "f2-ranked-beacons" },
        { type: "world-effect", effect: "f2-seven-reflections" },
        { type: "dialogue", speaker: "抄写员", lines: ["它们站在不同的水里。", "如果只是重复，为什么每一个都看向不同方向？"] },
      ],
      completionFact: "story:f2:seven-reflections",
    },
    {
      id: "f2-story-cipher",
      title: "七源密文被关系证据解开",
      trigger: "gate:floor-2-boss:opened",
      repeat: "once",
      priority: 88,
      actions: [
        { type: "camera-focus", landmarkId: "f2-sql-seal" },
        { type: "world-effect", effect: "f2-cipher-decoded" },
        { type: "banner", text: "跨岛关系校验通过；灯塔侧门永久开启" },
      ],
      completionFact: "story:f2:cipher",
    },
    {
      id: "f2-story-seven-pages",
      title: "七页，不是一个答案",
      trigger: "monster:14:defeated",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "world-effect", effect: "f2-lighthouse-preserving" },
        { type: "evidence", evidenceId: "lost-name:f2:shared-trace" },
        { type: "dialogue", speaker: "抄写员", lines: ["我给它们编了七个页码。", "没有一个被写成你的真名。"] },
      ],
      completionFact: "story:f2:completed",
    },
  ],
  environmentRules: [
    { id: "f2-beacons-dark", when: "order-by:not-completed", state: "beacons=dark", visibleResult: "远处航线熄灭，只保留码头安全水域" },
    { id: "f2-beacons-ranked", when: "order-by:completed", state: "beacons=ranked", visibleResult: "浮标按强度点亮，短船靠岸" },
    { id: "f2-channels-distinct", when: "distinct:completed", state: "channels=distinct", visibleResult: "重复水纹合并，不同岛屿方向保留" },
    { id: "f2-root-linked", when: "inner-join:completed", state: "root_bridge=linked", visibleResult: "树根正确连接两端并形成桥" },
    { id: "f2-missing-gear", when: "left-join:completed", state: "missing_gear=found", visibleResult: "沉水村落无装备记录的门显形" },
    { id: "f2-tide-low", when: "monster:21:defeated", state: "tide=low", visibleResult: "浅滩扩大、村落露出、船闸可用" },
    { id: "f2-lock-open", when: "gate:shortcut:2:return:opened", state: "shortcut=open", visibleResult: "码头与灯塔之间的短航线永久开放" },
    { id: "f2-lighthouse-preserving", when: "monster:14:defeated", state: "lighthouse=preserving", visibleResult: "灯塔同时照亮七个方向，北岸渡船靠岸" },
  ],
  adminPresets: [
    { id: "f2-admin-entry", label: "F2 入层", completedLessonIds: [], defeatedMonsterIds: [], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f2-ranked-beacons" },
    { id: "f2-admin-village", label: "F2 沉水村落", completedLessonIds: ["order-by", "distinct"], defeatedMonsterIds: [10, 11], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f2-drowned-village" },
    { id: "f2-admin-hidden", label: "F2 沉船记录舱", completedLessonIds: ["order-by", "distinct"], defeatedMonsterIds: [10, 11], openedGateIds: ["gate:floor-2-treasure"], collectedKeyItems: [], focusLandmarkId: "f2-wreck-ledger" },
    { id: "f2-admin-low-tide", label: "F2 退潮与船闸", completedLessonIds: ["order-by", "distinct", "inner-join"], defeatedMonsterIds: [10, 11, 12, 21], openedGateIds: ["shortcut:2:return"], collectedKeyItems: ["shortcut-key:2"], focusLandmarkId: "f2-ship-lock" },
    { id: "f2-admin-frog-court", label: "F2 泥冠硬门", completedLessonIds: ["order-by", "distinct", "inner-join", "left-join"], defeatedMonsterIds: [10, 11, 12, 13, 22], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f2-frog-court" },
    { id: "f2-admin-complete", label: "F2 通关", completedLessonIds: ["order-by", "distinct", "inner-join", "left-join", "join-boss"], defeatedMonsterIds: [10, 11, 12, 13, 14, 21, 22], openedGateIds: ["shortcut:2:return"], collectedKeyItems: ["floor-key:2"], focusLandmarkId: "f2-north-ferry" },
  ],
};
