/**
 * 第七层世界体验、地标和作者化楼层布局真源。
 *
 * 本模块只描述楼层作者内容，不执行游戏动作、不保存进度，并保持对 presentation/infrastructure 的隔离。
 */
import type {
  FloorAnchorDefinition,
  FloorExperienceDefinition,
  FloorLandmarkDefinition,
} from "../../types";

function anchor(
  roomNodeId: string,
  x: number,
  y: number,
  facing: FloorAnchorDefinition["facing"] = "south",
  width = 3,
  height = 3,
): FloorAnchorDefinition {
  return { roomNodeId, position: { x, y }, facing, clearance: { width, height } };
}

function landmark(
  input: Omit<FloorLandmarkDefinition, "minimapIcon"> & { minimapIcon?: string },
): FloorLandmarkDefinition {
  return { ...input, minimapIcon: input.minimapIcon ?? "landmark" };
}

export const FLOOR_SEVEN_EXPERIENCE: FloorExperienceDefinition = {
  id: "floor-07-sunset-index-garden",
  floor: 7,
  title: "残照索引王苑",
  subtitle: "找不到的记录仍然存在；每一条捷径都决定谁更容易被看见",
  version: 1,
  signature: "落日照亮的宽阔王苑、并存的扫描长路和索引短路、沿巨树根系展开的真实执行计划",
  assetPack: {
    id: "floor-07-sunset-index-garden-assets",
    version: 1,
    manifestPath: "/assets/floors/07-sunset-index-garden/manifest.json",
    assets: [],
  },
  regions: [
    {
      id: "f7-crystal-grove",
      navigationRegion: "front",
      name: "水晶枝径",
      purpose: "让主键点查与联合索引成为两条可比较的实体道路",
      lessonIds: ["f7-btree", "f7-composite"],
      material: "暖白石径、青色晶枝、低矮残墙与长影",
      ambience: "抒情大提琴、柔和木管与远处庭院钟",
      landmarkIds: ["f7-spawn-gate", "f7-scan-road", "f7-index-road", "f7-front-fire"],
    },
    {
      id: "f7-root-cloister",
      navigationRegion: "middle",
      name: "盘根回廊",
      purpose: "用覆盖索引与范围改写区分必要回表和可以避免的绕行",
      lessonIds: ["f7-covering", "f7-invalid"],
      material: "紫褐树根、镜面浅湖、断裂拱廊与金色叶片",
      ambience: "中提琴、竖琴泛音与稀疏落叶声",
      landmarkIds: ["f7-covering-lake", "f7-broken-root", "f7-blind-garden", "f7-rear-fire"],
    },
    {
      id: "f7-index-heart",
      navigationRegion: "rear",
      name: "索引树心",
      purpose: "把 EXPLAIN QUERY PLAN 的节点沿树根点亮，再证明路径不能改写事实",
      lessonIds: ["f7-plan", "f7-optimize"],
      material: "黑色树干、金色根脉、残照高窗与白石王座",
      ambience: "圆号、低弦与不喧闹的大编制残照主题",
      landmarkIds: ["f7-plan-tree", "f7-sql-seal", "f7-index-throne", "f7-ascent"],
    },
  ],
  landmarks: [
    landmark({
      id: "f7-spawn-gate",
      name: "残照晶门",
      kind: "spawn-anchor",
      regionId: "f7-crystal-grove",
      anchor: anchor("floor-7-entry", 0.5, 0.7, "north"),
      assetKey: "shared.setpiece.crystal-gate",
      fallback: "sunset-crystal-gate",
      interaction: null,
      stateKeys: ["always"],
    }),
    landmark({
      id: "f7-scan-road",
      name: "完整扫描长路",
      kind: "world-machine",
      regionId: "f7-crystal-grove",
      anchor: anchor("floor-7-lesson-1", 0.3, 0.5, "north", 7, 5),
      assetKey: "shared.setpiece.scan-road",
      fallback: "scan-road",
      interaction: "查看不依赖索引、但能抵达所有记录的长路",
      stateKeys: ["open"],
      minimapIcon: "route",
    }),
    landmark({
      id: "f7-index-road",
      name: "主键晶枝短路",
      kind: "world-machine",
      regionId: "f7-crystal-grove",
      anchor: anchor("floor-7-lesson-2", 0.68, 0.5, "north", 7, 5),
      assetKey: "shared.setpiece.index-road",
      fallback: "index-shortcut",
      interaction: "按最左前缀点亮索引短路",
      stateKeys: ["dark", "point-search", "composite"],
      minimapIcon: "shortcut",
    }),
    landmark({
      id: "f7-front-fire",
      name: "晶枝篝火",
      kind: "campfire",
      regionId: "f7-crystal-grove",
      anchor: anchor("floor-7-rest", 0.52, 0.62),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f7-covering-lake",
      name: "覆盖镜湖",
      kind: "world-machine",
      regionId: "f7-root-cloister",
      anchor: anchor("floor-7-lesson-3", 0.5, 0.48, "west", 8, 6),
      assetKey: "shared.setpiece.covering-lake",
      fallback: "covering-index-lake",
      interaction: "观察只读取索引列时不必返回数据页",
      stateKeys: ["reflecting-table", "covering"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f7-broken-root",
      name: "函数缠绕根门",
      kind: "world-machine",
      regionId: "f7-root-cloister",
      anchor: anchor("floor-7-lesson-4", 0.5, 0.46, "north", 8, 6),
      assetKey: "shared.setpiece.root-gate",
      fallback: "range-root-gate",
      interaction: "把函数过滤改写成可沿索引前进的范围",
      stateKeys: ["entangled", "range-open"],
      minimapIcon: "route",
    }),
    landmark({
      id: "f7-blind-garden",
      name: "盲索引花园",
      kind: "story",
      regionId: "f7-root-cloister",
      anchor: anchor("floor-7-treasure", 0.5, 0.46, "south", 8, 7),
      assetKey: "shared.setpiece.blind-garden",
      fallback: "blind-index-garden",
      interaction: "查看被当前访问路径长期绕开的旧页",
      stateKeys: ["sealed", "open"],
      minimapIcon: "secret",
    }),
    landmark({
      id: "f7-rear-fire",
      name: "回廊篝火",
      kind: "campfire",
      regionId: "f7-root-cloister",
      anchor: anchor("floor-7-event", 0.72, 0.7),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或本层答案复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f7-plan-tree",
      name: "执行计划巨树",
      kind: "world-machine",
      regionId: "f7-index-heart",
      anchor: anchor("floor-7-lesson-5", 0.52, 0.48, "north", 9, 8),
      assetKey: "shared.setpiece.plan-tree",
      fallback: "query-plan-tree",
      interaction: "沿根系读取 SEARCH、SCAN 与临时排序节点",
      stateKeys: ["opaque", "explained"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f7-sql-seal",
      name: "最优叶密文门",
      kind: "sql-seal",
      regionId: "f7-index-heart",
      anchor: anchor("floor-7-lesson-6", 0.18, 0.56, "east", 3, 4),
      assetKey: "shared.setpiece.query-seal",
      fallback: "query-seal",
      interaction: "用分区最优叶提前点亮树心侧门",
      stateKeys: ["sealed", "decoded"],
      minimapIcon: "query",
    }),
    landmark({
      id: "f7-index-throne",
      name: "索引古树心",
      kind: "boss-arena",
      regionId: "f7-index-heart",
      anchor: anchor("floor-7-lesson-6", 0.52, 0.38, "north", 9, 8),
      assetKey: "shared.setpiece.index-throne",
      fallback: "index-tree-throne",
      interaction: "挑战 ID #072 并证明路径不等于事实",
      stateKeys: ["single-path", "paths-compared"],
      minimapIcon: "boss",
    }),
    landmark({
      id: "f7-ascent",
      name: "金色长阶",
      kind: "transit",
      regionId: "f7-index-heart",
      anchor: anchor("floor-7-lesson-6", 0.84, 0.7, "east", 4, 5),
      assetKey: "shared.setpiece.golden-stair",
      fallback: "golden-stair",
      interaction: "登上黑金高堂",
      stateKeys: ["shadowed", "sunlit"],
      minimapIcon: "ascent",
    }),
  ],
  npcPlacements: [{
    id: "npc-scribe-f7",
    name: "抄写员",
    role: "公开自己曾让部分历史变得不可访问的同行者",
    regionId: "f7-crystal-grove",
    anchor: anchor("floor-7-entry", 0.36, 0.46, "south", 2, 2),
    assetKey: "shared.actor.scribe",
    alwaysShowName: true,
  }],
  hiddenAreas: [{
    id: "f7-hidden-blind-garden",
    title: "盲索引花园",
    roomNodeId: "floor-7-treasure",
    gateId: "gate:floor-7-treasure",
    landmarkId: "f7-blind-garden",
    requiredLessonIds: ["f7-btree", "f7-composite", "f7-covering"],
    rewardArmorId: "crystal-armor",
    sealedPrompt: "E  调查没有任何索引指向的花墙",
    sealedMessage: "花墙要求先理解主键点查、联合索引和覆盖索引，才能分清‘不可达’与‘不存在’。",
    openPrompt: "E  沿完整扫描路进入盲索引花园",
    openedMessage: "花墙后仍保存着被快捷路径绕开数百年的旧页，中央晶枝结出一套确定获得的水晶甲。",
    discoveryEventId: "f7-story-blind-garden",
  }],
  storyEvents: [
    {
      id: "f7-story-unreached",
      title: "看不见不等于不存在",
      trigger: "floor-entered",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "music-state", state: "f7-sunset-cello-horn" },
        { type: "camera-focus", landmarkId: "f7-scan-road" },
        { type: "dialogue", speaker: "抄写员", lines: ["我曾帮王城决定谁更容易被找到。", "长路会经过每一页；索引短路只是路径，不是事实。"] },
      ],
      completionFact: "story:f7:entry-seen",
    },
    {
      id: "f7-story-blind-garden",
      title: "被绕开的仍然存在",
      trigger: "gate:floor-7-treasure:opened",
      repeat: "once",
      priority: 94,
      actions: [
        { type: "camera-focus", landmarkId: "f7-blind-garden" },
        { type: "dialogue", speaker: "抄写员", lines: ["被藏起的路径让第四层签名迟了数百年才被看见。", "未命中的记录仍在；花园只保存这件事造成的后果。"] },
      ],
      completionFact: "story:f7:blind-garden",
    },
    {
      id: "f7-story-root-cloister-open",
      title: "错误前缀解除",
      trigger: "monster:77:defeated",
      repeat: "once",
      priority: 95,
      actions: [
        { type: "camera-focus", landmarkId: "f7-broken-root" },
        { type: "world-effect", effect: "f7-root-cloister-open" },
        { type: "banner", text: "错误前缀解除 · 索引树心可达" },
        { type: "dialogue", speaker: "抄写员", lines: ["最左前缀是一份路径契约，不是真相裁决。", "错误的根已经退开，完整扫描仍会与我们同行。"] },
      ],
      completionFact: "story:f7:root-cloister-open",
    },
    {
      id: "f7-story-cipher",
      title: "最优叶密文被解开",
      trigger: "gate:floor-7-lesson-6:opened",
      repeat: "once",
      priority: 88,
      actions: [
        { type: "camera-focus", landmarkId: "f7-sql-seal" },
        { type: "world-effect", effect: "f7-cipher-decoded" },
        { type: "banner", text: "每个 realm 的最优叶已定位；树心侧门永久点亮" },
      ],
      completionFact: "story:f7:cipher",
    },
    {
      id: "f7-story-paths-compared",
      title: "路径不能改写事实",
      trigger: "monster:72:defeated",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "camera-focus", landmarkId: "f7-index-throne" },
        { type: "evidence", evidenceId: "lost-name:f7:scan-proof" },
        { type: "dialogue", speaker: "抄写员", lines: ["最快的路径不是唯一的事实。", "现在我们带着完整扫描和索引证据，一起去见那位档案官。"] },
      ],
      completionFact: "story:f7:completed",
    },
  ],
  environmentRules: [
    { id: "f7-point-search-lit", when: "f7-btree:completed", state: "index_path=point-search", visibleResult: "主键晶枝点亮一条精确短路" },
    { id: "f7-composite-lit", when: "f7-composite:completed", state: "index_path=composite", visibleResult: "联合索引沿最左前缀继续展开" },
    { id: "f7-covering-reflection", when: "f7-covering:completed", state: "lake=covering", visibleResult: "镜湖只反射索引页，不再回到数据页" },
    { id: "f7-range-root-open", when: "f7-invalid:completed", state: "root_gate=range-open", visibleResult: "函数缠绕退去，范围根道恢复可行" },
    { id: "f7-plan-explained", when: "f7-plan:completed", state: "plan_tree=explained", visibleResult: "巨树根系依次显示 SEARCH、SCAN 与排序节点" },
    { id: "f7-paths-compared", when: "f7-optimize:completed", state: "throne=paths-compared", visibleResult: "扫描长路和索引短路同时保留，金色长阶点亮" },
  ],
  adminPresets: [
    { id: "f7-admin-entry", label: "F7 扫描与索引双路", completedLessonIds: [], defeatedMonsterIds: [], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f7-scan-road" },
    { id: "f7-admin-garden", label: "F7 盲索引花园", completedLessonIds: ["f7-btree", "f7-composite", "f7-covering"], defeatedMonsterIds: [67, 68, 69], openedGateIds: ["gate:floor-7-treasure"], collectedKeyItems: [], focusLandmarkId: "f7-blind-garden" },
    { id: "f7-admin-cipher", label: "F7 最优叶密文门", completedLessonIds: ["f7-btree", "f7-composite", "f7-covering", "f7-invalid"], defeatedMonsterIds: [67, 68, 69, 70], openedGateIds: ["gate:floor-7-lesson-6"], collectedKeyItems: [], focusLandmarkId: "f7-sql-seal" },
    { id: "f7-admin-root-cloister", label: "F7 根系回廊", completedLessonIds: ["f7-btree", "f7-composite", "f7-covering", "f7-invalid"], defeatedMonsterIds: [67, 68, 69, 70, 77], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f7-broken-root" },
    { id: "f7-admin-complete", label: "F7 残照树心", completedLessonIds: ["f7-btree", "f7-composite", "f7-covering", "f7-invalid", "f7-plan", "f7-optimize"], defeatedMonsterIds: [67, 68, 69, 70, 71, 72, 77], openedGateIds: ["shortcut:7:return"], collectedKeyItems: ["floor-key:7"], focusLandmarkId: "f7-index-throne" },
  ],
};
