import type { LessonStageDefinition, Monster } from "../../../../domain/shared/types";
import {
  biomeMonster,
  type BiomeEncounterDefinition,
} from "../shared/biome";

export const FLOOR_THREE_BIOME_MONSTERS: readonly Monster[] = [
  biomeMonster({
    floor: 3,
    id: 29,
    lessonId: "f3-inner",
    roomId: 47,
    name: "碎骨",
    species: "bone_scout",
    kind: "skeleton",
    hp: 16,
    maxHp: 16,
    armor: 0,
    damage: 2,
    attackName: "碎骨突刺",
    status: "patrolling",
    weakness: "join",
    masterId: 28,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 3,
    id: 30,
    lessonId: "f3-left",
    roomId: 48,
    name: "腐尸",
    species: "grave_zombie",
    kind: "zombie",
    hp: 16,
    maxHp: 16,
    armor: 0,
    damage: 2,
    attackName: "腐土抓击",
    status: "wandering",
    weakness: "left",
    masterId: 28,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 3,
    id: 31,
    lessonId: "f3-self",
    roomId: 49,
    name: "鬼火",
    species: "spirit_flame",
    kind: "ghost",
    hp: 24,
    maxHp: 24,
    armor: 1,
    damage: 3,
    attackName: "灵焰追踪",
    status: "haunting",
    weakness: "alias",
    masterId: 33,
    isBoss: false,
    rank: "elite",
  }),
  biomeMonster({
    floor: 3,
    id: 32,
    lessonId: "f3-self",
    roomId: 49,
    name: "游魂",
    species: "crypt_wraith",
    kind: "ghost",
    hp: 16,
    maxHp: 16,
    armor: 0,
    damage: 2,
    attackName: "魂火扑击",
    status: "drifting",
    weakness: "alias",
    masterId: 33,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 3,
    id: 33,
    lessonId: "f3-union",
    roomId: 50,
    name: "墓主",
    species: "tomb_lord",
    kind: "necromancer",
    hp: 28,
    maxHp: 28,
    armor: 2,
    damage: 3,
    attackName: "墓碑合流",
    status: "sealed",
    weakness: "union",
    masterId: 28,
    isBoss: true,
    rank: "elite",
  }),
] as const;

const PRACTICE_BONE: LessonStageDefinition = {
  id: "practice-bone",
  objective: "连接 monsters 与 rooms，查询 id = 29 的 id 与 room_name。",
  queryTemplate: "",
  answerSql: "SELECT m.id, r.name AS room_name FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 29;",
  hints: [
    "读取怪物 ID 与房间名。",
    "连接 monsters 与 rooms。",
    "ON m.room_id = r.id。",
    "完整写法：SELECT m.id, r.name AS room_name FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 29;",
  ],
  locks: ["INNER JOIN", "ON"],
  requiredFeatures: ["join", "on"],
  attackTargetIds: [29],
};

const PRACTICE_ZOMBIE: LessonStageDefinition = {
  id: "practice-zombie",
  objective: "LEFT JOIN 装备表，找出 id = 30 且没有装备的记录。",
  queryTemplate: "",
  answerSql: "SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 30 AND g.monster_id IS NULL;",
  hints: [
    "从 monsters m 开始。",
    "LEFT JOIN monster_gear g。",
    "检查 g.monster_id IS NULL。",
    "完整写法：SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 30 AND g.monster_id IS NULL;",
  ],
  locks: ["LEFT JOIN", "IS NULL"],
  requiredFeatures: ["left-join", "is-null"],
  attackTargetIds: [30],
};

const PRACTICE_SPIRIT: LessonStageDefinition = {
  id: "practice-spirit",
  objective: "自连接 monsters，查询 ID #031 的 child_id 与 master_id。",
  queryTemplate: "",
  answerSql: "SELECT child.id AS child_id, master.id AS master_id FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 31;",
  hints: [
    "同一张表使用 child 与 master 两个别名。",
    "连接 child.master_id = master.id。",
    "锁定 child.id = 31。",
    "完整写法：SELECT child.id AS child_id, master.id AS master_id FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 31;",
  ],
  locks: ["SELF JOIN", "ON"],
  requiredFeatures: ["self-join", "on"],
  attackTargetIds: [31],
};

const PRACTICE_SPIRIT_CORE: LessonStageDefinition = {
  id: "practice-spirit-core",
  objective: "第二击保留自连接，再加入已学过的状态过滤。返回 ID #031 的 child_id 与 master_id，并确认 child.status = 'haunting'。",
  queryTemplate: "",
  answerSql: "SELECT child.id AS child_id, master.id AS master_id FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 31 AND child.status = 'haunting';",
  hints: [
    "继续给 monsters 使用 child 与 master 两个别名。",
    "连接 child.master_id = master.id。",
    "用 AND 检查 child.status = 'haunting'。",
    "完整写法：SELECT child.id AS child_id, master.id AS master_id FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 31 AND child.status = 'haunting';",
  ],
  locks: ["SELF JOIN", "ON", "AND"],
  requiredFeatures: ["self-join", "on", "and"],
  attackTargetIds: [31],
};

const PRACTICE_WRAITH: LessonStageDefinition = {
  id: "practice-wraith",
  objective: "自连接 monsters，查询 ID #032 的 child_id 与 master_id。",
  queryTemplate: "",
  answerSql: "SELECT child.id AS child_id, master.id AS master_id FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 32;",
  hints: [
    "同一张表使用两个别名。",
    "连接 child.master_id = master.id。",
    "锁定 child.id = 32。",
    "完整写法：SELECT child.id AS child_id, master.id AS master_id FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 32;",
  ],
  locks: ["SELF JOIN", "ON"],
  requiredFeatures: ["self-join", "on"],
  attackTargetIds: [32],
};

const GRAVE_BOSS_SCAN: LessonStageDefinition = {
  id: "grave-boss-scan",
  objective: "区域首领第一击：给三张表使用别名，连接 monsters、rooms、monster_gear，返回 ID #033 的 m.id、r.name AS room_name 与 g.power。",
  queryTemplate: "",
  answerSql: "SELECT m.id, r.name AS room_name, g.power FROM monsters m INNER JOIN rooms r ON m.room_id = r.id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 33;",
  hints: [
    "monsters 使用 m，rooms 使用 r，monster_gear 使用 g。",
    "先用 m.room_id = r.id 连接房间。",
    "再用 m.id = g.monster_id 连接装备。",
    "完整写法：SELECT m.id, r.name AS room_name, g.power FROM monsters m INNER JOIN rooms r ON m.room_id = r.id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 33;",
  ],
  locks: ["INNER JOIN", "ON"],
  requiredFeatures: ["join", "on"],
  attackTargetIds: [33],
};

const GRAVE_BOSS_CORE: LessonStageDefinition = {
  id: "grave-boss-core",
  objective: "区域首领第二击：自连接 monsters，返回 id = 33 的 child_id 与 master_id。",
  queryTemplate: "",
  answerSql: "SELECT child.id AS child_id, master.id AS master_id FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 33;",
  hints: [
    "为 monsters 使用 child 与 master 两个别名。",
    "连接 child.master_id = master.id。",
    "锁定 child.id = 33。",
    "完整写法：SELECT child.id AS child_id, master.id AS master_id FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 33;",
  ],
  locks: ["SELF JOIN", "ON"],
  requiredFeatures: ["self-join", "on"],
  attackTargetIds: [33],
};

export const FLOOR_BIOME_ENCOUNTERS = [
  { monsterId: 29, floor: 3, biome: "bone-yard", role: "normal", randomEncounter: true, stages: [PRACTICE_BONE] },
  { monsterId: 30, floor: 3, biome: "grave-mire", role: "normal", randomEncounter: true, stages: [PRACTICE_ZOMBIE] },
  { monsterId: 31, floor: 3, biome: "spirit-crypt", role: "mini-elite", randomEncounter: true, stages: [PRACTICE_SPIRIT, PRACTICE_SPIRIT_CORE] },
  { monsterId: 32, floor: 3, biome: "spirit-crypt", role: "normal", randomEncounter: true, stages: [PRACTICE_WRAITH] },
  { monsterId: 33, floor: 3, biome: "grave-mire", role: "area-boss", randomEncounter: false, stages: [GRAVE_BOSS_SCAN, GRAVE_BOSS_CORE] },
] as const satisfies readonly BiomeEncounterDefinition[];
