import type { LessonStageDefinition, Monster } from "../../../../domain/shared/types";
import {
  biomeMonster,
  type BiomeEncounterDefinition,
} from "../shared/biome";

/** 第四层生态遭遇池：火/冰/雷怪物共享楼层的子查询课程推进。 */
export const FLOOR_FOUR_BIOME_MONSTERS: readonly Monster[] = [
  biomeMonster({
    floor: 4,
    id: 40,
    lessonId: "f4-scalar",
    roomId: 57,
    name: "火苗",
    species: "ember_sprite",
    kind: "fire-spirit",
    hp: 18,
    maxHp: 18,
    armor: 0,
    damage: 3,
    attackName: "火苗飞射",
    status: "sparking",
    weakness: "scalar",
    masterId: 44,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 4,
    id: 41,
    lessonId: "f4-in",
    roomId: 58,
    name: "冰晶",
    species: "frost_shard",
    kind: "ice-spirit",
    hp: 18,
    maxHp: 18,
    armor: 0,
    damage: 3,
    attackName: "冰晶散射",
    status: "frozen",
    weakness: "in",
    masterId: 44,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 4,
    id: 42,
    lessonId: "f4-exists",
    roomId: 59,
    name: "雷兽",
    species: "storm_beast",
    kind: "thunder-spirit",
    hp: 27,
    maxHp: 27,
    armor: 1,
    damage: 3,
    attackName: "雷爪",
    status: "charged",
    weakness: "exists",
    masterId: 44,
    isBoss: false,
    rank: "elite",
  }),
  biomeMonster({
    floor: 4,
    id: 43,
    lessonId: "f4-exists",
    roomId: 59,
    name: "电球",
    species: "storm_orb",
    kind: "thunder-spirit",
    hp: 18,
    maxHp: 18,
    armor: 0,
    damage: 3,
    attackName: "电弧撞击",
    status: "sparking",
    weakness: "exists",
    masterId: 44,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 4,
    id: 44,
    lessonId: "f4-in",
    roomId: 60,
    name: "霜炉主",
    species: "mirror_forge_lord",
    kind: "elemental-king",
    hp: 32,
    maxHp: 32,
    armor: 2,
    damage: 4,
    attackName: "炉火封锁",
    status: "sealed",
    weakness: "cte",
    masterId: 39,
    isBoss: true,
    rank: "elite",
  }),
] as const;

const PRACTICE_FIRE: LessonStageDefinition = {
  id: "practice-fire",
  objective: "用标量子查询返回 room_id = 57 中最小的 id。",
  queryTemplate: "",
  answerSql: "SELECT id FROM monsters WHERE id = (SELECT MIN(id) FROM monsters WHERE room_id = 57);",
  hints: [
    "外层读取 id。",
    "内层计算 room_id = 57 的 MIN(id)。",
    "外层用 id = (...)。",
    "完整写法：SELECT id FROM monsters WHERE id = (SELECT MIN(id) FROM monsters WHERE room_id = 57);",
  ],
  locks: ["SUBQUERY"],
  requiredFeatures: ["subquery"],
  attackTargetIds: [40],
};

const PRACTICE_ICE: LessonStageDefinition = {
  id: "practice-ice",
  objective: "用 IN 子查询返回 room_id 位于 frost-vault 区域的怪物 id。",
  queryTemplate: "",
  answerSql: "SELECT id FROM monsters WHERE room_id IN (SELECT id FROM rooms WHERE sector = 'frost-vault') ORDER BY id;",
  hints: [
    "内层从 rooms 查询 id。",
    "过滤 sector = 'frost-vault'。",
    "外层用 room_id IN (...)。",
    "完整写法：SELECT id FROM monsters WHERE room_id IN (SELECT id FROM rooms WHERE sector = 'frost-vault') ORDER BY id;",
  ],
  locks: ["IN", "SUBQUERY"],
  requiredFeatures: ["in", "subquery"],
  attackTargetIds: [41],
};

const PRACTICE_STORM: LessonStageDefinition = {
  id: "practice-storm",
  objective: "用 EXISTS 查询 id = 42 且存在装备记录的怪物 id。",
  queryTemplate: "",
  answerSql: "SELECT m.id FROM monsters m WHERE m.id = 42 AND EXISTS (SELECT 1 FROM monster_gear g WHERE g.monster_id = m.id);",
  hints: [
    "外层锁定 ID #042。",
    "EXISTS 内层查询 monster_gear。",
    "用 g.monster_id = m.id 相关。",
    "完整写法：SELECT m.id FROM monsters m WHERE m.id = 42 AND EXISTS (SELECT 1 FROM monster_gear g WHERE g.monster_id = m.id);",
  ],
  locks: ["EXISTS", "SUBQUERY"],
  requiredFeatures: ["exists", "subquery"],
  attackTargetIds: [42],
};

const PRACTICE_STORM_CORE: LessonStageDefinition = {
  id: "practice-storm-core",
  objective: "第二击：查询 id = 42 且 status = 'charged' 的 id。",
  queryTemplate: "",
  answerSql: "SELECT id FROM monsters WHERE id = 42 AND status = 'charged';",
  hints: [
    "读取 id。",
    "使用 WHERE 与 AND。",
    "同时限定 id 和 status。",
    "完整写法：SELECT id FROM monsters WHERE id = 42 AND status = 'charged';",
  ],
  locks: ["WHERE", "AND"],
  requiredFeatures: ["where", "and"],
  attackTargetIds: [42],
};

const PRACTICE_SPARK: LessonStageDefinition = {
  id: "practice-spark",
  objective: "用 EXISTS 查询 id = 43 且存在装备记录的怪物 id。",
  queryTemplate: "",
  answerSql: "SELECT m.id FROM monsters m WHERE m.id = 43 AND EXISTS (SELECT 1 FROM monster_gear g WHERE g.monster_id = m.id);",
  hints: [
    "外层读取 m.id。",
    "EXISTS 内层检查 monster_gear。",
    "通过 g.monster_id = m.id 关联。",
    "完整写法：SELECT m.id FROM monsters m WHERE m.id = 43 AND EXISTS (SELECT 1 FROM monster_gear g WHERE g.monster_id = m.id);",
  ],
  locks: ["EXISTS", "SUBQUERY"],
  requiredFeatures: ["exists", "subquery"],
  attackTargetIds: [43],
};

const FORGE_BOSS_SCAN: LessonStageDefinition = {
  id: "forge-boss-scan",
  objective: "区域首领第一击：用 IN 子查询筛出装备 power >= 22 的怪物，并只返回 ID #044 的 id。",
  queryTemplate: "",
  answerSql: "SELECT id FROM monsters WHERE id = 44 AND id IN (SELECT monster_id FROM monster_gear WHERE power >= 22);",
  hints: [
    "外层从 monsters 返回 id。",
    "先锁定 id = 44。",
    "IN 子查询从 monster_gear 返回 power >= 22 的 monster_id。",
    "完整写法：SELECT id FROM monsters WHERE id = 44 AND id IN (SELECT monster_id FROM monster_gear WHERE power >= 22);",
  ],
  locks: ["IN", "SUBQUERY"],
  requiredFeatures: ["in", "subquery"],
  attackTargetIds: [44],
};

const FORGE_BOSS_CORE: LessonStageDefinition = {
  id: "forge-boss-core",
  objective: "区域首领第二击：用 EXISTS 返回 id = 44 且存在装备记录的 id。",
  queryTemplate: "",
  answerSql: "SELECT m.id FROM monsters m WHERE m.id = 44 AND EXISTS (SELECT 1 FROM monster_gear g WHERE g.monster_id = m.id);",
  hints: [
    "外层读取 m.id。",
    "EXISTS 检查装备记录。",
    "内层关联 g.monster_id = m.id。",
    "完整写法：SELECT m.id FROM monsters m WHERE m.id = 44 AND EXISTS (SELECT 1 FROM monster_gear g WHERE g.monster_id = m.id);",
  ],
  locks: ["EXISTS", "SUBQUERY"],
  requiredFeatures: ["exists", "subquery"],
  attackTargetIds: [44],
};

export const FLOOR_BIOME_ENCOUNTERS = [
  { monsterId: 40, floor: 4, biome: "fire-forge", role: "normal", randomEncounter: true, stages: [PRACTICE_FIRE] },
  { monsterId: 41, floor: 4, biome: "frost-vault", role: "normal", randomEncounter: true, stages: [PRACTICE_ICE] },
  { monsterId: 42, floor: 4, biome: "storm-core", role: "mini-elite", randomEncounter: true, stages: [PRACTICE_STORM, PRACTICE_STORM_CORE] },
  { monsterId: 43, floor: 4, biome: "storm-core", role: "normal", randomEncounter: true, stages: [PRACTICE_SPARK] },
  { monsterId: 44, floor: 4, biome: "frost-vault", role: "area-boss", randomEncounter: false, stages: [FORGE_BOSS_SCAN, FORGE_BOSS_CORE] },
] as const satisfies readonly BiomeEncounterDefinition[];
