import type {
  LessonDefinition,
  Monster,
  Weapon,
} from "../domain/types";
import { COMPLETE_SCHEMA_LINES } from "./sqlSchema";

export const BONE_BLADE: Weapon = {
  id: "bone-blade",
  name: "骨剑",
  damage: 16,
  heatReduction: 0,
  description: "亡者墓城的必修武器。正确查询造成 16 点伤害，不会跳过题目阶段。",
};

export const FLOOR_THREE_MONSTERS: readonly Monster[] = [
  {
    floor: 3,
    id: 23,
    lessonId: "f3-inner",
    roomId: 41,
    name: "骷髅",
    species: "grave_skeleton",
    kind: "skeleton",
    x: 1,
    y: 1,
    hp: 15,
    maxHp: 15,
    armor: 0,
    damage: 2,
    attackName: "骨刀横扫",
    status: "guarding",
    weakness: "join",
    masterId: 28,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 3,
    id: 24,
    lessonId: "f3-left",
    roomId: 42,
    name: "僵尸",
    species: "grave_zombie",
    kind: "zombie",
    x: 1,
    y: 1,
    hp: 16,
    maxHp: 16,
    armor: 0,
    damage: 2,
    attackName: "墓土拍击",
    status: "unarmed",
    weakness: "left",
    masterId: 28,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 3,
    id: 25,
    lessonId: "f3-self",
    roomId: 43,
    name: "幽灵",
    species: "crypt_ghost",
    kind: "ghost",
    x: 1,
    y: 1,
    hp: 16,
    maxHp: 16,
    armor: 0,
    damage: 2,
    attackName: "灵火穿透",
    status: "bound",
    weakness: "alias",
    masterId: 28,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 3,
    id: 26,
    lessonId: "f3-chain",
    roomId: 44,
    name: "铠骷髅",
    species: "armored_skeleton",
    kind: "skeleton",
    x: 1,
    y: 1,
    hp: 15,
    maxHp: 15,
    armor: 1,
    damage: 3,
    attackName: "铠骨重斩",
    status: "armored",
    weakness: "chain",
    masterId: 28,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 3,
    id: 27,
    lessonId: "f3-union",
    roomId: 45,
    name: "骨骑士",
    species: "bone_knight",
    kind: "skeleton",
    x: 1,
    y: 1,
    hp: 15,
    maxHp: 15,
    armor: 1,
    damage: 3,
    attackName: "双墓冲锋",
    status: "mounted",
    weakness: "union",
    masterId: 28,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 3,
    id: 28,
    lessonId: "f3-audit",
    roomId: 46,
    name: "死灵王",
    species: "necromancer_king",
    kind: "necromancer",
    x: 1,
    y: 1,
    hp: 28,
    maxHp: 28,
    armor: 2,
    damage: 3,
    attackName: "亡者审计",
    status: "ruling",
    weakness: "audit",
    masterId: null,
    isBoss: true,
    rank: "boss",
    encounterType: "curriculum",
  },
] as const;

const SCHEMA = [...COMPLETE_SCHEMA_LINES];

export const FLOOR_THREE_LESSON_DEFINITIONS: readonly LessonDefinition[] = [
  {
    id: "f3-inner",
    concept: "INNER JOIN / ON",
    title: "骨桥前庭 · 匹配两表",
    intro: "ID #023 的房间名在 rooms 表。用真实键关系把怪物记录与墓室接起来。",
    schema: SCHEMA,
    primaryMonsterId: 23,
    stages: [{
      id: "f3-inner-room",
      objective: "给 monsters 起别名 m、rooms 起别名 r；连接两表后，查询 m.id = 23 的 m.id，以及房间名 r.name AS room_name。",
      queryTemplate: "",
      answerSql: "SELECT m.id, r.name AS room_name FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 23;",
      hints: [
        "需要读取怪物 ID 和房间名。",
        "连接 monsters 与 rooms。",
        "关系是 m.room_id = r.id。",
        "用 WHERE m.id = 23 锁定 ID #023。",
        "完整写法：SELECT m.id, r.name AS room_name FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 23;",
      ],
      locks: ["INNER JOIN", "ON"],
      requiredFeatures: ["join", "on"],
      attackTargetIds: [23],
    }],
  },
  {
    id: "f3-left",
    concept: "LEFT JOIN / IS NULL",
    title: "空甲墓道 · 保留左表",
    intro: "ID #024 没有装备记录。保留怪物主表，再用右表空值找出它。",
    schema: SCHEMA,
    primaryMonsterId: 24,
    stages: [{
      id: "f3-left-unarmed",
      objective: "给 monsters 起别名 m、monster_gear 起别名 g；LEFT JOIN 后返回 m.room_id = 42 且 g.monster_id IS NULL 的怪物主键 m.id。",
      queryTemplate: "",
      answerSql: "SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id = 42 AND g.monster_id IS NULL;",
      hints: [
        "从 monsters m 开始。",
        "LEFT JOIN monster_gear g。",
        "ON m.id = g.monster_id。",
        "过滤 room_id = 42 与 g.monster_id IS NULL。",
        "完整写法：SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id = 42 AND g.monster_id IS NULL;",
      ],
      locks: ["LEFT JOIN", "ON", "IS NULL"],
      requiredFeatures: ["left-join", "on", "is-null"],
      attackTargetIds: [24],
    }],
  },
  {
    id: "f3-self",
    concept: "SELF JOIN / 别名",
    title: "回声灵堂 · 自连接",
    intro: "ID #025 与其上级记录都在 monsters 表。为同一张表取两个身份。",
    schema: SCHEMA,
    primaryMonsterId: 25,
    stages: [{
      id: "f3-self-master",
      objective: "把 monsters 分别命名为 child 与 master；自连接后查询 child.id = 25 的 child.id AS child_id 和 master.id AS master_id。",
      queryTemplate: "",
      answerSql: "SELECT child.id AS child_id, master.id AS master_id FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 25;",
      hints: [
        "同一张 monsters 表要使用两次。",
        "给它们取 child 与 master 两个别名。",
        "连接 child.master_id = master.id。",
        "用 child.id = 25 锁定 ID #025。",
        "完整写法：SELECT child.id AS child_id, master.id AS master_id FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 25;",
      ],
      locks: ["SELF JOIN", "ON"],
      requiredFeatures: ["self-join", "on"],
      attackTargetIds: [25],
    }],
  },
  {
    id: "f3-chain",
    concept: "三表 JOIN 链",
    title: "骑士墓 · 串联三表",
    intro: "ID #026、所在墓室和武器力量分散在三张表里。",
    schema: SCHEMA,
    primaryMonsterId: 26,
    stages: [{
      id: "f3-chain-gear",
      objective: "给 rooms、monsters、monster_gear 分别起别名 r、m、g；连接三表后返回 m.id = 26 的 r.name AS room_name、m.id、g.power。",
      queryTemplate: "",
      answerSql: "SELECT r.name AS room_name, m.id, g.power FROM rooms r INNER JOIN monsters m ON r.id = m.room_id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 26;",
      hints: [
        "需要 rooms、monsters、monster_gear 三张表。",
        "先连接 r.id = m.room_id。",
        "再连接 m.id = g.monster_id。",
        "WHERE m.id = 26。",
        "完整写法：SELECT r.name AS room_name, m.id, g.power FROM rooms r INNER JOIN monsters m ON r.id = m.room_id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 26;",
      ],
      locks: ["JOIN × 2", "ON"],
      requiredFeatures: ["join", "on"],
      attackTargetIds: [26],
    }],
  },
  {
    id: "f3-union",
    concept: "UNION",
    title: "合葬厅 · 合并结果",
    intro: "两条墓道各有一组记录。用 UNION 合成一张去重名册。",
    schema: SCHEMA,
    primaryMonsterId: 27,
    stages: [{
      id: "f3-union-patrol",
      objective: "用 UNION 合并 monsters 中 room_id = 41 与 room_id = 43 的两组记录，统一返回 monsters.id，并按 id 升序。",
      queryTemplate: "",
      answerSql: "SELECT id FROM monsters WHERE room_id = 41 UNION SELECT id FROM monsters WHERE room_id = 43 ORDER BY id;",
      hints: [
        "先分别查询两条墓道。",
        "两边都只返回 id。",
        "用 UNION 合并并去重。",
        "最后按 id 排序。",
        "完整写法：SELECT id FROM monsters WHERE room_id = 41 UNION SELECT id FROM monsters WHERE room_id = 43 ORDER BY id;",
      ],
      locks: ["UNION", "ORDER BY"],
      requiredFeatures: ["union", "order-by"],
      attackTargetIds: [27],
    }],
  },
  {
    id: "f3-audit",
    concept: "JOIN 综合审计",
    title: "墓城王庭 · 关系审计",
    intro: "先审计墓城各区人数，再穿透装备表找到 ID #028 的核心记录。",
    schema: SCHEMA,
    primaryMonsterId: 28,
    stages: [
      {
        id: "f3-audit-groups",
        objective: "连接 monsters m 与 rooms r；按 r.sector 统计 m.room_id 在 41 至 46 的怪物数 AS total，只保留 total 不少于 2 的分组并排序。",
        queryTemplate: "",
        answerSql: "SELECT r.sector, COUNT(*) AS total FROM rooms r INNER JOIN monsters m ON r.id = m.room_id WHERE r.floor = 3 AND m.room_id BETWEEN 41 AND 46 GROUP BY r.sector HAVING COUNT(*) >= 2 ORDER BY r.sector;",
        hints: [
          "先连接 rooms 与 monsters。",
          "限定第三层和 room_id 41 至 46。",
          "按 r.sector 分组并 COUNT(*) AS total。",
          "HAVING COUNT(*) >= 2，最后排序。",
          "完整写法：SELECT r.sector, COUNT(*) AS total FROM rooms r INNER JOIN monsters m ON r.id = m.room_id WHERE r.floor = 3 AND m.room_id BETWEEN 41 AND 46 GROUP BY r.sector HAVING COUNT(*) >= 2 ORDER BY r.sector;",
        ],
        locks: ["JOIN", "GROUP BY", "HAVING"],
        requiredFeatures: ["join", "group-by", "having"],
        attackTargetIds: [28],
      },
      {
        id: "f3-audit-core",
        objective: "连接 monsters m 与 monster_gear g；在 m.room_id 41 至 46 中返回装备 power 最高怪物的 m.id 与 g.power。",
        queryTemplate: "",
        answerSql: "SELECT m.id, g.power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id BETWEEN 41 AND 46 ORDER BY g.power DESC LIMIT 1;",
        hints: [
          "连接 monsters 与 monster_gear。",
          "关系是 m.id = g.monster_id。",
          "限定 room_id 41 至 46。",
          "按 g.power DESC 排序并 LIMIT 1。",
          "完整写法：SELECT m.id, g.power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id BETWEEN 41 AND 46 ORDER BY g.power DESC LIMIT 1;",
        ],
        locks: ["JOIN", "ORDER BY", "LIMIT"],
        requiredFeatures: ["join", "order-by", "limit"],
        attackTargetIds: [28],
      },
    ],
  },
] as const;
