import type {
  LessonDefinition,
  Monster,
  Weapon,
} from "../domain/types";
import { COMPLETE_SCHEMA_LINES } from "./sqlSchema";

export const RUNE_STAFF: Weapon = {
  id: "rune-staff",
  name: "符文杖",
  damage: 18,
  heatReduction: 0,
  description: "元素熔炉的必修武器。正确查询造成 18 点伤害，不会跳过题目阶段。",
};

export const FLOOR_FOUR_MONSTERS: readonly Monster[] = [
  {
    floor: 4,
    id: 34,
    lessonId: "f4-scalar",
    roomId: 51,
    name: "火灵",
    species: "fire_spirit",
    kind: "fire-spirit",
    x: 1,
    y: 1,
    hp: 16,
    maxHp: 16,
    armor: 0,
    damage: 2,
    attackName: "火星喷射",
    status: "burning",
    weakness: "scalar",
    masterId: 37,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 4,
    id: 35,
    lessonId: "f4-in",
    roomId: 52,
    name: "冰灵",
    species: "ice_spirit",
    kind: "ice-spirit",
    x: 1,
    y: 1,
    hp: 18,
    maxHp: 18,
    armor: 0,
    damage: 2,
    attackName: "冰晶飞散",
    status: "frozen",
    weakness: "in",
    masterId: 39,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 4,
    id: 36,
    lessonId: "f4-exists",
    roomId: 53,
    name: "雷灵",
    species: "thunder_spirit",
    kind: "thunder-spirit",
    x: 1,
    y: 1,
    hp: 18,
    maxHp: 18,
    armor: 0,
    damage: 2,
    attackName: "雷弧反击",
    status: "charged",
    weakness: "exists",
    masterId: 39,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 4,
    id: 37,
    lessonId: "f4-correlated",
    roomId: 54,
    name: "石巨人",
    species: "forge_golem",
    kind: "aggregate-golem",
    x: 1,
    y: 1,
    hp: 17,
    maxHp: 17,
    armor: 1,
    damage: 2,
    attackName: "炉石重压",
    status: "forged",
    weakness: "correlated",
    masterId: 39,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 4,
    id: 38,
    lessonId: "f4-cte",
    roomId: 55,
    name: "炎王",
    species: "flame_lord",
    kind: "fire-spirit",
    x: 1,
    y: 1,
    hp: 17,
    maxHp: 17,
    armor: 1,
    damage: 2,
    attackName: "炎环爆发",
    status: "crowned",
    weakness: "cte",
    masterId: 39,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 4,
    id: 39,
    lessonId: "f4-recursive",
    roomId: 56,
    name: "元素王",
    species: "elemental_king",
    kind: "elemental-king",
    x: 1,
    y: 1,
    hp: 32,
    maxHp: 32,
    armor: 2,
    damage: 3,
    attackName: "元素坍缩",
    status: "ruling",
    weakness: "recursive",
    masterId: null,
    isBoss: true,
    rank: "boss",
    encounterType: "curriculum",
  },
] as const;

const SCHEMA = [...COMPLETE_SCHEMA_LINES];

export const FLOOR_FOUR_LESSON_DEFINITIONS: readonly LessonDefinition[] = [
  {
    id: "f4-scalar",
    concept: "标量子查询",
    title: "火室 · 用结果定位记录",
    intro: "先在内层得到一个 id，再由外层读取对应记录。",
    schema: SCHEMA,
    primaryMonsterId: 34,
    stages: [{
      id: "f4-scalar-first",
      objective: "外层从 monsters 读取 id；标量子查询先返回 monsters.room_id = 51 中最小的 monsters.id，再由外层定位该记录。",
      queryTemplate: "",
      answerSql: "SELECT id FROM monsters WHERE id = (SELECT MIN(id) FROM monsters WHERE room_id = 51);",
      hints: [
        "外层只读取 id。",
        "内层先查询 room_id = 51 的最小 id。",
        "把内层结果放到外层 id = (...)。",
        "完整写法：SELECT id FROM monsters WHERE id = (SELECT MIN(id) FROM monsters WHERE room_id = 51);",
      ],
      locks: ["SUBQUERY"],
      requiredFeatures: ["subquery"],
      attackTargetIds: [34],
    }],
  },
  {
    id: "f4-in",
    concept: "IN 子查询",
    title: "冰库 · 集合筛选",
    intro: "先让子查询返回寒霜房间集合，再筛选其中的怪物。",
    schema: SCHEMA,
    primaryMonsterId: 35,
    stages: [{
      id: "f4-in-frost",
      objective: "子查询从 rooms 返回 floor = 4 且 sector = 'frost' 的 rooms.id 集合；外层用 monsters.room_id IN (...) 返回 monsters.id，并按 id 排序。",
      queryTemplate: "",
      answerSql: "SELECT id FROM monsters WHERE room_id IN (SELECT id FROM rooms WHERE floor = 4 AND sector = 'frost') ORDER BY id;",
      hints: [
        "外层从 monsters 读取 id。",
        "内层从 rooms 读取 id。",
        "内层条件是 floor = 4 与 sector = 'frost'。",
        "外层用 room_id IN (...)，最后排序。",
        "完整写法：SELECT id FROM monsters WHERE room_id IN (SELECT id FROM rooms WHERE floor = 4 AND sector = 'frost') ORDER BY id;",
      ],
      locks: ["IN", "SUBQUERY", "ORDER BY"],
      requiredFeatures: ["in", "subquery", "order-by"],
      attackTargetIds: [35],
    }],
  },
  {
    id: "f4-exists",
    concept: "EXISTS",
    title: "雷池 · 判断记录存在",
    intro: "不要取出装备内容；只判断 ID #036 是否拥有装备记录。",
    schema: SCHEMA,
    primaryMonsterId: 36,
    stages: [{
      id: "f4-exists-gear",
      objective: "给 monsters 起别名 m、monster_gear 起别名 g；用 EXISTS 返回 m.id = 36 且存在 g.monster_id = m.id 装备记录的 m.id。",
      queryTemplate: "",
      answerSql: "SELECT m.id FROM monsters m WHERE m.id = 36 AND EXISTS (SELECT 1 FROM monster_gear g WHERE g.monster_id = m.id);",
      hints: [
        "外层读取 m.id。",
        "用 m.id = 36 锁定 ID #036。",
        "EXISTS 内层检查 monster_gear。",
        "内外层通过 g.monster_id = m.id 相关。",
        "完整写法：SELECT m.id FROM monsters m WHERE m.id = 36 AND EXISTS (SELECT 1 FROM monster_gear g WHERE g.monster_id = m.id);",
      ],
      locks: ["EXISTS", "SUBQUERY"],
      requiredFeatures: ["exists", "subquery"],
      attackTargetIds: [36],
    }],
  },
  {
    id: "f4-correlated",
    concept: "相关子查询",
    title: "石炉 · 逐行关联",
    intro: "内层装备查询要引用当前外层怪物，才能判断 ID #037 的力量。",
    schema: SCHEMA,
    primaryMonsterId: 37,
    stages: [{
      id: "f4-correlated-gear",
      objective: "给 monsters 起别名 m；相关子查询从 monster_gear g 计算当前 m.id 的 MAX(g.power)，返回 m.id = 37 且最高 power 不低于 18 的 m.id。",
      queryTemplate: "",
      answerSql: "SELECT m.id FROM monsters m WHERE m.id = 37 AND (SELECT MAX(g.power) FROM monster_gear g WHERE g.monster_id = m.id) >= 18;",
      hints: [
        "外层读取 m.id。",
        "内层从 monster_gear 计算 MAX(power)。",
        "内层条件引用外层 m.id。",
        "比较内层结果 >= 18。",
        "完整写法：SELECT m.id FROM monsters m WHERE m.id = 37 AND (SELECT MAX(g.power) FROM monster_gear g WHERE g.monster_id = m.id) >= 18;",
      ],
      locks: ["CORRELATED SUBQUERY"],
      requiredFeatures: ["subquery"],
      attackTargetIds: [37],
    }],
  },
  {
    id: "f4-cte",
    concept: "WITH / CTE",
    title: "符文环 · 命名中间结果",
    intro: "先把高 power 装备命名为 armored，再连接回怪物。",
    schema: SCHEMA,
    primaryMonsterId: 38,
    stages: [{
      id: "f4-cte-armor",
      objective: "用 CTE armored 保存 monster_gear 中 power >= 20 的 monster_id；主查询连接 monsters m 与 armored a，返回 m.id = 38 的 m.id。",
      queryTemplate: "",
      answerSql: "WITH armored AS (SELECT monster_id FROM monster_gear WHERE power >= 20) SELECT m.id FROM monsters m INNER JOIN armored a ON m.id = a.monster_id WHERE m.id = 38;",
      hints: [
        "先写 WITH armored AS (...)。",
        "CTE 中读取 power >= 20 的 monster_id。",
        "主查询连接 monsters 与 armored。",
        "用 m.id = 38 锁定 ID #038。",
        "完整写法：WITH armored AS (SELECT monster_id FROM monster_gear WHERE power >= 20) SELECT m.id FROM monsters m INNER JOIN armored a ON m.id = a.monster_id WHERE m.id = 38;",
      ],
      locks: ["WITH / CTE", "JOIN"],
      requiredFeatures: ["cte", "join"],
      attackTargetIds: [38],
    }],
  },
  {
    id: "f4-recursive",
    concept: "WITH RECURSIVE",
    title: "元素核心 · 递归追踪",
    intro: "先生成连续熔炉房间，再沿 master_id 追到 ID #039 的核心。",
    schema: SCHEMA,
    primaryMonsterId: 39,
    stages: [
      {
        id: "f4-recursive-rooms",
        objective: "用递归 CTE 生成 id 51 至 53；连接 rooms r 后返回 r.name AS room_name，并按 r.id 升序。",
        queryTemplate: "",
        answerSql: "WITH RECURSIVE room_ids(id) AS (SELECT 51 UNION ALL SELECT id + 1 FROM room_ids WHERE id < 53) SELECT r.name AS room_name FROM rooms r INNER JOIN room_ids x ON r.id = x.id ORDER BY r.id;",
        hints: [
          "使用 WITH RECURSIVE room_ids(id)。",
          "锚点是 SELECT 51。",
          "递归项每次 id + 1，直到 id < 53。",
          "连接 rooms 并按 r.id 排序。",
          "完整写法：WITH RECURSIVE room_ids(id) AS (SELECT 51 UNION ALL SELECT id + 1 FROM room_ids WHERE id < 53) SELECT r.name AS room_name FROM rooms r INNER JOIN room_ids x ON r.id = x.id ORDER BY r.id;",
        ],
        locks: ["WITH RECURSIVE", "UNION ALL"],
        requiredFeatures: ["cte", "recursive", "union"],
        attackTargetIds: [39],
      },
      {
        id: "f4-recursive-core",
        objective: "把 monsters 当前层命名为 m、递归结果命名为 lineage；从 m.id = 34 出发，递归沿 m.id = lineage.master_id 返回 id 与 depth，直到深度 3。",
        queryTemplate: "",
        answerSql: "WITH RECURSIVE lineage(id, master_id, depth) AS (SELECT id, master_id, 1 FROM monsters WHERE id = 34 UNION ALL SELECT m.id, m.master_id, l.depth + 1 FROM monsters m INNER JOIN lineage l ON m.id = l.master_id WHERE l.depth < 3) SELECT id, depth FROM lineage ORDER BY depth;",
        hints: [
          "CTE 保存 id、master_id、depth。",
          "锚点从 id = 34、depth = 1 开始。",
          "递归项连接 m.id = l.master_id。",
          "限制 l.depth < 3，最后按 depth 排序。",
          "完整写法：WITH RECURSIVE lineage(id, master_id, depth) AS (SELECT id, master_id, 1 FROM monsters WHERE id = 34 UNION ALL SELECT m.id, m.master_id, l.depth + 1 FROM monsters m INNER JOIN lineage l ON m.id = l.master_id WHERE l.depth < 3) SELECT id, depth FROM lineage ORDER BY depth;",
        ],
        locks: ["WITH RECURSIVE", "递归 JOIN"],
        requiredFeatures: ["cte", "recursive", "join"],
        attackTargetIds: [39],
      },
    ],
  },
] as const;
