import type {
  LessonDefinition,
  LessonId,
  LessonStageDefinition,
  Monster,
  Position,
  Weapon,
} from "../domain/types";
import { COMPLETE_SCHEMA_LINES } from "./sqlSchema";
import {
  BIOME_PRACTICE_STAGES,
  FLOOR_TWO_BIOME_MONSTERS,
} from "./biomeContent";

export const SORT_SABER: Weapon = {
  id: "sort-saber",
  name: "雷序军刀",
  damage: 13,
  heatReduction: 2,
  description: "把结果按顺序切开。正确排序时造成 13 点伤害，并减少 2 点查询热量。",
};

export const JOIN_CHAIN: Weapon = {
  id: "join-chain",
  name: "关系链刃",
  damage: 15,
  heatReduction: 3,
  description: "连接两张表的关系武器。正确 JOIN 时造成 15 点伤害，并减少 3 点查询热量。",
};

export const FLOOR_TWO_MONSTERS: readonly Monster[] = [
  {
    floor: 2,
    id: 1200,
    lessonId: "order-by",
    roomId: 21,
    name: "猎犬",
    species: "forest_hound_guard",
    kind: "filter-hound",
    x: 10,
    y: 5,
    hp: 24,
    maxHp: 24,
    armor: 0,
    damage: 1,
    attackName: "乱序扑咬",
    status: "charged",
    weakness: "descending",
    masterId: 77,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 2,
    id: 1300,
    lessonId: "distinct",
    roomId: 22,
    name: "水蛇",
    species: "water_snake_guard",
    kind: "distinct-mimic",
    x: 10,
    y: 5,
    hp: 13,
    maxHp: 13,
    armor: 0,
    damage: 1,
    attackName: "重复水纹",
    status: "mirrored",
    weakness: "unique",
    masterId: 77,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 2,
    id: 1400,
    lessonId: "inner-join",
    roomId: 23,
    name: "树妖",
    species: "forest_treant_guard",
    kind: "join-spider",
    x: 10,
    y: 5,
    hp: 26,
    maxHp: 26,
    armor: 0,
    damage: 1,
    attackName: "笛卡尔根网",
    status: "linked",
    weakness: "relation",
    masterId: 88,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 2,
    id: 1500,
    lessonId: "left-join",
    roomId: 24,
    name: "毒蛙",
    species: "poison_frog_guard",
    kind: "left-join-wraith",
    x: 10,
    y: 5,
    hp: 15,
    maxHp: 15,
    armor: 0,
    damage: 2,
    attackName: "右表毒沼",
    status: "unmatched",
    weakness: "left",
    masterId: null,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 2,
    id: 1900,
    lessonId: "join-boss",
    roomId: 25,
    name: "丛林王",
    species: "jungle_king",
    kind: "relation-titan",
    x: 10,
    y: 5,
    hp: 30,
    maxHp: 30,
    armor: 0,
    damage: 2,
    attackName: "丛林风暴",
    status: "conducting",
    weakness: "composite-query",
    masterId: 0,
    isBoss: true,
    rank: "boss",
    encounterType: "curriculum",
  },
  ...FLOOR_TWO_BIOME_MONSTERS,
] as const;

export const FLOOR_TWO_PRACTICE_STAGES: Readonly<Record<number, LessonStageDefinition>> =
  Object.fromEntries(
    Object.entries(BIOME_PRACTICE_STAGES)
      .filter(([id]) => Number(id) >= 1000)
      .map(([id, stages]) => [id, stages[0]]),
  );

const FLOOR_TWO_SCHEMA = [...COMPLETE_SCHEMA_LINES];

export const FLOOR_TWO_LESSONS: readonly LessonDefinition[] = [
  {
    id: "order-by",
    concept: "ORDER BY / LIMIT",
    title: "森林入口 · 排序与截取",
    intro: "猎犬把强弱信号打乱。先排序，再只取真正需要的前几行。",
    schema: FLOOR_TWO_SCHEMA,
    primaryMonsterId: 1200,
    stages: [
      {
        id: "order-peak",
        objective: "第一击：从 monster_signals 查询 monster_id = 1200 的最高 charge 对应 channel。",
        queryTemplate: "",
        answerSql: "SELECT channel FROM monster_signals WHERE monster_id = 1200 ORDER BY charge DESC LIMIT 1;",
        hints: [
          "数据表是 monster_signals。",
          "按 charge 降序排列。",
          "LIMIT 1 只保留最高值。",
          "完整写法：SELECT channel FROM monster_signals WHERE monster_id = 1200 ORDER BY charge DESC LIMIT 1;",
        ],
        locks: ["ORDER BY", "LIMIT"],
        requiredFeatures: ["order-by", "limit"],
        attackTargetIds: [1200],
      },
      {
        id: "order-top-two",
        objective: "第二击：按 charge 从高到低返回前两个 channel 与 charge。",
        queryTemplate: "",
        answerSql: "SELECT channel, charge FROM monster_signals WHERE monster_id = 1200 ORDER BY charge DESC LIMIT 2;",
        hints: [
          "SELECT channel, charge。",
          "仍然使用 ORDER BY charge DESC。",
          "把 LIMIT 改为 2。",
          "完整写法：SELECT channel, charge FROM monster_signals WHERE monster_id = 1200 ORDER BY charge DESC LIMIT 2;",
        ],
        locks: ["ORDER BY", "LIMIT"],
        requiredFeatures: ["order-by", "limit"],
        attackTargetIds: [1200],
      },
    ],
  },
  {
    id: "distinct",
    concept: "DISTINCT",
    title: "湖心石台 · 去除重复结果",
    intro: "水蛇把相同水纹复制成多行。DISTINCT 只保留真正不同的值。",
    schema: FLOOR_TWO_SCHEMA,
    primaryMonsterId: 1300,
    stages: [{
      id: "distinct-status",
      objective: "从 monster_signals 查询 monster_id = 1300 的不同 channel，并按 channel 升序排列。",
      queryTemplate: "",
      answerSql: "SELECT DISTINCT channel FROM monster_signals WHERE monster_id = 1300 ORDER BY channel;",
      hints: [
        "数据表是 monster_signals。",
        "SELECT 后加入 DISTINCT channel。",
        "WHERE 锁定 monster_id = 1300。",
        "完整写法：SELECT DISTINCT channel FROM monster_signals WHERE monster_id = 1300 ORDER BY channel;",
      ],
      locks: ["DISTINCT", "ORDER BY"],
      requiredFeatures: ["distinct", "order-by"],
      attackTargetIds: [1300],
    }],
  },
  {
    id: "inner-join",
    concept: "INNER JOIN / ON",
    title: "古树桥 · 连接怪物与房间",
    intro: "树妖的档案分散在两张表。用 room_id = rooms.id 把怪物档案与房间档案连接起来。",
    schema: FLOOR_TWO_SCHEMA,
    primaryMonsterId: 1400,
    stages: [
      {
        id: "inner-join-room",
        objective: "第一击：连接 monsters 与 rooms，查询 id = 1400 的 name 和 room_name。",
        queryTemplate: "",
        answerSql: "SELECT m.name, r.name AS room_name FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 1400;",
        hints: [
          "给 monsters 起别名 m，rooms 起别名 r。",
          "ON m.room_id = r.id。",
          "把 r.name 命名为 room_name。",
          "完整写法：SELECT m.name, r.name AS room_name FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 1400;",
        ],
        locks: ["INNER JOIN", "ON"],
        requiredFeatures: ["join", "on"],
        attackTargetIds: [1400],
      },
      {
        id: "inner-join-sector",
        objective: "第二击：连接两表，查询 id = 1400 的 name 与 sector。",
        queryTemplate: "",
        answerSql: "SELECT m.name, r.sector FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 1400;",
        hints: [
          "仍连接 monsters m 与 rooms r。",
          "连接条件保持为 ON m.room_id = r.id。",
          "这次读取 r.sector。",
          "完整写法：SELECT m.name, r.sector FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 1400;",
        ],
        locks: ["INNER JOIN", "ON"],
        requiredFeatures: ["join", "on"],
        attackTargetIds: [1400],
      },
    ],
  },
  {
    id: "left-join",
    concept: "LEFT JOIN / IS NULL",
    title: "毒雾泥沼 · 找出右表不存在的记录",
    intro: "毒蛙没有装备记录。保留左表全部怪物，再用右表 NULL 找出没有匹配项的实体。",
    schema: FLOOR_TWO_SCHEMA,
    primaryMonsterId: 1500,
    stages: [{
      id: "left-join-unarmed",
      objective: "LEFT JOIN 装备表，找出 room_id = 24 且没有装备记录的怪物 id。",
      queryTemplate: "",
      answerSql: "SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id = 24 AND g.monster_id IS NULL;",
      hints: [
        "从 monsters m LEFT JOIN monster_gear g。",
        "ON m.id = g.monster_id。",
        "WHERE 同时限制 room_id = 24 与 g.monster_id IS NULL。",
        "完整写法：SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id = 24 AND g.monster_id IS NULL;",
      ],
      locks: ["LEFT JOIN", "IS NULL"],
      requiredFeatures: ["left-join", "is-null"],
      attackTargetIds: [1500],
    }],
  },
  {
    id: "join-boss",
    concept: "JOIN 综合查询",
    title: "丛林王庭 · 多表综合查询",
    intro: "丛林王同时控制房间、怪物和装备。把 JOIN、分组过滤与排序组合成一条可核对的查询。",
    schema: FLOOR_TWO_SCHEMA,
    primaryMonsterId: 1900,
    stages: [
      {
        id: "join-boss-groups",
        objective: "护盾阶段：统计第二层各 sector 的怪物数，只保留至少 2 只的组，并按 total 降序。",
        queryTemplate: "",
        answerSql: "SELECT r.sector, COUNT(*) AS total FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE r.floor = 2 GROUP BY r.sector HAVING COUNT(*) >= 2 ORDER BY total DESC;",
        hints: [
          "连接 monsters m 与 rooms r。",
          "连接条件是 ON m.room_id = r.id。",
          "WHERE r.floor = 2，GROUP BY r.sector。",
          "HAVING COUNT(*) >= 2，最后 ORDER BY total DESC。",
          "完整写法：SELECT r.sector, COUNT(*) AS total FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE r.floor = 2 GROUP BY r.sector HAVING COUNT(*) >= 2 ORDER BY total DESC;",
        ],
        locks: ["INNER JOIN", "GROUP BY", "HAVING", "ORDER BY"],
        requiredFeatures: ["join", "group-by", "having", "order-by"],
        attackTargetIds: [1900],
      },
      {
        id: "join-boss-core",
        objective: "核心阶段：连接装备表，查询魔王最强装备对应的怪物 name 与 power。",
        queryTemplate: "",
        answerSql: "SELECT m.name, g.power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 1900 ORDER BY g.power DESC LIMIT 1;",
        hints: [
          "连接 monsters m 与 monster_gear g。",
          "连接条件是 ON m.id = g.monster_id。",
          "WHERE m.id = 1900。",
          "按 g.power 降序并 LIMIT 1。",
          "完整写法：SELECT m.name, g.power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 1900 ORDER BY g.power DESC LIMIT 1;",
        ],
        locks: ["INNER JOIN", "ORDER BY", "LIMIT"],
        requiredFeatures: ["join", "order-by", "limit"],
        attackTargetIds: [1900],
      },
    ],
  },
] as const;

export const FLOOR_TWO_LOOT_AFTER_LESSON: Partial<
  Record<LessonId, { weapon: Weapon; position: Position }>
> = {
  "order-by": { weapon: SORT_SABER, position: { x: 10, y: 5 } },
  "inner-join": { weapon: JOIN_CHAIN, position: { x: 10, y: 5 } },
};
