import type {
  LessonDefinition,
  LessonId,
  LessonStageDefinition,
  Monster,
  Position,
  Weapon,
} from "../domain/types";
import { COMPLETE_SCHEMA_LINES } from "./sqlSchema";
import {
  BIOME_PRACTICE_STAGES,
  FLOOR_TWO_BIOME_MONSTERS,
} from "./biomeContent";

export const SORT_SABER: Weapon = {
  id: "sort-saber",
  name: "雷序军刀",
  damage: 13,
  heatReduction: 2,
  description: "把结果按顺序切开。正确排序时造成 13 点伤害，并减少 2 点查询热量。",
};

export const JOIN_CHAIN: Weapon = {
  id: "join-chain",
  name: "关系链刃",
  damage: 15,
  heatReduction: 3,
  description: "连接两张表的关系武器。正确 JOIN 时造成 15 点伤害，并减少 3 点查询热量。",
};

export const FLOOR_TWO_MONSTERS: readonly Monster[] = [
  {
    floor: 2,
    id: 10,
    lessonId: "order-by",
    roomId: 21,
    name: "猎犬",
    species: "forest_hound_guard",
    kind: "filter-hound",
    x: 10,
    y: 5,
    hp: 24,
    maxHp: 24,
    armor: 0,
    damage: 2,
    attackName: "乱序扑咬",
    status: "charged",
    weakness: "descending",
    masterId: 14,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 2,
    id: 11,
    lessonId: "distinct",
    roomId: 22,
    name: "水蛇",
    species: "water_snake_guard",
    kind: "distinct-mimic",
    x: 10,
    y: 5,
    hp: 13,
    maxHp: 13,
    armor: 0,
    damage: 2,
    attackName: "重复水纹",
    status: "mirrored",
    weakness: "unique",
    masterId: 14,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 2,
    id: 12,
    lessonId: "inner-join",
    roomId: 23,
    name: "树妖",
    species: "forest_treant_guard",
    kind: "join-spider",
    x: 10,
    y: 5,
    hp: 26,
    maxHp: 26,
    armor: 0,
    damage: 2,
    attackName: "笛卡尔根网",
    status: "linked",
    weakness: "relation",
    masterId: 14,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 2,
    id: 13,
    lessonId: "left-join",
    roomId: 24,
    name: "毒蛙",
    species: "poison_frog_guard",
    kind: "left-join-wraith",
    x: 10,
    y: 5,
    hp: 15,
    maxHp: 15,
    armor: 0,
    damage: 2,
    attackName: "右表毒沼",
    status: "unmatched",
    weakness: "left",
    masterId: null,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 2,
    id: 14,
    lessonId: "join-boss",
    roomId: 25,
    name: "灯塔守卫",
    species: "jungle_king",
    kind: "relation-titan",
    x: 10,
    y: 5,
    hp: 30,
    maxHp: 30,
    armor: 0,
    damage: 3,
    attackName: "灯塔强光",
    status: "conducting",
    weakness: "composite-query",
    masterId: null,
    isBoss: true,
    rank: "boss",
    encounterType: "curriculum",
  },
  ...FLOOR_TWO_BIOME_MONSTERS,
] as const;

export const FLOOR_TWO_PRACTICE_STAGES: Readonly<Record<number, LessonStageDefinition>> =
  Object.fromEntries(
    Object.entries(BIOME_PRACTICE_STAGES)
      .filter(([id]) => FLOOR_TWO_BIOME_MONSTERS.some((monster) => monster.id === Number(id)))
      .map(([id, stages]) => [id, stages[0]]),
  );

const FLOOR_TWO_SCHEMA = [...COMPLETE_SCHEMA_LINES];

export const FLOOR_TWO_LESSONS: readonly LessonDefinition[] = [
  {
    id: "order-by",
    concept: "ORDER BY / LIMIT",
    title: "潮汐码头 · 排序点亮浮标",
    intro: "ID #010 把七盏导航灯的强弱信号打乱。先排序，再只取真正需要的前几行。",
    schema: FLOOR_TWO_SCHEMA,
    primaryMonsterId: 10,
    stages: [
      {
        id: "order-peak",
        objective: "第一击：从 monster_signals 查询 monster_id = 10 的最高 charge 对应 channel。",
        queryTemplate: "",
        answerSql: "SELECT channel FROM monster_signals WHERE monster_id = 10 ORDER BY charge DESC LIMIT 1;",
        hints: [
          "数据表是 monster_signals。",
          "按 charge 降序排列。",
          "LIMIT 1 只保留最高值。",
          "完整写法：SELECT channel FROM monster_signals WHERE monster_id = 10 ORDER BY charge DESC LIMIT 1;",
        ],
        locks: ["ORDER BY", "LIMIT"],
        requiredFeatures: ["order-by", "limit"],
        attackTargetIds: [10],
      },
      {
        id: "order-top-two",
        objective: "第二击：按 charge 从高到低返回前两个 channel 与 charge。",
        queryTemplate: "",
        answerSql: "SELECT channel, charge FROM monster_signals WHERE monster_id = 10 ORDER BY charge DESC LIMIT 2;",
        hints: [
          "SELECT channel, charge。",
          "仍然使用 ORDER BY charge DESC。",
          "把 LIMIT 改为 2。",
          "完整写法：SELECT channel, charge FROM monster_signals WHERE monster_id = 10 ORDER BY charge DESC LIMIT 2;",
        ],
        locks: ["ORDER BY", "LIMIT"],
        requiredFeatures: ["order-by", "limit"],
        attackTargetIds: [10],
      },
    ],
  },
  {
    id: "distinct",
    concept: "DISTINCT",
    title: "七岔潮渠 · 去除重复航线",
    intro: "ID #011 把相同水纹复制成多条航线。DISTINCT 只保留真正不同的方向。",
    schema: FLOOR_TWO_SCHEMA,
    primaryMonsterId: 11,
    stages: [{
      id: "distinct-status",
      objective: "从 monster_signals 查询 monster_id = 11 的不同 channel，并按 channel 升序排列。",
      queryTemplate: "",
      answerSql: "SELECT DISTINCT channel FROM monster_signals WHERE monster_id = 11 ORDER BY channel;",
      hints: [
        "数据表是 monster_signals。",
        "SELECT 后加入 DISTINCT channel。",
        "WHERE 锁定 monster_id = 11。",
        "完整写法：SELECT DISTINCT channel FROM monster_signals WHERE monster_id = 11 ORDER BY channel;",
      ],
      locks: ["DISTINCT", "ORDER BY"],
      requiredFeatures: ["distinct", "order-by"],
      attackTargetIds: [11],
    }],
  },
  {
    id: "inner-join",
    concept: "INNER JOIN / ON",
    title: "双端根桥 · 连接怪物与房间",
    intro: "ID #012 的档案分散在 monsters 与 rooms。给两张表使用别名，再用 monsters.room_id = rooms.id 建立连接。",
    schema: FLOOR_TWO_SCHEMA,
    primaryMonsterId: 12,
    stages: [
      {
        id: "inner-join-sector",
        objective: "第一击：给 monsters 使用别名 m、rooms 使用别名 r，查询 m.id = 12 的 m.id 与 r.sector。",
        queryTemplate: "",
        answerSql: "SELECT m.id, r.sector FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE m.id = 12;",
        hints: [
          "给 monsters 使用别名 m，给 rooms 使用别名 r。",
          "ON m.room_id = r.id。",
          "这次只读取 m.id 与 r.sector，不要提前查询怪物名字。",
          "完整写法：SELECT m.id, r.sector FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE m.id = 12;",
        ],
        locks: ["INNER JOIN", "ON"],
        requiredFeatures: ["join", "on"],
        attackTargetIds: [12],
      },
      {
        id: "inner-join-room",
        objective: "第二击：继续使用别名 m 与 r，查询 m.id = 12 的 m.id，并把 r.name 命名为 room_name。",
        queryTemplate: "",
        answerSql: "SELECT m.id, r.name AS room_name FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE m.id = 12;",
        hints: [
          "仍连接 monsters AS m 与 rooms AS r。",
          "连接条件保持为 ON m.room_id = r.id。",
          "读取 m.id，并用 AS room_name 说明 name 来自房间表。",
          "完整写法：SELECT m.id, r.name AS room_name FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE m.id = 12;",
        ],
        locks: ["INNER JOIN", "ON"],
        requiredFeatures: ["join", "on"],
        attackTargetIds: [12],
      },
    ],
  },
  {
    id: "left-join",
    concept: "LEFT JOIN / IS NULL",
    title: "沉水村落 · 找出无装备记录",
    intro: "ID #013 守着一扇没有装备记录的门。保留左表全部怪物，再用右表 NULL 找出没有匹配项的实体。",
    schema: FLOOR_TWO_SCHEMA,
    primaryMonsterId: 13,
    stages: [{
      id: "left-join-unarmed",
      objective: "给 monsters 使用别名 m、monster_gear 使用别名 g；LEFT JOIN 后返回 m.room_id = 24 且 g.monster_id 为空的 m.id。",
      queryTemplate: "",
      answerSql: "SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id = 24 AND g.monster_id IS NULL;",
      hints: [
        "从 monsters m LEFT JOIN monster_gear g。",
        "ON m.id = g.monster_id。",
        "WHERE 同时限制 room_id = 24 与 g.monster_id IS NULL。",
        "完整写法：SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id = 24 AND g.monster_id IS NULL;",
      ],
      locks: ["LEFT JOIN", "IS NULL"],
      requiredFeatures: ["left-join", "is-null"],
      attackTargetIds: [13],
    }],
  },
  {
    id: "join-boss",
    concept: "JOIN 综合查询",
    title: "灯塔核心 · 多表综合查询",
    intro: "ID #014 同时控制房间、怪物和装备。把 JOIN、分组过滤与排序组合成一条可核对的查询。",
    schema: FLOOR_TWO_SCHEMA,
    primaryMonsterId: 14,
    stages: [
      {
        id: "join-boss-groups",
        objective: "护盾阶段：连接 monsters AS m 与 rooms AS r，按 r.sector 统计第二层怪物数为 total；保留至少 3 只的组，并按 total 降序、r.sector 升序。",
        queryTemplate: "",
        answerSql: "SELECT r.sector, COUNT(*) AS total FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE r.floor = 2 GROUP BY r.sector HAVING COUNT(*) >= 3 ORDER BY total DESC, r.sector ASC;",
        hints: [
          "连接 monsters m 与 rooms r。",
          "连接条件是 ON m.room_id = r.id。",
          "WHERE r.floor = 2，GROUP BY r.sector。",
          "HAVING COUNT(*) >= 3，最后 ORDER BY total DESC, r.sector ASC。",
          "完整写法：SELECT r.sector, COUNT(*) AS total FROM monsters AS m INNER JOIN rooms AS r ON m.room_id = r.id WHERE r.floor = 2 GROUP BY r.sector HAVING COUNT(*) >= 3 ORDER BY total DESC, r.sector ASC;",
        ],
        locks: ["INNER JOIN", "GROUP BY", "HAVING", "ORDER BY"],
        requiredFeatures: ["join", "group-by", "having", "order-by"],
        attackTargetIds: [14],
      },
      {
        id: "join-boss-core",
        objective: "核心阶段：连接 monsters AS m 与 monster_gear AS g，返回 m.id = 14 的 m.id 与最高 g.power。",
        queryTemplate: "",
        answerSql: "SELECT m.id, g.power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 14 ORDER BY g.power DESC LIMIT 1;",
        hints: [
          "连接 monsters m 与 monster_gear g。",
          "连接条件是 ON m.id = g.monster_id。",
          "WHERE m.id = 14。",
          "按 g.power 降序并 LIMIT 1。",
          "完整写法：SELECT m.id, g.power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 14 ORDER BY g.power DESC LIMIT 1;",
        ],
        locks: ["INNER JOIN", "ORDER BY", "LIMIT"],
        requiredFeatures: ["join", "order-by", "limit"],
        attackTargetIds: [14],
      },
    ],
  },
] as const;

export const FLOOR_TWO_LOOT_AFTER_LESSON: Partial<
  Record<LessonId, { weapon: Weapon; position: Position }>
> = {
  "order-by": { weapon: SORT_SABER, position: { x: 10, y: 5 } },
  "inner-join": { weapon: JOIN_CHAIN, position: { x: 10, y: 5 } },
};
