import type {
  LessonDefinition,
  Monster,
  Weapon,
} from "../domain/types";
import { COMPLETE_SCHEMA_LINES } from "./sqlSchema";

export const RUNE_STAFF: Weapon = {
  id: "rune-staff",
  name: "符文杖",
  damage: 18,
  heatReduction: 0,
  description: "元素熔炉的必修武器。正确查询造成 18 点伤害，不会跳过题目阶段。",
};

export const FLOOR_FOUR_MONSTERS: readonly Monster[] = [
  {
    floor: 4,
    id: 12,
    lessonId: "f4-scalar",
    roomId: 51,
    name: "火灵",
    species: "fire_spirit",
    kind: "fire-spirit",
    x: 1,
    y: 1,
    hp: 16,
    maxHp: 16,
    armor: 0,
    damage: 2,
    attackName: "火星喷射",
    status: "burning",
    weakness: "scalar",
    masterId: 15,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 4,
    id: 13,
    lessonId: "f4-in",
    roomId: 52,
    name: "冰灵",
    species: "ice_spirit",
    kind: "ice-spirit",
    x: 1,
    y: 1,
    hp: 18,
    maxHp: 18,
    armor: 0,
    damage: 2,
    attackName: "冰晶飞散",
    status: "frozen",
    weakness: "in",
    masterId: 17,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 4,
    id: 14,
    lessonId: "f4-exists",
    roomId: 53,
    name: "雷灵",
    species: "thunder_spirit",
    kind: "thunder-spirit",
    x: 1,
    y: 1,
    hp: 18,
    maxHp: 18,
    armor: 0,
    damage: 2,
    attackName: "雷弧反击",
    status: "charged",
    weakness: "exists",
    masterId: 17,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 4,
    id: 15,
    lessonId: "f4-correlated",
    roomId: 54,
    name: "石巨人",
    species: "forge_golem",
    kind: "aggregate-golem",
    x: 1,
    y: 1,
    hp: 17,
    maxHp: 17,
    armor: 1,
    damage: 2,
    attackName: "炉石重压",
    status: "forged",
    weakness: "correlated",
    masterId: 17,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 4,
    id: 16,
    lessonId: "f4-cte",
    roomId: 55,
    name: "炎王",
    species: "flame_lord",
    kind: "fire-spirit",
    x: 1,
    y: 1,
    hp: 17,
    maxHp: 17,
    armor: 1,
    damage: 2,
    attackName: "炎环爆发",
    status: "crowned",
    weakness: "cte",
    masterId: 17,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 4,
    id: 17,
    lessonId: "f4-recursive",
    roomId: 56,
    name: "元素王",
    species: "elemental_king",
    kind: "elemental-king",
    x: 1,
    y: 1,
    hp: 32,
    maxHp: 32,
    armor: 2,
    damage: 3,
    attackName: "元素坍缩",
    status: "ruling",
    weakness: "recursive",
    masterId: null,
    isBoss: true,
    rank: "boss",
    encounterType: "curriculum",
  },
] as const;

const SCHEMA = [...COMPLETE_SCHEMA_LINES];

export const FLOOR_FOUR_LESSON_DEFINITIONS: readonly LessonDefinition[] = [
  {
    id: "f4-scalar",
    concept: "标量子查询",
    title: "火室 · 用结果定位记录",
    intro: "先在内层得到一个 id，再由外层读取火灵名字。",
    schema: SCHEMA,
    primaryMonsterId: 12,
    stages: [{
      id: "f4-scalar-first",
      objective: "用标量子查询找出 room_id = 51 中 id 最小怪物的 name。",
      queryTemplate: "",
      answerSql: "SELECT name FROM monsters WHERE id = (SELECT MIN(id) FROM monsters WHERE room_id = 51);",
      hints: [
        "外层只读取 name。",
        "内层先查询 room_id = 51 的最小 id。",
        "把内层结果放到外层 id = (...)。",
        "完整写法：SELECT name FROM monsters WHERE id = (SELECT MIN(id) FROM monsters WHERE room_id = 51);",
      ],
      locks: ["SUBQUERY"],
      requiredFeatures: ["subquery"],
      attackTargetIds: [12],
    }],
  },
  {
    id: "f4-in",
    concept: "IN 子查询",
    title: "冰库 · 集合筛选",
    intro: "先让子查询返回寒霜房间集合，再筛选其中的怪物。",
    schema: SCHEMA,
    primaryMonsterId: 13,
    stages: [{
      id: "f4-in-frost",
      objective: "查询位于第四层 frost 区域房间中的怪物 name，并按 name 排序。",
      queryTemplate: "",
      answerSql: "SELECT name FROM monsters WHERE room_id IN (SELECT id FROM rooms WHERE floor = 4 AND sector = 'frost') ORDER BY name;",
      hints: [
        "外层从 monsters 读取 name。",
        "内层从 rooms 读取 id。",
        "内层条件是 floor = 4 与 sector = 'frost'。",
        "外层用 room_id IN (...)，最后排序。",
        "完整写法：SELECT name FROM monsters WHERE room_id IN (SELECT id FROM rooms WHERE floor = 4 AND sector = 'frost') ORDER BY name;",
      ],
      locks: ["IN", "SUBQUERY", "ORDER BY"],
      requiredFeatures: ["in", "subquery", "order-by"],
      attackTargetIds: [13],
    }],
  },
  {
    id: "f4-exists",
    concept: "EXISTS",
    title: "雷池 · 判断记录存在",
    intro: "不要取出装备内容；只判断雷灵是否拥有装备记录。",
    schema: SCHEMA,
    primaryMonsterId: 14,
    stages: [{
      id: "f4-exists-gear",
      objective: "用 EXISTS 查询 id = 14 且存在装备记录的怪物 name。",
      queryTemplate: "",
      answerSql: "SELECT m.name FROM monsters m WHERE m.id = 14 AND EXISTS (SELECT 1 FROM monster_gear g WHERE g.monster_id = m.id);",
      hints: [
        "外层读取 m.name。",
        "用 m.id = 14 锁定雷灵。",
        "EXISTS 内层检查 monster_gear。",
        "内外层通过 g.monster_id = m.id 相关。",
        "完整写法：SELECT m.name FROM monsters m WHERE m.id = 14 AND EXISTS (SELECT 1 FROM monster_gear g WHERE g.monster_id = m.id);",
      ],
      locks: ["EXISTS", "SUBQUERY"],
      requiredFeatures: ["exists", "subquery"],
      attackTargetIds: [14],
    }],
  },
  {
    id: "f4-correlated",
    concept: "相关子查询",
    title: "石炉 · 逐行关联",
    intro: "内层装备查询要引用当前外层怪物，才能判断石巨人的力量。",
    schema: SCHEMA,
    primaryMonsterId: 15,
    stages: [{
      id: "f4-correlated-gear",
      objective: "用相关子查询找出 id = 15 且最高装备 power 不低于 18 的怪物 name。",
      queryTemplate: "",
      answerSql: "SELECT m.name FROM monsters m WHERE m.id = 15 AND (SELECT MAX(g.power) FROM monster_gear g WHERE g.monster_id = m.id) >= 18;",
      hints: [
        "外层读取 m.name。",
        "内层从 monster_gear 计算 MAX(power)。",
        "内层条件引用外层 m.id。",
        "比较内层结果 >= 18。",
        "完整写法：SELECT m.name FROM monsters m WHERE m.id = 15 AND (SELECT MAX(g.power) FROM monster_gear g WHERE g.monster_id = m.id) >= 18;",
      ],
      locks: ["CORRELATED SUBQUERY"],
      requiredFeatures: ["subquery"],
      attackTargetIds: [15],
    }],
  },
  {
    id: "f4-cte",
    concept: "WITH / CTE",
    title: "符文环 · 命名中间结果",
    intro: "先把高 power 装备命名为 armored，再连接回怪物。",
    schema: SCHEMA,
    primaryMonsterId: 16,
    stages: [{
      id: "f4-cte-armor",
      objective: "从 monster_gear 用 CTE 保存 power >= 20 的 monster_id，再查询 monsters.id = 16 的怪物 name。",
      queryTemplate: "",
      answerSql: "WITH armored AS (SELECT monster_id FROM monster_gear WHERE power >= 20) SELECT m.name FROM monsters m INNER JOIN armored a ON m.id = a.monster_id WHERE m.id = 16;",
      hints: [
        "先写 WITH armored AS (...)。",
        "CTE 中读取 power >= 20 的 monster_id。",
        "主查询连接 monsters 与 armored。",
        "用 m.id = 16 锁定炎王。",
        "完整写法：WITH armored AS (SELECT monster_id FROM monster_gear WHERE power >= 20) SELECT m.name FROM monsters m INNER JOIN armored a ON m.id = a.monster_id WHERE m.id = 16;",
      ],
      locks: ["WITH / CTE", "JOIN"],
      requiredFeatures: ["cte", "join"],
      attackTargetIds: [16],
    }],
  },
  {
    id: "f4-recursive",
    concept: "WITH RECURSIVE",
    title: "元素王座 · 递归追踪",
    intro: "先生成连续熔炉房间，再沿 master_id 追到元素王核心。",
    schema: SCHEMA,
    primaryMonsterId: 17,
    stages: [
      {
        id: "f4-recursive-rooms",
        objective: "递归生成 51 到 53，连接 rooms 后按 id 返回 room_name。",
        queryTemplate: "",
        answerSql: "WITH RECURSIVE room_ids(id) AS (SELECT 51 UNION ALL SELECT id + 1 FROM room_ids WHERE id < 53) SELECT r.name AS room_name FROM rooms r INNER JOIN room_ids x ON r.id = x.id ORDER BY r.id;",
        hints: [
          "使用 WITH RECURSIVE room_ids(id)。",
          "锚点是 SELECT 51。",
          "递归项每次 id + 1，直到 id < 53。",
          "连接 rooms 并按 r.id 排序。",
          "完整写法：WITH RECURSIVE room_ids(id) AS (SELECT 51 UNION ALL SELECT id + 1 FROM room_ids WHERE id < 53) SELECT r.name AS room_name FROM rooms r INNER JOIN room_ids x ON r.id = x.id ORDER BY r.id;",
        ],
        locks: ["WITH RECURSIVE", "UNION ALL"],
        requiredFeatures: ["cte", "recursive", "union"],
        attackTargetIds: [17],
      },
      {
        id: "f4-recursive-core",
        objective: "从火灵 #12 出发，递归沿 master_id 返回 name、depth，直到元素王。",
        queryTemplate: "",
        answerSql: "WITH RECURSIVE lineage(id, name, master_id, depth) AS (SELECT id, name, master_id, 1 FROM monsters WHERE id = 12 UNION ALL SELECT m.id, m.name, m.master_id, l.depth + 1 FROM monsters m INNER JOIN lineage l ON m.id = l.master_id WHERE l.depth < 3) SELECT name, depth FROM lineage ORDER BY depth;",
        hints: [
          "CTE 保存 id、name、master_id、depth。",
          "锚点从 id = 12、depth = 1 开始。",
          "递归项连接 m.id = l.master_id。",
          "限制 l.depth < 3，最后按 depth 排序。",
          "完整写法：WITH RECURSIVE lineage(id, name, master_id, depth) AS (SELECT id, name, master_id, 1 FROM monsters WHERE id = 12 UNION ALL SELECT m.id, m.name, m.master_id, l.depth + 1 FROM monsters m INNER JOIN lineage l ON m.id = l.master_id WHERE l.depth < 3) SELECT name, depth FROM lineage ORDER BY depth;",
        ],
        locks: ["WITH RECURSIVE", "递归 JOIN"],
        requiredFeatures: ["cte", "recursive", "join"],
        attackTargetIds: [17],
      },
    ],
  },
] as const;
