import type {
  LessonDefinition,
  Monster,
  Weapon,
} from "../domain/types";
import { COMPLETE_SCHEMA_LINES } from "./sqlSchema";

export const BONE_BLADE: Weapon = {
  id: "bone-blade",
  name: "骨剑",
  damage: 16,
  heatReduction: 0,
  description: "亡者墓城的必修武器。正确查询造成 16 点伤害，不会跳过题目阶段。",
};

export const FLOOR_THREE_MONSTERS: readonly Monster[] = [
  {
    floor: 3,
    id: 1,
    lessonId: "f3-inner",
    roomId: 41,
    name: "骷髅",
    species: "grave_skeleton",
    kind: "skeleton",
    x: 1,
    y: 1,
    hp: 15,
    maxHp: 15,
    armor: 0,
    damage: 2,
    attackName: "骨刀横扫",
    status: "guarding",
    weakness: "join",
    masterId: 6,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 3,
    id: 2,
    lessonId: "f3-left",
    roomId: 42,
    name: "僵尸",
    species: "grave_zombie",
    kind: "zombie",
    x: 1,
    y: 1,
    hp: 16,
    maxHp: 16,
    armor: 0,
    damage: 2,
    attackName: "墓土拍击",
    status: "unarmed",
    weakness: "left",
    masterId: 6,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 3,
    id: 3,
    lessonId: "f3-self",
    roomId: 43,
    name: "幽灵",
    species: "crypt_ghost",
    kind: "ghost",
    x: 1,
    y: 1,
    hp: 16,
    maxHp: 16,
    armor: 0,
    damage: 2,
    attackName: "灵火穿透",
    status: "bound",
    weakness: "alias",
    masterId: 6,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 3,
    id: 4,
    lessonId: "f3-chain",
    roomId: 44,
    name: "铠骷髅",
    species: "armored_skeleton",
    kind: "skeleton",
    x: 1,
    y: 1,
    hp: 15,
    maxHp: 15,
    armor: 1,
    damage: 2,
    attackName: "铠骨重斩",
    status: "armored",
    weakness: "chain",
    masterId: 6,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 3,
    id: 5,
    lessonId: "f3-union",
    roomId: 45,
    name: "骨骑士",
    species: "bone_knight",
    kind: "skeleton",
    x: 1,
    y: 1,
    hp: 15,
    maxHp: 15,
    armor: 1,
    damage: 2,
    attackName: "双墓冲锋",
    status: "mounted",
    weakness: "union",
    masterId: 6,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 3,
    id: 6,
    lessonId: "f3-audit",
    roomId: 46,
    name: "死灵王",
    species: "necromancer_king",
    kind: "necromancer",
    x: 1,
    y: 1,
    hp: 28,
    maxHp: 28,
    armor: 2,
    damage: 2,
    attackName: "亡者审计",
    status: "ruling",
    weakness: "audit",
    masterId: null,
    isBoss: true,
    rank: "boss",
    encounterType: "curriculum",
  },
] as const;

const SCHEMA = [...COMPLETE_SCHEMA_LINES];

export const FLOOR_THREE_LESSON_DEFINITIONS: readonly LessonDefinition[] = [
  {
    id: "f3-inner",
    concept: "INNER JOIN / ON",
    title: "骨桥前庭 · 匹配两表",
    intro: "骷髅的房间名在 rooms 表。用真实键关系把怪物与墓室接起来。",
    schema: SCHEMA,
    primaryMonsterId: 1,
    stages: [{
      id: "f3-inner-room",
      objective: "连接 monsters 与 rooms，查询 id = 1 的 name 和 room_name。",
      queryTemplate: "",
      answerSql: "SELECT m.name, r.name AS room_name FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 1;",
      hints: [
        "需要读取怪物名和房间名。",
        "连接 monsters 与 rooms。",
        "关系是 m.room_id = r.id。",
        "用 WHERE m.id = 1 锁定骷髅。",
        "完整写法：SELECT m.name, r.name AS room_name FROM monsters m INNER JOIN rooms r ON m.room_id = r.id WHERE m.id = 1;",
      ],
      locks: ["INNER JOIN", "ON"],
      requiredFeatures: ["join", "on"],
      attackTargetIds: [1],
    }],
  },
  {
    id: "f3-left",
    concept: "LEFT JOIN / IS NULL",
    title: "空甲墓道 · 保留左表",
    intro: "僵尸没有装备记录。保留怪物，再用右表空值找出它。",
    schema: SCHEMA,
    primaryMonsterId: 2,
    stages: [{
      id: "f3-left-unarmed",
      objective: "LEFT JOIN 装备表，找出 room_id = 42 且没有装备的怪物 id。",
      queryTemplate: "",
      answerSql: "SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id = 42 AND g.monster_id IS NULL;",
      hints: [
        "从 monsters m 开始。",
        "LEFT JOIN monster_gear g。",
        "ON m.id = g.monster_id。",
        "过滤 room_id = 42 与 g.monster_id IS NULL。",
        "完整写法：SELECT m.id FROM monsters m LEFT JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id = 42 AND g.monster_id IS NULL;",
      ],
      locks: ["LEFT JOIN", "ON", "IS NULL"],
      requiredFeatures: ["left-join", "on", "is-null"],
      attackTargetIds: [2],
    }],
  },
  {
    id: "f3-self",
    concept: "SELF JOIN / 别名",
    title: "回声灵堂 · 自连接",
    intro: "幽灵与主人都在 monsters 表。为同一张表取两个身份。",
    schema: SCHEMA,
    primaryMonsterId: 3,
    stages: [{
      id: "f3-self-master",
      objective: "自连接 monsters，查询 id = 3 的 child_name 与 master_name。",
      queryTemplate: "",
      answerSql: "SELECT child.name AS child_name, master.name AS master_name FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 3;",
      hints: [
        "同一张 monsters 表要使用两次。",
        "给它们取 child 与 master 两个别名。",
        "连接 child.master_id = master.id。",
        "用 child.id = 3 锁定幽灵。",
        "完整写法：SELECT child.name AS child_name, master.name AS master_name FROM monsters child INNER JOIN monsters master ON child.master_id = master.id WHERE child.id = 3;",
      ],
      locks: ["SELF JOIN", "ON"],
      requiredFeatures: ["self-join", "on"],
      attackTargetIds: [3],
    }],
  },
  {
    id: "f3-chain",
    concept: "三表 JOIN 链",
    title: "骑士墓 · 串联三表",
    intro: "铠骷髅、所在墓室和武器力量分散在三张表里。",
    schema: SCHEMA,
    primaryMonsterId: 4,
    stages: [{
      id: "f3-chain-gear",
      objective: "连接 rooms、monsters、monster_gear，返回 id = 4 的 room_name、name、power。",
      queryTemplate: "",
      answerSql: "SELECT r.name AS room_name, m.name, g.power FROM rooms r INNER JOIN monsters m ON r.id = m.room_id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 4;",
      hints: [
        "需要 rooms、monsters、monster_gear 三张表。",
        "先连接 r.id = m.room_id。",
        "再连接 m.id = g.monster_id。",
        "WHERE m.id = 4。",
        "完整写法：SELECT r.name AS room_name, m.name, g.power FROM rooms r INNER JOIN monsters m ON r.id = m.room_id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id = 4;",
      ],
      locks: ["JOIN × 2", "ON"],
      requiredFeatures: ["join", "on"],
      attackTargetIds: [4],
    }],
  },
  {
    id: "f3-union",
    concept: "UNION",
    title: "合葬厅 · 合并结果",
    intro: "两条墓道各有一组记录。用 UNION 合成一张去重名册。",
    schema: SCHEMA,
    primaryMonsterId: 5,
    stages: [{
      id: "f3-union-patrol",
      objective: "合并 room_id = 41 与 43 的怪物 id、name，并按 id 升序。",
      queryTemplate: "",
      answerSql: "SELECT id, name FROM monsters WHERE room_id = 41 UNION SELECT id, name FROM monsters WHERE room_id = 43 ORDER BY id;",
      hints: [
        "先分别查询两条墓道。",
        "两边都返回 id、name。",
        "用 UNION 合并并去重。",
        "最后按 id 排序。",
        "完整写法：SELECT id, name FROM monsters WHERE room_id = 41 UNION SELECT id, name FROM monsters WHERE room_id = 43 ORDER BY id;",
      ],
      locks: ["UNION", "ORDER BY"],
      requiredFeatures: ["union", "order-by"],
      attackTargetIds: [5],
    }],
  },
  {
    id: "f3-audit",
    concept: "JOIN 综合审计",
    title: "死灵王庭 · 关系审计",
    intro: "先审计墓城各区人数，再穿透装备表找到死灵王核心。",
    schema: SCHEMA,
    primaryMonsterId: 6,
    stages: [
      {
        id: "f3-audit-groups",
        objective: "按 sector 统计 room_id 41 至 46 的怪物数，只保留不少于 2 只的组并排序。",
        queryTemplate: "",
        answerSql: "SELECT r.sector, COUNT(*) AS total FROM rooms r INNER JOIN monsters m ON r.id = m.room_id WHERE r.floor = 3 AND m.room_id BETWEEN 41 AND 46 GROUP BY r.sector HAVING COUNT(*) >= 2 ORDER BY r.sector;",
        hints: [
          "先连接 rooms 与 monsters。",
          "限定第三层和 room_id 41 至 46。",
          "按 r.sector 分组并 COUNT(*) AS total。",
          "HAVING COUNT(*) >= 2，最后排序。",
          "完整写法：SELECT r.sector, COUNT(*) AS total FROM rooms r INNER JOIN monsters m ON r.id = m.room_id WHERE r.floor = 3 AND m.room_id BETWEEN 41 AND 46 GROUP BY r.sector HAVING COUNT(*) >= 2 ORDER BY r.sector;",
        ],
        locks: ["JOIN", "GROUP BY", "HAVING"],
        requiredFeatures: ["join", "group-by", "having"],
        attackTargetIds: [6],
      },
      {
        id: "f3-audit-core",
        objective: "连接装备表，找出 room_id 41 至 46 中 power 最高怪物的 name 与 power。",
        queryTemplate: "",
        answerSql: "SELECT m.name, g.power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id BETWEEN 41 AND 46 ORDER BY g.power DESC LIMIT 1;",
        hints: [
          "连接 monsters 与 monster_gear。",
          "关系是 m.id = g.monster_id。",
          "限定 room_id 41 至 46。",
          "按 g.power DESC 排序并 LIMIT 1。",
          "完整写法：SELECT m.name, g.power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.room_id BETWEEN 41 AND 46 ORDER BY g.power DESC LIMIT 1;",
        ],
        locks: ["JOIN", "ORDER BY", "LIMIT"],
        requiredFeatures: ["join", "order-by", "limit"],
        attackTargetIds: [6],
      },
    ],
  },
] as const;
