import type {
  LessonDefinition,
  Monster,
  Weapon,
} from "../domain/types";

export const DRAGON_SPEAR: Weapon = {
  id: "dragon-spear",
  name: "龙枪",
  damage: 22,
  heatReduction: 1,
  description: "巨龙熔巢的必修武器。正确沙箱操作造成 22 点伤害，并减少 1 点查询热量。",
};

export const FLOOR_SIX_MONSTERS: readonly Monster[] = [
  {
    floor: 6,
    id: 56,
    lessonId: "f6-insert",
    roomId: 71,
    name: "幼龙",
    species: "magma_hatchling",
    kind: "hatchling",
    x: 1,
    y: 1,
    hp: 20,
    maxHp: 20,
    armor: 0,
    damage: 2,
    attackName: "火星吐息",
    status: "hatching",
    weakness: "insert",
    masterId: 61,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 6,
    id: 57,
    lessonId: "f6-update",
    roomId: 72,
    name: "飞龙",
    species: "cave_wyvern",
    kind: "wyvern",
    x: 1,
    y: 1,
    hp: 22,
    maxHp: 22,
    armor: 0,
    damage: 2,
    attackName: "俯冲爪击",
    status: "flying",
    weakness: "update",
    masterId: 61,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 6,
    id: 58,
    lessonId: "f6-delete",
    roomId: 73,
    name: "雷龙",
    species: "thunder_drake",
    kind: "dragon",
    x: 1,
    y: 1,
    hp: 24,
    maxHp: 24,
    armor: 1,
    damage: 2,
    attackName: "雷翼扫击",
    status: "charged",
    weakness: "delete",
    masterId: 61,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 6,
    id: 59,
    lessonId: "f6-constraint",
    roomId: 74,
    name: "晶龙",
    species: "crystal_drake",
    kind: "dragon",
    x: 1,
    y: 1,
    hp: 25,
    maxHp: 25,
    armor: 1,
    damage: 3,
    attackName: "晶刺反射",
    status: "armored",
    weakness: "constraint",
    masterId: 61,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 6,
    id: 60,
    lessonId: "f6-transaction",
    roomId: 75,
    name: "巨龙",
    species: "ancient_dragon",
    kind: "dragon",
    x: 1,
    y: 1,
    hp: 28,
    maxHp: 28,
    armor: 1,
    damage: 3,
    attackName: "熔岩吐息",
    status: "ancient",
    weakness: "rollback",
    masterId: 61,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 6,
    id: 61,
    lessonId: "f6-savepoint",
    roomId: 76,
    name: "龙王",
    species: "dragon_king",
    kind: "dragon-king",
    x: 1,
    y: 1,
    hp: 44,
    maxHp: 44,
    armor: 2,
    damage: 4,
    attackName: "王焰坠落",
    status: "ruling",
    weakness: "savepoint",
    masterId: null,
    isBoss: true,
    rank: "boss",
    encounterType: "curriculum",
  },
] as const;

export const REPAIR_QUEUE_SCHEMA =
  "repair_queue(id, item, quantity, status)";

const SANDBOX_SCHEMA = [
  REPAIR_QUEUE_SCHEMA,
  "沙箱初始行：1 ore 2 ready；2 scale 1 damaged；3 fang 1 duplicate；4 fang 1 duplicate；5 core 1 ready",
  "约束：id PRIMARY KEY；item/status NOT NULL；quantity 必须在 0 到 9",
];

export const FLOOR_SIX_LESSON_DEFINITIONS: readonly LessonDefinition[] = [
  {
    id: "f6-insert",
    concept: "INSERT",
    title: "孵化台 · 指定列安全写入",
    intro: "每次提交都在一次性 SQLite 副本执行；结算后副本销毁，不会污染永久怪物档案。",
    schema: SANDBOX_SCHEMA,
    primaryMonsterId: 56,
    stages: [{
      id: "f6-insert-row",
      objective: "向 repair_queue 写入 id = 6、item = 'claw'、quantity = 2、status = 'ready'。",
      queryTemplate: "",
      answerSql: "INSERT INTO repair_queue(id, item, quantity, status) VALUES (6, 'claw', 2, 'ready');",
      hints: [
        "操作目标：repair_queue。",
        "使用 INSERT INTO ... VALUES ...。",
        "明确写出四个字段名，不依赖表内默认顺序。",
        "值依次是 6、'claw'、2、'ready'。",
        "完整写法：INSERT INTO repair_queue(id, item, quantity, status) VALUES (6, 'claw', 2, 'ready');",
      ],
      locks: ["INSERT"],
      requiredFeatures: ["insert"],
      attackTargetIds: [56],
    }],
  },
  {
    id: "f6-update",
    concept: "UPDATE / WHERE",
    title: "鳞甲炉 · 定向修复",
    intro: "先锁定 id，再更新状态；沙箱拒绝没有 WHERE 的全表 UPDATE。",
    schema: SANDBOX_SCHEMA,
    primaryMonsterId: 57,
    stages: [{
      id: "f6-update-target",
      objective: "把 repair_queue 中 id = 2 的 status 更新为 'fixed'。",
      queryTemplate: "",
      answerSql: "UPDATE repair_queue SET status = 'fixed' WHERE id = 2;",
      hints: [
        "操作目标：repair_queue。",
        "使用 UPDATE ... SET ...。",
        "修改字段是 status。",
        "WHERE 必须精确锁定 id = 2。",
        "完整写法：UPDATE repair_queue SET status = 'fixed' WHERE id = 2;",
      ],
      locks: ["UPDATE", "WHERE"],
      requiredFeatures: ["update", "where"],
      attackTargetIds: [57],
    }],
  },
  {
    id: "f6-delete",
    concept: "DELETE / WHERE",
    title: "清巢槽 · 删除唯一重复行",
    intro: "重复 fang 有两行；只清除 id = 4，保留 id = 3 作为验证证据。",
    schema: SANDBOX_SCHEMA,
    primaryMonsterId: 58,
    stages: [{
      id: "f6-delete-duplicate",
      objective: "删除 repair_queue 中 id = 4 且 status = 'duplicate' 的记录。",
      queryTemplate: "",
      answerSql: "DELETE FROM repair_queue WHERE id = 4 AND status = 'duplicate';",
      hints: [
        "操作目标：repair_queue。",
        "使用 DELETE FROM ... WHERE ...。",
        "第一项条件是 id = 4。",
        "再用 AND 限定 status = 'duplicate'。",
        "完整写法：DELETE FROM repair_queue WHERE id = 4 AND status = 'duplicate';",
      ],
      locks: ["DELETE", "WHERE", "AND"],
      requiredFeatures: ["delete", "where", "and"],
      attackTargetIds: [58],
    }],
  },
  {
    id: "f6-constraint",
    concept: "CHECK 约束与冲突处理",
    title: "龙晶门 · 保留约束后的有效状态",
    intro: "quantity = -1 会违反 CHECK；用 SQLite 的 OR IGNORE 让无效行不进入结果。",
    schema: SANDBOX_SCHEMA,
    primaryMonsterId: 59,
    stages: [{
      id: "f6-constraint-ignore",
      objective: "尝试写入 id = 6、item = 'bad'、quantity = -1、status = 'ready'，并用 OR IGNORE 保持表不变。",
      queryTemplate: "",
      answerSql: "INSERT OR IGNORE INTO repair_queue(id, item, quantity, status) VALUES (6, 'bad', -1, 'ready');",
      hints: [
        "仍然使用 INSERT。",
        "目标表是 repair_queue。",
        "冲突策略写在 INSERT 与 INTO 之间。",
        "使用 OR IGNORE，让违反 CHECK 的行不落表。",
        "完整写法：INSERT OR IGNORE INTO repair_queue(id, item, quantity, status) VALUES (6, 'bad', -1, 'ready');",
      ],
      locks: ["INSERT", "OR IGNORE"],
      requiredFeatures: ["insert", "constraint"],
      attackTargetIds: [59],
    }],
  },
  {
    id: "f6-transaction",
    concept: "BEGIN / ROLLBACK",
    title: "事务熔洞 · 整体撤销",
    intro: "先修改 ore 数量，再回滚；最终快照必须与进入事务前完全一致。",
    schema: SANDBOX_SCHEMA,
    primaryMonsterId: 60,
    stages: [{
      id: "f6-transaction-rollback",
      objective: "开启事务，把 id = 1 的 quantity 改成 9，然后 ROLLBACK 恢复初始状态。",
      queryTemplate: "",
      answerSql: "BEGIN; UPDATE repair_queue SET quantity = 9 WHERE id = 1; ROLLBACK;",
      hints: [
        "这是三条按顺序执行的沙箱语句。",
        "第一条是 BEGIN。",
        "中间 UPDATE 精确锁定 id = 1。",
        "最后使用 ROLLBACK，不要 COMMIT。",
        "完整写法：BEGIN; UPDATE repair_queue SET quantity = 9 WHERE id = 1; ROLLBACK;",
      ],
      locks: ["BEGIN", "UPDATE", "ROLLBACK"],
      requiredFeatures: ["transaction", "update", "rollback"],
      attackTargetIds: [60],
    }],
  },
  {
    id: "f6-savepoint",
    concept: "SAVEPOINT / ROLLBACK TO",
    title: "龙王巢 · 局部回滚后提交",
    intro: "保存点只撤销局部错误；外层已经完成的修复仍可以提交。",
    schema: SANDBOX_SCHEMA,
    primaryMonsterId: 61,
    stages: [
      {
        id: "f6-savepoint-rollback",
        objective: "BEGIN 后把 id = 2 修为 fixed；建立 clean 保存点，删除 id = 3，再 ROLLBACK TO clean 并 COMMIT。",
        queryTemplate: "",
        answerSql: "BEGIN; UPDATE repair_queue SET status = 'fixed' WHERE id = 2; SAVEPOINT clean; DELETE FROM repair_queue WHERE id = 3; ROLLBACK TO clean; COMMIT;",
        hints: [
          "外层顺序是 BEGIN → 修复 → 保存点 → 错误删除 → 局部回滚 → COMMIT。",
          "先更新 id = 2 的 status。",
          "保存点名为 clean。",
          "删除 id = 3 后使用 ROLLBACK TO clean。",
          "完整写法：BEGIN; UPDATE repair_queue SET status = 'fixed' WHERE id = 2; SAVEPOINT clean; DELETE FROM repair_queue WHERE id = 3; ROLLBACK TO clean; COMMIT;",
        ],
        locks: ["SAVEPOINT", "ROLLBACK TO", "COMMIT"],
        requiredFeatures: ["savepoint", "rollback", "commit"],
        attackTargetIds: [61],
      },
      {
        id: "f6-savepoint-commit",
        objective: "BEGIN 后建立 repair 保存点，修复 id = 2、删除 id = 4，RELEASE repair 并 COMMIT。",
        queryTemplate: "",
        answerSql: "BEGIN; SAVEPOINT repair; UPDATE repair_queue SET status = 'fixed' WHERE id = 2; DELETE FROM repair_queue WHERE id = 4; RELEASE repair; COMMIT;",
        hints: [
          "这次保存点内的两项修改都要保留。",
          "顺序是 BEGIN → SAVEPOINT repair。",
          "修复 id = 2，再删除 id = 4。",
          "用 RELEASE repair 接受保存点内修改，最后 COMMIT。",
          "完整写法：BEGIN; SAVEPOINT repair; UPDATE repair_queue SET status = 'fixed' WHERE id = 2; DELETE FROM repair_queue WHERE id = 4; RELEASE repair; COMMIT;",
        ],
        locks: ["SAVEPOINT", "UPDATE", "COMMIT"],
        requiredFeatures: ["savepoint", "update", "commit"],
        attackTargetIds: [61],
      },
    ],
  },
] as const;
