import type {
  LessonDefinition,
  Monster,
  Weapon,
} from "../domain/types";
import { COMPLETE_SCHEMA_LINES } from "./sqlSchema";

export const IRON_AXE: Weapon = {
  id: "iron-axe",
  name: "黑铁斧",
  damage: 20,
  heatReduction: 1,
  description: "黑铁要塞的必修武器。正确窗口查询造成 20 点伤害，并减少 1 点查询热量。",
};

export const FLOOR_FIVE_MONSTERS: readonly Monster[] = [
  {
    floor: 5,
    id: 23,
    lessonId: "f5-over",
    roomId: 61,
    name: "哥布林",
    species: "fort_goblin",
    kind: "goblin",
    x: 1,
    y: 1,
    hp: 18,
    maxHp: 18,
    armor: 0,
    damage: 2,
    attackName: "短矛突刺",
    status: "outer",
    weakness: "partition",
    masterId: 28,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 5,
    id: 24,
    lessonId: "f5-row-number",
    roomId: 62,
    name: "兽人",
    species: "fort_orc",
    kind: "orc",
    x: 1,
    y: 1,
    hp: 20,
    maxHp: 20,
    armor: 0,
    damage: 2,
    attackName: "战斧横扫",
    status: "outer",
    weakness: "row-number",
    masterId: 28,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 5,
    id: 25,
    lessonId: "f5-rank",
    roomId: 63,
    name: "骑士",
    species: "fort_knight",
    kind: "knight",
    x: 1,
    y: 1,
    hp: 20,
    maxHp: 20,
    armor: 1,
    damage: 2,
    attackName: "盾剑连击",
    status: "arena",
    weakness: "rank",
    masterId: 28,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 5,
    id: 26,
    lessonId: "f5-lag-lead",
    roomId: 64,
    name: "铁骑",
    species: "iron_knight",
    kind: "knight",
    x: 1,
    y: 1,
    hp: 22,
    maxHp: 22,
    armor: 1,
    damage: 2,
    attackName: "铁骑冲锋",
    status: "arena",
    weakness: "lag",
    masterId: 28,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 5,
    id: 27,
    lessonId: "f5-frame",
    roomId: 65,
    name: "巨魔",
    species: "fort_troll",
    kind: "troll",
    x: 1,
    y: 1,
    hp: 24,
    maxHp: 24,
    armor: 1,
    damage: 3,
    attackName: "城墙震击",
    status: "wall",
    weakness: "frame",
    masterId: 28,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 5,
    id: 28,
    lessonId: "f5-top-n",
    roomId: 66,
    name: "城主",
    species: "iron_castle_lord",
    kind: "castle-lord",
    x: 1,
    y: 1,
    hp: 40,
    maxHp: 40,
    armor: 2,
    damage: 3,
    attackName: "军阵压制",
    status: "core",
    weakness: "top-n",
    masterId: null,
    isBoss: true,
    rank: "boss",
    encounterType: "curriculum",
  },
] as const;

const SCHEMA = [...COMPLETE_SCHEMA_LINES];

export const FLOOR_FIVE_LESSON_DEFINITIONS: readonly LessonDefinition[] = [
  {
    id: "f5-over",
    concept: "OVER / PARTITION BY",
    title: "黑铁外城 · 保留明细分区计数",
    intro: "窗口函数不会像 GROUP BY 一样折叠卫兵行；每只怪物仍保留自己的名字。",
    schema: SCHEMA,
    primaryMonsterId: 23,
    stages: [{
      id: "f5-over-count",
      objective: "查询 id 23 到 25 的 name，并按 master_id 分区计算 guard_total，最后按 id 排序。",
      queryTemplate: "",
      answerSql: "SELECT name, COUNT(*) OVER (PARTITION BY master_id) AS guard_total FROM monsters WHERE id BETWEEN 23 AND 25 ORDER BY id;",
      hints: [
        "返回 name 与分区计数 guard_total。",
        "窗口函数写成 COUNT(*) OVER (...)。",
        "分区字段是 master_id。",
        "范围是 id BETWEEN 23 AND 25，最后按 id 排序。",
        "完整写法：SELECT name, COUNT(*) OVER (PARTITION BY master_id) AS guard_total FROM monsters WHERE id BETWEEN 23 AND 25 ORDER BY id;",
      ],
      locks: ["OVER", "PARTITION BY"],
      requiredFeatures: ["over", "partition-by"],
      attackTargetIds: [23],
    }],
  },
  {
    id: "f5-row-number",
    concept: "ROW_NUMBER",
    title: "要塞哨塔 · 分区编号",
    intro: "先按区域分队，再按不会随战斗变化的装备 power 与 id 给每名守军稳定编号。",
    schema: SCHEMA,
    primaryMonsterId: 24,
    stages: [{
      id: "f5-row-number-order",
      objective: "连接 rooms 与 monster_gear，为 id 23 到 26 的怪物按 sector 分区、power 降序和 id 升序生成 pos。",
      queryTemplate: "",
      answerSql: "SELECT m.name, r.sector, ROW_NUMBER() OVER (PARTITION BY r.sector ORDER BY g.power DESC, m.id) AS pos FROM monsters m INNER JOIN rooms r ON m.room_id = r.id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 23 AND 26 ORDER BY r.sector, pos;",
      hints: [
        "返回 name、sector 与 pos。",
        "连接 rooms 取得 sector，再连接 monster_gear 取得 power。",
        "ROW_NUMBER() 的窗口按 sector 分区。",
        "窗口内按 power DESC、id ASC，结果按 sector、pos。",
        "完整写法：SELECT m.name, r.sector, ROW_NUMBER() OVER (PARTITION BY r.sector ORDER BY g.power DESC, m.id) AS pos FROM monsters m INNER JOIN rooms r ON m.room_id = r.id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 23 AND 26 ORDER BY r.sector, pos;",
      ],
      locks: ["ROW_NUMBER", "PARTITION BY", "ORDER BY"],
      requiredFeatures: ["row-number", "partition-by", "order-by"],
      attackTargetIds: [24],
    }],
  },
  {
    id: "f5-rank",
    concept: "RANK / DENSE_RANK",
    title: "黑铁竞技场 · 处理并列",
    intro: "兽人与骑士的装备 power 相同；同时观察 RANK 的空档和 DENSE_RANK 的连续编号。",
    schema: SCHEMA,
    primaryMonsterId: 25,
    stages: [{
      id: "f5-rank-ties",
      objective: "连接装备表，查询 id 24 到 26 的 name、power、rank_no 与 dense_no，按 power 降序、id 升序排列。",
      queryTemplate: "",
      answerSql: "SELECT m.name, g.power, RANK() OVER (ORDER BY g.power DESC) AS rank_no, DENSE_RANK() OVER (ORDER BY g.power DESC) AS dense_no FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 24 AND 26 ORDER BY g.power DESC, m.id;",
      hints: [
        "返回 name、power 和两种排名。",
        "连接 monster_gear，使用不会随战斗变化的 power。",
        "rank_no 使用 RANK() OVER (...)。",
        "dense_no 使用 DENSE_RANK() OVER (...)。",
        "两个窗口都按 power DESC；最终再用 id 稳定并列顺序。",
        "完整写法：SELECT m.name, g.power, RANK() OVER (ORDER BY g.power DESC) AS rank_no, DENSE_RANK() OVER (ORDER BY g.power DESC) AS dense_no FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 24 AND 26 ORDER BY g.power DESC, m.id;",
      ],
      locks: ["RANK", "DENSE_RANK"],
      requiredFeatures: ["rank", "dense-rank"],
      attackTargetIds: [25],
    }],
  },
  {
    id: "f5-lag-lead",
    concept: "LAG / LEAD",
    title: "巡逻城墙 · 读取前后行",
    intro: "不用自连接，直接把上一名和下一名守军的装备 power 放到当前行。",
    schema: SCHEMA,
    primaryMonsterId: 26,
    stages: [{
      id: "f5-lag-lead-delta",
      objective: "连接装备表，查询 id 23 到 27 的 name、power、prev_power、next_power，窗口与结果都按 id 排序。",
      queryTemplate: "",
      answerSql: "SELECT m.name, g.power, LAG(g.power) OVER (ORDER BY m.id) AS prev_power, LEAD(g.power) OVER (ORDER BY m.id) AS next_power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 23 AND 27 ORDER BY m.id;",
      hints: [
        "返回 name、power、prev_power、next_power。",
        "prev_power 使用 LAG(g.power)。",
        "next_power 使用 LEAD(g.power)。",
        "两个窗口与最终结果都按 id 排序。",
        "完整写法：SELECT m.name, g.power, LAG(g.power) OVER (ORDER BY m.id) AS prev_power, LEAD(g.power) OVER (ORDER BY m.id) AS next_power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 23 AND 27 ORDER BY m.id;",
      ],
      locks: ["LAG", "LEAD", "ORDER BY"],
      requiredFeatures: ["lag", "lead", "order-by"],
      attackTargetIds: [26],
    }],
  },
  {
    id: "f5-frame",
    concept: "窗口 Frame",
    title: "累计城墙 · 明确窗口范围",
    intro: "累计装备 power 必须说明从第一行到当前行，避免默认 Frame 带来歧义。",
    schema: SCHEMA,
    primaryMonsterId: 27,
    stages: [{
      id: "f5-frame-running",
      objective: "连接装备表，查询 id 23 到 27 的 name 与 running_power，按 id 累计 power。",
      queryTemplate: "",
      answerSql: "SELECT m.name, SUM(g.power) OVER (ORDER BY m.id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 23 AND 27 ORDER BY m.id;",
      hints: [
        "返回 name 与 running_power。",
        "累计表达式使用 SUM(g.power) OVER (...)。",
        "窗口按 id 排序。",
        "Frame 是 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW。",
        "完整写法：SELECT m.name, SUM(g.power) OVER (ORDER BY m.id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 23 AND 27 ORDER BY m.id;",
      ],
      locks: ["OVER", "ROWS FRAME"],
      requiredFeatures: ["over", "window-frame"],
      attackTargetIds: [27],
    }],
  },
  {
    id: "f5-top-n",
    concept: "CTE + 分组 Top-N",
    title: "城主厅 · 每区取最强守军",
    intro: "窗口结果不能直接写在同层 WHERE；先在 CTE 计算排名，再由外层筛选。",
    schema: SCHEMA,
    primaryMonsterId: 28,
    stages: [
      {
        id: "f5-top-n-groups",
        objective: "用 CTE 为 id 23 到 28 的怪物按 sector 排名，返回每个 sector 的第 1 名。",
        queryTemplate: "",
        answerSql: "WITH ranked AS (SELECT r.sector, m.name, g.power, ROW_NUMBER() OVER (PARTITION BY r.sector ORDER BY g.power DESC, m.id) AS rn FROM monsters m INNER JOIN rooms r ON m.room_id = r.id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 23 AND 28) SELECT sector, name, power FROM ranked WHERE rn = 1 ORDER BY sector;",
        hints: [
          "外层返回 sector、name、power。",
          "CTE 名为 ranked，并连接 monsters、rooms 与 monster_gear。",
          "用 ROW_NUMBER 按 sector 分区、power DESC 与 id 排序。",
          "外层条件是 rn = 1，最后按 sector 排序。",
          "完整写法：WITH ranked AS (SELECT r.sector, m.name, g.power, ROW_NUMBER() OVER (PARTITION BY r.sector ORDER BY g.power DESC, m.id) AS rn FROM monsters m INNER JOIN rooms r ON m.room_id = r.id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 23 AND 28) SELECT sector, name, power FROM ranked WHERE rn = 1 ORDER BY sector;",
        ],
        locks: ["WITH", "ROW_NUMBER", "PARTITION BY"],
        requiredFeatures: ["cte", "row-number", "partition-by"],
        attackTargetIds: [28],
      },
      {
        id: "f5-top-n-core",
        objective: "用 CTE 返回 outer 与 arena 两区各前 2 名，列为 sector、name、rn。",
        queryTemplate: "",
        answerSql: "WITH ranked AS (SELECT r.sector, m.name, ROW_NUMBER() OVER (PARTITION BY r.sector ORDER BY g.power DESC, m.id) AS rn FROM monsters m INNER JOIN rooms r ON m.room_id = r.id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 23 AND 26) SELECT sector, name, rn FROM ranked WHERE rn <= 2 ORDER BY sector, rn;",
        hints: [
          "外层返回 sector、name、rn。",
          "CTE 只处理 id 23 到 26。",
          "按 sector 分区，power DESC、id ASC 编号。",
          "外层保留 rn <= 2，并按 sector、rn 排序。",
          "完整写法：WITH ranked AS (SELECT r.sector, m.name, ROW_NUMBER() OVER (PARTITION BY r.sector ORDER BY g.power DESC, m.id) AS rn FROM monsters m INNER JOIN rooms r ON m.room_id = r.id INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 23 AND 26) SELECT sector, name, rn FROM ranked WHERE rn <= 2 ORDER BY sector, rn;",
        ],
        locks: ["WITH", "ROW_NUMBER", "TOP 2"],
        requiredFeatures: ["cte", "row-number", "partition-by"],
        attackTargetIds: [28],
      },
    ],
  },
] as const;
