import type {
  LessonDefinition,
  Monster,
  Weapon,
} from "../domain/types";

export const CRYSTAL_BLADE: Weapon = {
  id: "crystal-blade",
  name: "水晶剑",
  damage: 24,
  heatReduction: 2,
  description: "水晶索引林的必修武器。正确查询造成 24 点伤害，并减少 2 点查询热量。",
};

export const FLOOR_SEVEN_MONSTERS: readonly Monster[] = [
  {
    floor: 7,
    id: 67,
    lessonId: "f7-btree",
    roomId: 81,
    name: "树卫",
    species: "index_guard",
    kind: "index-guard",
    x: 1,
    y: 1,
    hp: 22,
    maxHp: 22,
    armor: 0,
    damage: 3,
    attackName: "枝刃",
    status: "guarding",
    weakness: "search",
    masterId: 72,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 7,
    id: 68,
    lessonId: "f7-composite",
    roomId: 82,
    name: "根兽",
    species: "root_beast",
    kind: "root-beast",
    x: 1,
    y: 1,
    hp: 24,
    maxHp: 24,
    armor: 1,
    damage: 3,
    attackName: "根撞",
    status: "rooted",
    weakness: "left-prefix",
    masterId: 72,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 7,
    id: 69,
    lessonId: "f7-covering",
    roomId: 83,
    name: "镜灵",
    species: "crystal_spirit",
    kind: "crystal-spirit",
    x: 1,
    y: 1,
    hp: 24,
    maxHp: 24,
    armor: 1,
    damage: 3,
    attackName: "镜光",
    status: "reflecting",
    weakness: "covering",
    masterId: 72,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 7,
    id: 70,
    lessonId: "f7-invalid",
    roomId: 84,
    name: "藤巫",
    species: "vine_witch",
    kind: "vine-witch",
    x: 1,
    y: 1,
    hp: 24,
    maxHp: 24,
    armor: 1,
    damage: 3,
    attackName: "缠藤",
    status: "casting",
    weakness: "range",
    masterId: 72,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 7,
    id: 71,
    lessonId: "f7-plan",
    roomId: 85,
    name: "眼魔",
    species: "index_eye",
    kind: "index-eye",
    x: 1,
    y: 1,
    hp: 24,
    maxHp: 24,
    armor: 1,
    damage: 4,
    attackName: "计划凝视",
    status: "watching",
    weakness: "plan",
    masterId: 72,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 7,
    id: 72,
    lessonId: "f7-optimize",
    roomId: 86,
    name: "古树",
    species: "index_tree",
    kind: "index-tree",
    x: 1,
    y: 1,
    hp: 48,
    maxHp: 48,
    armor: 2,
    damage: 4,
    attackName: "树冠坠落",
    status: "ancient",
    weakness: "rewrite",
    masterId: null,
    isBoss: true,
    rank: "boss",
    encounterType: "curriculum",
  },
] as const;

export const INDEX_RECORDS_SCHEMA = [
  "index_records(id, realm, category, score, code, payload)",
  "真实 SQLite 索引：主键 id；(realm, score DESC)；(category, code)；code",
  "每次提交都会读取真实 EXPLAIN QUERY PLAN；计划只描述本游戏的 SQLite 夹具。",
];

export const FLOOR_SEVEN_LESSON_DEFINITIONS: readonly LessonDefinition[] = [
  {
    id: "f7-btree",
    concept: "B+ 树与点查",
    title: "枝径 · 主键点查",
    intro: "先用主键找到一片叶子，再观察 SQLite 的 SEARCH 计划；这里不会把 SQLite 计划冒充 MySQL 结论。",
    schema: INDEX_RECORDS_SCHEMA,
    primaryMonsterId: 67,
    stages: [{
      id: "f7-btree-search",
      objective: "查询 id = 3 的 code、score，让执行计划使用主键 SEARCH。",
      queryTemplate: "",
      answerSql: "SELECT code, score FROM index_records WHERE id = 3;",
      hints: [
        "先写 SELECT code, score。",
        "数据表是 index_records。",
        "用 WHERE 精确过滤 id = 3。",
        "执行后在真实计划中确认 SEARCH，而不是全表 SCAN。",
        "完整写法：SELECT code, score FROM index_records WHERE id = 3;",
      ],
      locks: ["SELECT", "WHERE"],
      requiredFeatures: ["select", "where"],
      attackTargetIds: [67],
    }],
  },
  {
    id: "f7-composite",
    concept: "联合索引与最左前缀",
    title: "根道 · 联合索引",
    intro: "联合索引先按 realm，再按 score 排列。保留最左列，范围与排序才能沿同一条根道前进。",
    schema: INDEX_RECORDS_SCHEMA,
    primaryMonsterId: 68,
    stages: [{
      id: "f7-composite-prefix",
      objective: "查询 crystal 区 score >= 80 的 code、score，按 score 降序。",
      queryTemplate: "",
      answerSql: "SELECT code, score FROM index_records WHERE realm = 'crystal' AND score >= 80 ORDER BY score DESC;",
      hints: [
        "返回 code、score。",
        "先过滤联合索引最左列 realm。",
        "再用 AND 添加 score >= 80。",
        "ORDER BY score DESC 与索引方向一致。",
        "完整写法：SELECT code, score FROM index_records WHERE realm = 'crystal' AND score >= 80 ORDER BY score DESC;",
      ],
      locks: ["WHERE", "AND", "ORDER BY"],
      requiredFeatures: ["where", "and", "order-by"],
      attackTargetIds: [68],
    }],
  },
  {
    id: "f7-covering",
    concept: "覆盖索引",
    title: "镜湖 · 只读索引列",
    intro: "只选择联合索引中已经存在的列，SQLite 可以显示 COVERING INDEX，省去回到数据页取 payload。",
    schema: INDEX_RECORDS_SCHEMA,
    primaryMonsterId: 69,
    stages: [{
      id: "f7-covering-read",
      objective: "查询 category = 'guard' 的 category、code，按 code 排序，并命中覆盖索引。",
      queryTemplate: "",
      answerSql: "SELECT category, code FROM index_records WHERE category = 'guard' ORDER BY code;",
      hints: [
        "只返回 category、code。",
        "过滤 category = 'guard'。",
        "按 code 排序。",
        "不要读取 payload；计划应出现 COVERING INDEX。",
        "完整写法：SELECT category, code FROM index_records WHERE category = 'guard' ORDER BY code;",
      ],
      locks: ["WHERE", "ORDER BY"],
      requiredFeatures: ["where", "order-by"],
      attackTargetIds: [69],
    }],
  },
  {
    id: "f7-invalid",
    concept: "索引失效与范围改写",
    title: "藤门 · 改写函数过滤",
    intro: "对索引列包函数常会让引擎无法直接按键定位。本题把前三位匹配改成等价的闭开区间。",
    schema: INDEX_RECORDS_SCHEMA,
    primaryMonsterId: 70,
    stages: [{
      id: "f7-invalid-rewrite",
      objective: "不用 substr：查询 code 从 CRY-105（含）到 CRY-108（不含）的 code，按 code 排序。",
      queryTemplate: "",
      answerSql: "SELECT code FROM index_records WHERE code >= 'CRY-105' AND code < 'CRY-108' ORDER BY code;",
      hints: [
        "返回 code。",
        "不要在 code 外包 substr。",
        "下界是 code >= 'CRY-105'。",
        "上界是 code < 'CRY-108'，再按 code 排序。",
        "完整写法：SELECT code FROM index_records WHERE code >= 'CRY-105' AND code < 'CRY-108' ORDER BY code;",
      ],
      locks: ["WHERE", "AND", "ORDER BY"],
      requiredFeatures: ["where", "and", "order-by"],
      attackTargetIds: [70],
    }],
  },
  {
    id: "f7-plan",
    concept: "EXPLAIN QUERY PLAN",
    title: "晶眼 · 读懂执行计划",
    intro: "游戏自动运行 EXPLAIN QUERY PLAN。你负责写业务查询，并用结果、SEARCH 与临时排序证据判断路径。",
    schema: INDEX_RECORDS_SCHEMA,
    primaryMonsterId: 71,
    stages: [{
      id: "f7-plan-audit",
      objective: "查询 ember 区最高 score，别名 peak；结果只保留一行，并使用 realm 联合索引。",
      queryTemplate: "",
      answerSql: "SELECT realm, MAX(score) AS peak FROM index_records WHERE realm = 'ember' GROUP BY realm;",
      hints: [
        "返回 realm 与 MAX(score) AS peak。",
        "先过滤 realm = 'ember'。",
        "按 realm 分组。",
        "计划应沿 realm、score 联合索引 SEARCH。",
        "完整写法：SELECT realm, MAX(score) AS peak FROM index_records WHERE realm = 'ember' GROUP BY realm;",
      ],
      locks: ["WHERE", "GROUP BY"],
      requiredFeatures: ["where", "group-by"],
      attackTargetIds: [71],
    }],
  },
  {
    id: "f7-optimize",
    concept: "查询优化",
    title: "古树心 · 结果与代价同时正确",
    intro: "最终优化不是追求一个神秘分数，而是在结果正确的前提下复用索引顺序，并避免临时 B-Tree。",
    schema: INDEX_RECORDS_SCHEMA,
    primaryMonsterId: 72,
    stages: [
      {
        id: "f7-optimize-top",
        objective: "第一击：查询 crystal 区 score >= 80 的前两名 code、score，按 score 降序。",
        queryTemplate: "",
        answerSql: "SELECT code, score FROM index_records WHERE realm = 'crystal' AND score >= 80 ORDER BY score DESC LIMIT 2;",
        hints: [
          "返回 code、score。",
          "过滤 realm 与 score。",
          "按 score DESC。",
          "只取前两行，计划不应出现临时排序。",
          "完整写法：SELECT code, score FROM index_records WHERE realm = 'crystal' AND score >= 80 ORDER BY score DESC LIMIT 2;",
        ],
        locks: ["WHERE", "AND", "ORDER BY", "LIMIT"],
        requiredFeatures: ["where", "and", "order-by", "limit"],
        attackTargetIds: [72],
      },
      {
        id: "f7-optimize-core",
        objective: "第二击：只用覆盖索引查询 boss 类别的 code，并按 code 排序。",
        queryTemplate: "",
        answerSql: "SELECT code FROM index_records WHERE category = 'boss' ORDER BY code;",
        hints: [
          "只返回 code。",
          "过滤 category = 'boss'。",
          "按 code 排序。",
          "不要读取 payload；让计划保留 COVERING INDEX。",
          "完整写法：SELECT code FROM index_records WHERE category = 'boss' ORDER BY code;",
        ],
        locks: ["WHERE", "ORDER BY"],
        requiredFeatures: ["where", "order-by"],
        attackTargetIds: [72],
      },
    ],
  },
];
