import type {
  LessonDefinition,
  LessonId,
  LessonStageDefinition,
  Monster,
  Position,
  Weapon,
} from "../domain/types";
import {
  FLOOR_TWO_LESSONS,
  FLOOR_TWO_LOOT_AFTER_LESSON,
  FLOOR_TWO_MONSTERS,
  FLOOR_TWO_PRACTICE_STAGES,
} from "./floor2Level";
import { sqlSchemaLine } from "./sqlSchema";

export const TILE_SIZE = 32;
export const MAP_ROWS = [
  "####################",
  "#..................#",
  "#..................#",
  "#..................#",
  "#..................#",
  "#..................#",
  "#..................#",
  "#..................#",
  "#..................#",
  "#..................#",
  "#..................#",
  "#..................#",
  "####################",
] as const;

export const PLAYER_START = { x: 10, y: 10 } as const;

export const DATA_BLADE: Weapon = {
  id: "data-blade",
  name: "数据之刃",
  damage: 6,
  heatReduction: 0,
  description: "基础查询武器。每次正确读取造成 6 点伤害。",
};

export const FILTER_BOW: Weapon = {
  id: "filter-bow",
  name: "过滤弓",
  damage: 7,
  heatReduction: 1,
  description: "WHERE 条件命中时造成 7 点伤害，并减少 1 点查询热量。",
};

export const NULL_LANTERN: Weapon = {
  id: "null-lantern",
  name: "空值提灯",
  damage: 8,
  heatReduction: 1,
  description: "照出未知值的轮廓。正确处理 NULL 时稳定破甲。",
};

export const AGGREGATE_HAMMER: Weapon = {
  id: "aggregate-hammer",
  name: "聚合战锤",
  damage: 12,
  heatReduction: 2,
  description: "为 GROUP BY 与 HAVING 打造，对聚合守卫造成 12 点伤害。",
};

export const INITIAL_MONSTERS: readonly Monster[] = [
  {
    floor: 1,
    id: 101,
    lessonId: "select",
    roomId: 1,
    name: "史莱姆",
    species: "projection_slime",
    kind: "projection-slime",
    x: 10,
    y: 5,
    hp: 12,
    maxHp: 12,
    armor: 0,
    damage: 1,
    attackName: "字段喷溅",
    status: "idle",
    weakness: "slash",
    masterId: 7,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 1,
    id: 201,
    lessonId: "where",
    roomId: 2,
    name: "猎犬",
    species: "filter_hound",
    kind: "filter-hound",
    x: 10,
    y: 5,
    hp: 14,
    maxHp: 14,
    armor: 0,
    damage: 1,
    attackName: "多余行扑咬",
    status: "escaped",
    weakness: "focus",
    masterId: 11,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 1,
    id: 301,
    lessonId: "is-null",
    roomId: 3,
    name: "幽灵",
    species: "null_ghost",
    kind: "null-ghost",
    x: 10,
    y: 5,
    hp: 14,
    maxHp: 14,
    armor: 0,
    damage: 1,
    attackName: "空值吞噬",
    status: "cursed",
    weakness: "light",
    masterId: null,
    isBoss: false,
    rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 1,
    id: 800,
    lessonId: "group-by",
    roomId: 4,
    name: "石巨人",
    species: "aggregate_warden",
    kind: "aggregate-golem",
    x: 10,
    y: 5,
    hp: 12,
    maxHp: 12,
    armor: 0,
    damage: 1,
    attackName: "分组震荡",
    status: "anchored",
    weakness: "aggregate",
    masterId: 42,
    isBoss: false,
    rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 1,
    id: 900,
    lessonId: "having",
    roomId: 5,
    name: "魔王",
    species: "query_overseer",
    kind: "aggregate-golem",
    x: 10,
    y: 5,
    hp: 24,
    maxHp: 24,
    armor: 0,
    damage: 1,
    attackName: "结果集坍缩",
    status: "sovereign",
    weakness: "having",
    masterId: 0,
    isBoss: true,
    rank: "boss",
    encounterType: "curriculum",
  },
  {
    floor: 1,
    id: 111,
    lessonId: "select",
    roomId: 11,
    name: "幻影",
    species: "projection_echo",
    kind: "projection-slime",
    x: 1,
    y: 1,
    hp: 6,
    maxHp: 6,
    armor: 0,
    damage: 1,
    attackName: "字段回声",
    status: "drifting",
    weakness: "spark",
    masterId: 7,
    isBoss: false,
    rank: "normal",
    encounterType: "ambush",
  },
  {
    floor: 1,
    id: 211,
    lessonId: "where",
    roomId: 12,
    name: "暗影犬",
    species: "filter_stalker",
    kind: "filter-hound",
    x: 1,
    y: 1,
    hp: 6,
    maxHp: 6,
    armor: 0,
    damage: 1,
    attackName: "条件突袭",
    status: "lurking",
    weakness: "focus",
    masterId: 11,
    isBoss: false,
    rank: "normal",
    encounterType: "ambush",
  },
  {
    floor: 1,
    id: 311,
    lessonId: "is-null",
    roomId: 13,
    name: "鬼火",
    species: "null_wisp",
    kind: "null-ghost",
    x: 1,
    y: 1,
    hp: 6,
    maxHp: 6,
    armor: 0,
    damage: 1,
    attackName: "未知侵蚀",
    status: "faded",
    weakness: "light",
    masterId: null,
    isBoss: false,
    rank: "normal",
    encounterType: "ambush",
  },
  {
    floor: 1,
    id: 810,
    lessonId: "group-by",
    roomId: 14,
    name: "石像鬼",
    species: "aggregate_sentinel",
    kind: "aggregate-golem",
    x: 1,
    y: 1,
    hp: 10,
    maxHp: 10,
    armor: 0,
    damage: 1,
    attackName: "分组脉冲",
    status: "patrolling",
    weakness: "aggregate",
    masterId: 42,
    isBoss: false,
    rank: "elite",
    encounterType: "ambush",
  },
  ...FLOOR_TWO_MONSTERS,
] as const;

export const PRACTICE_STAGES: Readonly<Record<number, LessonStageDefinition>> = {
  111: {
    id: "practice-select",
    objective: "突发练习：查询 id = 111 的怪物名字 name。",
    queryTemplate: "",
    hints: [
      "SELECT 后写 name，FROM 后写 monsters。",
      "使用 WHERE id = 111 锁定余像。",
      "完整写法：SELECT name FROM monsters WHERE id = 111;",
    ],
    locks: ["SELECT", "FROM"],
    requiredFeatures: ["select", "from"],
    attackTargetIds: [111],
  },
  211: {
    id: "practice-where",
    objective: "突发练习：返回 room_id = 12 且 status = 'lurking' 的怪物 id。",
    queryTemplate: "",
    hints: [
      "用 WHERE 同时检查 room_id 与 status。",
      "两个条件之间使用 AND。",
      "完整写法：SELECT id FROM monsters WHERE room_id = 12 AND status = 'lurking';",
    ],
    locks: ["WHERE", "AND"],
    requiredFeatures: ["where", "and"],
    attackTargetIds: [211],
  },
  311: {
    id: "practice-null",
    objective: "突发练习：查询 status = 'faded' 且 master_id 为空的怪物 name。",
    queryTemplate: "",
    hints: [
      "NULL 需要使用 IS NULL，不能写 = NULL。",
      "再用 AND 检查 status = 'faded'。",
      "完整写法：SELECT name FROM monsters WHERE master_id IS NULL AND status = 'faded';",
    ],
    locks: ["WHERE", "IS NULL"],
    requiredFeatures: ["where", "is-null"],
    attackTargetIds: [311],
  },
  810: {
    id: "practice-group",
    objective: "精英练习：按 channel 统计 monster_id = 810 的信号数，别名为 total。",
    queryTemplate: "",
    hints: [
      "SELECT channel 与 COUNT(*) AS total。",
      "WHERE 锁定 monster_id = 810，再按 channel 分组。",
      "完整写法：SELECT channel, COUNT(*) AS total FROM monster_signals WHERE monster_id = 810 GROUP BY channel;",
    ],
    locks: ["COUNT", "GROUP BY"],
    requiredFeatures: ["count", "group-by"],
    attackTargetIds: [810],
  },
  ...FLOOR_TWO_PRACTICE_STAGES,
};

export function practiceStageFor(monsterId: number): LessonStageDefinition | null {
  return PRACTICE_STAGES[monsterId] ?? null;
}

const MONSTER_SCHEMA = [
  sqlSchemaLine("monsters"),
  "每条记录都是魔王城里真实存在的怪物。",
];

export const LESSONS: readonly LessonDefinition[] = [
  {
    id: "select",
    concept: "SELECT / FROM",
    title: "青页回廊 · 读取怪物档案",
    intro: "史莱姆把名字和弱点藏进怪物档案。完整写出 SELECT 与 FROM，夺回两段情报。",
    schema: MONSTER_SCHEMA,
    primaryMonsterId: 101,
    stages: [
      {
        id: "select-name",
        objective: "第一击：查询 id = 101 的怪物名字 name。",
        queryTemplate: "",
        hints: [
          "SELECT 后写想看到的列，FROM 后写数据表。",
          "目标列是 name，目标表是 monsters。",
          "使用 WHERE id = 101 只保留史莱姆。",
          "完整写法：SELECT name FROM monsters WHERE id = 101;",
        ],
        locks: ["SELECT", "FROM"],
        requiredFeatures: ["select", "from"],
        attackTargetIds: [101],
      },
      {
        id: "select-weakness",
        objective: "第二击：查询 id = 101 的 weakness，击穿史莱姆核心。",
        queryTemplate: "",
        hints: [
          "这次仍从 monsters 读取，但目标列发生了变化。",
          "SELECT 后应写 weakness。",
          "WHERE 仍然锁定 id = 101。",
          "完整写法：SELECT weakness FROM monsters WHERE id = 101;",
        ],
        locks: ["SELECT", "FROM"],
        requiredFeatures: ["select", "from"],
        attackTargetIds: [101],
      },
    ],
  },
  {
    id: "where",
    concept: "WHERE / AND",
    title: "猎犬廊 · 精确过滤",
    intro: "猎犬混在城堡记录中。名字、房间和状态都与怪物有关，任何多余行都会引来扑咬。",
    schema: MONSTER_SCHEMA,
    primaryMonsterId: 201,
    stages: [
      {
        id: "where-target",
        objective: "第一击：返回 room_id = 2 且 status = 'escaped' 的怪物 id。",
        queryTemplate: "",
        hints: [
          "WHERE 过滤行，AND 让两个条件同时成立。",
          "需要检查 room_id 和 status。",
          "条件是 room_id = 2 AND status = 'escaped'。",
          "完整写法：SELECT id FROM monsters WHERE room_id = 2 AND status = 'escaped';",
        ],
        locks: ["WHERE", "AND"],
        requiredFeatures: ["where", "and"],
        attackTargetIds: [201],
      },
      {
        id: "where-weakness",
        objective: "第二击：按怪物 name 与 status 过滤，返回猎犬的 weakness。",
        queryTemplate: "",
        hints: [
          "SELECT weakness，并在 WHERE 中同时检查 name 与 status。",
          "怪物名是 '猎犬'。",
          "状态仍是 'escaped'，两个条件使用 AND。",
          "完整写法：SELECT weakness FROM monsters WHERE name = '猎犬' AND status = 'escaped';",
        ],
        locks: ["WHERE", "AND"],
        requiredFeatures: ["where", "and"],
        attackTargetIds: [201],
      },
    ],
  },
  {
    id: "is-null",
    concept: "IS NULL",
    title: "无主墓室 · 判断未知",
    intro: "墓室里只有一名守卫没有主人。NULL 不是普通值，等号无法照出它。",
    schema: MONSTER_SCHEMA,
    primaryMonsterId: 301,
    stages: [
      {
        id: "null-target",
        objective: "第一击：返回 room_id = 3 且 master_id 为空的怪物 id。",
        queryTemplate: "",
        hints: [
          "NULL 表示未知，不能写 = NULL。",
          "判断空值使用 IS NULL。",
          "同时保留 room_id = 3，两个条件用 AND。",
          "完整写法：SELECT id FROM monsters WHERE room_id = 3 AND master_id IS NULL;",
        ],
        locks: ["WHERE", "IS NULL"],
        requiredFeatures: ["where", "is-null"],
        attackTargetIds: [301],
      },
      {
        id: "null-name",
        objective: "第二击：找出 master_id 为空且 status = 'cursed' 的怪物 name。",
        queryTemplate: "",
        hints: [
          "这次返回 name，而不是 id。",
          "master_id 仍使用 IS NULL。",
          "再用 AND 增加 status = 'cursed'。",
          "完整写法：SELECT name FROM monsters WHERE master_id IS NULL AND status = 'cursed';",
        ],
        locks: ["WHERE", "IS NULL"],
        requiredFeatures: ["where", "is-null"],
        attackTargetIds: [301],
      },
    ],
  },
  {
    id: "group-by",
    concept: "COUNT / GROUP BY",
    title: "聚合钟楼 · 统计信号",
    intro: "执行官把信号拆成 echo 与 noise。按 channel 分组统计，聚合战锤才能找到钟摆。",
    schema: [
      sqlSchemaLine("monster_signals"),
      "执行官 ID = 800，信号分为 echo 与 noise。",
    ],
    primaryMonsterId: 800,
    stages: [
      {
        id: "group-signals",
        objective: "按 channel 分组统计 monster_id = 800 的信号数，数量别名为 total。",
        queryTemplate: "",
        hints: [
          "COUNT(*) 统计每组行数，GROUP BY 决定分组列。",
          "读取 channel 和 COUNT(*) AS total。",
          "WHERE 先锁定 monster_id = 800，再 GROUP BY channel。",
          "完整写法：SELECT channel, COUNT(*) AS total FROM monster_signals WHERE monster_id = 800 GROUP BY channel;",
        ],
        locks: ["COUNT", "GROUP BY"],
        requiredFeatures: ["count", "group-by"],
        attackTargetIds: [800],
      },
    ],
  },
  {
    id: "having",
    concept: "HAVING",
    title: "魔王核心 · 过滤分组",
    intro: "监视者的信号分成 echo、ward 与 noise。HAVING 只在分组形成之后审判它们。",
    schema: [
      sqlSchemaLine("monster_signals"),
      "魔王 ID = 900；HAVING 在 GROUP BY 之后过滤聚合结果。",
    ],
    primaryMonsterId: 900,
    stages: [
      {
        id: "having-shield",
        objective: "第一阶段：只保留信号数不少于 2 的 channel，数量别名为 total。",
        queryTemplate: "",
        hints: [
          "WHERE 过滤原始行，HAVING 过滤已经形成的组。",
          "先按 channel 分组，再判断 COUNT(*)。",
          "护盾阈值是 COUNT(*) >= 2。",
          "完整写法：SELECT channel, COUNT(*) AS total FROM monster_signals WHERE monster_id = 900 GROUP BY channel HAVING COUNT(*) >= 2;",
        ],
        locks: ["GROUP BY", "HAVING"],
        requiredFeatures: ["group-by", "having"],
        attackTargetIds: [900],
      },
      {
        id: "having-core",
        objective: "核心阶段：把阈值提高到至少 3，只留下最强的 echo 组。",
        queryTemplate: "",
        hints: [
          "保持相同分组，把 HAVING 阈值提高。",
          "需要只返回 total = 3 的 echo 组。",
          "核心条件是 COUNT(*) >= 3。",
          "完整写法：SELECT channel, COUNT(*) AS total FROM monster_signals WHERE monster_id = 900 GROUP BY channel HAVING COUNT(*) >= 3;",
        ],
        locks: ["GROUP BY", "HAVING"],
        requiredFeatures: ["group-by", "having"],
        attackTargetIds: [900],
      },
    ],
  },
  ...FLOOR_TWO_LESSONS,
] as const;

export const LOOT_AFTER_LESSON: Partial<Record<LessonId, { weapon: Weapon; position: Position }>> = {
  select: { weapon: FILTER_BOW, position: { x: 10, y: 5 } },
  "is-null": { weapon: NULL_LANTERN, position: { x: 10, y: 5 } },
  ...FLOOR_TWO_LOOT_AFTER_LESSON,
};

export function lessonById(id: LessonId): LessonDefinition {
  const lesson = LESSONS.find((entry) => entry.id === id);
  if (!lesson) throw new Error(`未知课程：${id}`);
  return lesson;
}
