import type { LessonStageDefinition, Monster } from "../../../../domain/shared/types";
import {
  biomeMonster,
  type BiomeEncounterDefinition,
} from "../shared/biome";

export const FLOOR_FIVE_BIOME_MONSTERS: readonly Monster[] = [
  biomeMonster({
    floor: 5,
    id: 51,
    lessonId: "f5-over",
    roomId: 67,
    name: "小妖",
    species: "iron_goblin",
    kind: "goblin",
    hp: 18,
    maxHp: 18,
    armor: 0,
    damage: 3,
    attackName: "铁钉投掷",
    status: "scouting",
    weakness: "partition",
    masterId: 55,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 5,
    id: 52,
    lessonId: "f5-row-number",
    roomId: 68,
    name: "战兽",
    species: "barracks_orc",
    kind: "orc",
    hp: 20,
    maxHp: 20,
    armor: 0,
    damage: 3,
    attackName: "肩甲冲撞",
    status: "marching",
    weakness: "row-number",
    masterId: 55,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 5,
    id: 53,
    lessonId: "f5-rank",
    roomId: 68,
    name: "铁卫",
    species: "iron_guard",
    kind: "knight",
    hp: 24,
    maxHp: 24,
    armor: 1,
    damage: 4,
    attackName: "盾墙推进",
    status: "guarding",
    weakness: "rank",
    masterId: 55,
    isBoss: false,
    rank: "elite",
  }),
  biomeMonster({
    floor: 5,
    id: 54,
    lessonId: "f5-frame",
    roomId: 69,
    name: "石魔",
    species: "citadel_troll",
    kind: "troll",
    hp: 22,
    maxHp: 22,
    armor: 0,
    damage: 3,
    attackName: "石块砸击",
    status: "hauling",
    weakness: "frame",
    masterId: 55,
    isBoss: false,
    rank: "normal",
  }),
  biomeMonster({
    floor: 5,
    id: 55,
    lessonId: "f5-top-n",
    roomId: 70,
    name: "堡主",
    species: "citadel_lord",
    kind: "castle-lord",
    hp: 36,
    maxHp: 36,
    armor: 2,
    damage: 4,
    attackName: "城弩齐射",
    status: "commanding",
    weakness: "top-n",
    masterId: 50,
    isBoss: true,
    rank: "elite",
  }),
] as const;

const PRACTICE_GOBLIN: LessonStageDefinition = {
  id: "practice-goblin",
  objective: "查询 id 51 到 52 的 id，并按 master_id 分区计算 guard_total。",
  queryTemplate: "",
  answerSql: "SELECT id, COUNT(*) OVER (PARTITION BY master_id) AS guard_total FROM monsters WHERE id BETWEEN 51 AND 52 ORDER BY id;",
  hints: [
    "返回 id 与 guard_total。",
    "使用 COUNT(*) OVER (...)。",
    "按 master_id 分区。",
    "完整写法：SELECT id, COUNT(*) OVER (PARTITION BY master_id) AS guard_total FROM monsters WHERE id BETWEEN 51 AND 52 ORDER BY id;",
  ],
  locks: ["OVER", "PARTITION BY"],
  requiredFeatures: ["over", "partition-by"],
  attackTargetIds: [51],
};

const PRACTICE_ORC: LessonStageDefinition = {
  id: "practice-orc",
  objective: "连接装备表，对 id 51 到 52 按 power 降序生成 pos，并按 pos 返回 id。",
  queryTemplate: "",
  answerSql: "SELECT m.id, ROW_NUMBER() OVER (ORDER BY g.power DESC, m.id) AS pos FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 51 AND 52 ORDER BY pos;",
  hints: [
    "返回 id 与 pos。",
    "使用 ROW_NUMBER() OVER (...)。",
    "窗口按装备 power DESC、id 排序。",
    "完整写法：SELECT m.id, ROW_NUMBER() OVER (ORDER BY g.power DESC, m.id) AS pos FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 51 AND 52 ORDER BY pos;",
  ],
  locks: ["ROW_NUMBER", "ORDER BY"],
  requiredFeatures: ["row-number", "order-by"],
  attackTargetIds: [52],
};

const PRACTICE_KNIGHT: LessonStageDefinition = {
  id: "practice-knight",
  objective: "连接装备表，查询 id 52 到 53 的 id、power 与 rank_no，按 power 降序排列。",
  queryTemplate: "",
  answerSql: "SELECT m.id, g.power, RANK() OVER (ORDER BY g.power DESC) AS rank_no FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 52 AND 53 ORDER BY g.power DESC, m.id;",
  hints: [
    "返回 id、power、rank_no。",
    "rank_no 使用 RANK()。",
    "窗口按装备 power DESC。",
    "完整写法：SELECT m.id, g.power, RANK() OVER (ORDER BY g.power DESC) AS rank_no FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 52 AND 53 ORDER BY g.power DESC, m.id;",
  ],
  locks: ["RANK", "OVER"],
  requiredFeatures: ["rank", "over"],
  attackTargetIds: [53],
};

const PRACTICE_TROLL: LessonStageDefinition = {
  id: "practice-troll",
  objective: "连接装备表，查询 id 51 到 54 的 id 与 running_power，按 id 累计 power。",
  queryTemplate: "",
  answerSql: "SELECT m.id, SUM(g.power) OVER (ORDER BY m.id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 51 AND 54 ORDER BY m.id;",
  hints: [
    "返回 id 与 running_power。",
    "使用 SUM(g.power) OVER (...)。",
    "写明从第一行到当前行的 ROWS Frame。",
    "完整写法：SELECT m.id, SUM(g.power) OVER (ORDER BY m.id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 51 AND 54 ORDER BY m.id;",
  ],
  locks: ["OVER", "ROWS FRAME"],
  requiredFeatures: ["over", "window-frame"],
  attackTargetIds: [54],
};

const IRON_BOSS_SCAN: LessonStageDefinition = {
  id: "iron-boss-scan",
  objective: "第一击：连接装备表，对 ID #051–#055 按 power 降序计算 RANK() AS rank_no，并按 m.id 返回 m.id、rank_no。",
  queryTemplate: "",
  answerSql: "SELECT m.id, RANK() OVER (ORDER BY g.power DESC) AS rank_no FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 51 AND 55 ORDER BY m.id;",
  hints: [
    "返回 m.id 与 rank_no。",
    "窗口函数使用 RANK()。",
    "窗口按 g.power DESC，结果按 m.id。",
    "完整写法：SELECT m.id, RANK() OVER (ORDER BY g.power DESC) AS rank_no FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 51 AND 55 ORDER BY m.id;",
  ],
  locks: ["RANK", "OVER", "ORDER BY"],
  requiredFeatures: ["rank", "over", "order-by"],
  attackTargetIds: [55],
};

const IRON_BOSS_CORE: LessonStageDefinition = {
  id: "iron-boss-core",
  objective: "第二击：连接装备表，对 ID #051–#055 同时用 LAG 与 LEAD 读取前后 power，返回 id、prev_power、next_power。",
  queryTemplate: "",
  answerSql: "SELECT m.id, LAG(g.power) OVER (ORDER BY m.id) AS prev_power, LEAD(g.power) OVER (ORDER BY m.id) AS next_power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 51 AND 55 ORDER BY m.id;",
  hints: [
    "返回 id、prev_power、next_power。",
    "分别使用 LAG(g.power) 与 LEAD(g.power)。",
    "两个窗口和结果都按 m.id。",
    "完整写法：SELECT m.id, LAG(g.power) OVER (ORDER BY m.id) AS prev_power, LEAD(g.power) OVER (ORDER BY m.id) AS next_power FROM monsters m INNER JOIN monster_gear g ON m.id = g.monster_id WHERE m.id BETWEEN 51 AND 55 ORDER BY m.id;",
  ],
  locks: ["LAG", "LEAD", "ORDER BY"],
  requiredFeatures: ["lag", "lead", "order-by"],
  attackTargetIds: [55],
};

export const FLOOR_BIOME_ENCOUNTERS = [
  { monsterId: 51, floor: 5, biome: "iron-yard", role: "normal", randomEncounter: true, stages: [PRACTICE_GOBLIN] },
  { monsterId: 52, floor: 5, biome: "barracks", role: "normal", randomEncounter: true, stages: [PRACTICE_ORC] },
  { monsterId: 53, floor: 5, biome: "barracks", role: "mini-elite", randomEncounter: true, stages: [PRACTICE_KNIGHT] },
  { monsterId: 54, floor: 5, biome: "black-citadel", role: "normal", randomEncounter: true, stages: [PRACTICE_TROLL] },
  { monsterId: 55, floor: 5, biome: "barracks", role: "area-boss", randomEncounter: false, stages: [IRON_BOSS_SCAN, IRON_BOSS_CORE] },
] as const satisfies readonly BiomeEncounterDefinition[];

