/** 第三层固定地标、隐藏房、故事触发和世界变化配置。 */
import type {
  FloorAnchorDefinition,
  FloorExperienceDefinition,
  FloorLandmarkDefinition,
} from "./types";

function anchor(
  roomNodeId: string,
  x: number,
  y: number,
  facing: FloorAnchorDefinition["facing"] = "south",
  width = 3,
  height = 3,
): FloorAnchorDefinition {
  return { roomNodeId, position: { x, y }, facing, clearance: { width, height } };
}

function landmark(
  input: Omit<FloorLandmarkDefinition, "minimapIcon"> & { minimapIcon?: string },
): FloorLandmarkDefinition {
  return { ...input, minimapIcon: input.minimapIcon ?? "landmark" };
}

export const FLOOR_THREE_EXPERIENCE: FloorExperienceDefinition = {
  id: "floor-03-frost-gravefield",
  floor: 3,
  title: "白霜墓原",
  subtitle: "名字会消失，关系仍在冰下相连",
  version: 1,
  signature: "冻结墓碑之间以 JOIN 形成实体骨桥，幽火地宫保存没有当前主人的遗物",
  assetPack: {
    id: "floor-03-frost-gravefield-assets",
    version: 1,
    manifestPath: "/assets/floors/03-frost-gravefield/manifest.json",
    assets: [],
  },
  regions: [
    {
      id: "f3-bone-yard",
      navigationRegion: "front",
      name: "遗骨荒地",
      purpose: "用明确的两端关系搭起第一座骨桥",
      lessonIds: ["f3-inner", "f3-left"],
      material: "白霜、断骨、低矮墓碑与黑色冻土",
      ambience: "稀疏大提琴、远风与低音钟",
      landmarkIds: ["f3-spawn-cairn", "f3-relation-bridge", "f3-front-fire"],
    },
    {
      id: "f3-grave-mire",
      navigationRegion: "middle",
      name: "腐土墓园",
      purpose: "让同表别名和三表关系成为看得见的墓志连接",
      lessonIds: ["f3-self", "f3-chain"],
      material: "湿黑腐土、铜绿碑框、垂落锁链",
      ambience: "缓慢中提琴、泥水与链条回响",
      landmarkIds: ["f3-master-steles", "f3-relic-chain", "f3-grave-lord", "f3-rear-fire"],
    },
    {
      id: "f3-spirit-crypt",
      navigationRegion: "rear",
      name: "幽火地宫",
      purpose: "用 UNION 保留多处证词，并审计唯一继承人的错误规则",
      lessonIds: ["f3-union", "f3-audit"],
      material: "冰蓝幽火、深色石棺与象牙色墓志",
      ambience: "低声合唱、柔和圆号与空旷残响",
      landmarkIds: ["f3-reliquary", "f3-sql-seal", "f3-necromancer-throne", "f3-burial-shaft"],
    },
  ],
  landmarks: [
    landmark({
      id: "f3-spawn-cairn",
      name: "冻岸石冢",
      kind: "spawn-anchor",
      regionId: "f3-bone-yard",
      anchor: anchor("floor-3-entry", 0.22, 0.62, "east"),
      assetKey: "shared.setpiece.stone-cairn",
      fallback: "frost-cairn",
      interaction: null,
      stateKeys: ["always"],
    }),
    landmark({
      id: "f3-relation-bridge",
      name: "断裂骨桥",
      kind: "world-machine",
      regionId: "f3-bone-yard",
      anchor: anchor("floor-3-lesson-1", 0.56, 0.48, "west", 8, 4),
      assetKey: "shared.setpiece.bone-bridge",
      fallback: "bone-bridge",
      interaction: "读取桥两端的墓室编号",
      stateKeys: ["severed", "linked"],
      minimapIcon: "bridge",
    }),
    landmark({
      id: "f3-front-fire",
      name: "冻岸篝火",
      kind: "campfire",
      regionId: "f3-bone-yard",
      anchor: anchor("floor-3-rest", 0.52, 0.62),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f3-master-steles",
      name: "双名墓碑",
      kind: "story",
      regionId: "f3-grave-mire",
      anchor: anchor("floor-3-lesson-3", 0.5, 0.38, "north", 7, 4),
      assetKey: "shared.setpiece.twin-steles",
      fallback: "twin-steles",
      interaction: "对照死者与主人",
      stateKeys: ["anonymous", "aliased"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f3-relic-chain",
      name: "三段遗物链",
      kind: "world-machine",
      regionId: "f3-grave-mire",
      anchor: anchor("floor-3-lesson-4", 0.52, 0.5, "east", 8, 4),
      assetKey: "shared.setpiece.relic-chain",
      fallback: "relic-chain",
      interaction: "连接死者、墓室与遗物",
      stateKeys: ["loose", "linked"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f3-rear-fire",
      name: "守墓人篝火",
      kind: "campfire",
      regionId: "f3-grave-mire",
      anchor: anchor("floor-3-event", 0.72, 0.64),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或本层答案复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f3-reliquary",
      name: "无主遗物室",
      kind: "story",
      regionId: "f3-spirit-crypt",
      anchor: anchor("floor-3-treasure", 0.5, 0.46, "south", 7, 6),
      assetKey: "shared.setpiece.reliquary",
      fallback: "frost-reliquary",
      interaction: "核对遗物的当前主人",
      stateKeys: ["sealed", "discovered"],
      minimapIcon: "secret",
    }),
    landmark({
      id: "f3-grave-lord",
      name: "双墓园见证坛",
      kind: "boss-arena",
      regionId: "f3-grave-mire",
      anchor: anchor("floor-3-event", 0.42, 0.48, "north", 7, 7),
      assetKey: "shared.setpiece.grave-altar",
      fallback: "grave-altar",
      interaction: "挑战区域首领 ID #033",
      stateKeys: ["sealed", "defeated"],
      minimapIcon: "area-boss",
    }),
    landmark({
      id: "f3-sql-seal",
      name: "三表墓印",
      kind: "sql-seal",
      regionId: "f3-spirit-crypt",
      anchor: anchor("floor-3-lesson-6", 0.18, 0.56, "east", 3, 4),
      assetKey: "shared.setpiece.crypt-throne",
      fallback: "query-seal",
      interaction: "用三表审计提前解开王座墓门",
      stateKeys: ["sealed", "decoded"],
      minimapIcon: "query",
    }),
    landmark({
      id: "f3-necromancer-throne",
      name: "唯一继承审计座",
      kind: "boss-arena",
      regionId: "f3-spirit-crypt",
      anchor: anchor("floor-3-lesson-6", 0.5, 0.38, "north", 9, 8),
      assetKey: "shared.setpiece.crypt-throne",
      fallback: "crypt-throne",
      interaction: "审计唯一继承人规则",
      stateKeys: ["judging", "audited"],
      minimapIcon: "boss",
    }),
    landmark({
      id: "f3-burial-shaft",
      name: "葬火井",
      kind: "transit",
      regionId: "f3-spirit-crypt",
      anchor: anchor("floor-3-lesson-6", 0.82, 0.7, "east", 4, 4),
      assetKey: "shared.setpiece.burial-shaft",
      fallback: "burial-shaft",
      interaction: "前往元素升炉",
      stateKeys: ["cold", "lit"],
      minimapIcon: "ascent",
    }),
  ],
  npcPlacements: [{
    id: "npc-scribe-f3",
    name: "抄写员",
    role: "替没有当前主人的遗物保留旧关系",
    regionId: "f3-bone-yard",
    anchor: anchor("floor-3-entry", 0.5, 0.4, "south", 2, 2),
    assetKey: "shared.actor.scribe",
    alwaysShowName: true,
  }],
  hiddenAreas: [{
    id: "f3-hidden-reliquary",
    title: "无主遗物室",
    roomNodeId: "floor-3-treasure",
    gateId: "gate:floor-3-treasure",
    landmarkId: "f3-reliquary",
    requiredLessonIds: ["f3-inner", "f3-left", "f3-self"],
    sealedPrompt: "E  调查结霜墓志后的空槽",
    sealedMessage: "三块墓志分别记录死者、墓室与主人。先学会连接两表、保留缺失记录，再为同一张表命名两个身份。",
    openPrompt: "E  推开无主遗物室",
    openedMessage: "冰封石门退入墙内。一件没有当前主人的遗物仍保留着多条旧关系。",
    discoveryEventId: "f3-story-reliquary",
  }],
  storyEvents: [
    {
      id: "f3-story-no-owner",
      title: "没有主人的遗物",
      trigger: "floor-entered",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "music-state", state: "f3-frozen-cello" },
        { type: "camera-focus", landmarkId: "f3-relation-bridge" },
        { type: "dialogue", speaker: "抄写员", lines: ["名字会从碑上磨掉。", "关系不会。先看清它连接了哪两端。"] },
      ],
      completionFact: "story:f3:entry-seen",
    },
    {
      id: "f3-story-reliquary",
      title: "无主不等于从未属于",
      trigger: "gate:floor-3-treasure:opened",
      repeat: "once",
      priority: 90,
      actions: [
        { type: "camera-focus", landmarkId: "f3-reliquary" },
        { type: "world-effect", effect: "f3-reliquary-open" },
        { type: "evidence", evidenceId: "lost-name:f3:current-owner" },
        { type: "dialogue", speaker: "抄写员", lines: ["CURRENT OWNER 已确认是 NULL。", "它没有现在的主人，却留下了过去的连接。"] },
      ],
      completionFact: "story:f3:reliquary",
    },
    {
      id: "f3-story-grave-lord",
      title: "冰下的多份证词",
      trigger: "monster:33:defeated",
      repeat: "once",
      priority: 92,
      actions: [
        { type: "camera-focus", landmarkId: "f3-grave-lord" },
        { type: "world-effect", effect: "f3-witnesses-rise" },
        { type: "dialogue", speaker: "抄写员", lines: ["墓主想删去互相冲突的证词。", "UNION 保住了它们；冲突本身也是事实。"] },
      ],
      completionFact: "story:f3:grave-lord",
    },
    {
      id: "f3-story-cipher",
      title: "三表墓印被完整关系解开",
      trigger: "gate:floor-3-lesson-6:opened",
      repeat: "once",
      priority: 88,
      actions: [
        { type: "camera-focus", landmarkId: "f3-sql-seal" },
        { type: "world-effect", effect: "f3-cipher-decoded" },
        { type: "banner", text: "怪物、墓室与遗物校验通过；王座墓门永久开启" },
      ],
      completionFact: "story:f3:cipher",
    },
    {
      id: "f3-story-audit-complete",
      title: "墓门从内部打开",
      trigger: "monster:28:defeated",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "camera-focus", landmarkId: "f3-burial-shaft" },
        { type: "world-effect", effect: "f3-burial-shaft-lit" },
        { type: "dialogue", speaker: "抄写员", lines: ["你不是墓碑上的某一个名字。", "你是这些关系没有被删掉以后，仍能彼此找到的结果。"] },
      ],
      completionFact: "story:f3:completed",
    },
  ],
  environmentRules: [
    { id: "f3-bone-linked", when: "f3-inner:completed", state: "bone_bridge=linked", visibleResult: "骨桥连接怪物记录与墓室记录" },
    { id: "f3-unarmed-kept", when: "f3-left:completed", state: "missing_gear=kept", visibleResult: "没有装备记录的墓位仍被保留" },
    { id: "f3-steles-aliased", when: "f3-self:completed", state: "steles=aliased", visibleResult: "双名墓碑分别显示死者与主人" },
    { id: "f3-relic-chain", when: "f3-chain:completed", state: "relic_chain=linked", visibleResult: "死者、墓室与遗物连成三段证据链" },
    { id: "f3-witnesses-united", when: "f3-union:completed", state: "witnesses=united", visibleResult: "两处墓园的证词同时升起" },
    { id: "f3-shaft-lit", when: "f3-audit:completed", state: "burial_shaft=lit", visibleResult: "葬火井点燃并接入第四层" },
  ],
  adminPresets: [
    { id: "f3-admin-entry", label: "F3 冻岸入口", completedLessonIds: [], defeatedMonsterIds: [], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f3-relation-bridge" },
    { id: "f3-admin-reliquary", label: "F3 无主遗物室", completedLessonIds: ["f3-inner", "f3-left", "f3-self"], defeatedMonsterIds: [23, 24, 25], openedGateIds: ["gate:floor-3-treasure"], collectedKeyItems: [], focusLandmarkId: "f3-reliquary" },
    { id: "f3-admin-grave-lord", label: "F3 墓主见证坛", completedLessonIds: ["f3-inner", "f3-left", "f3-self", "f3-chain", "f3-union"], defeatedMonsterIds: [23, 24, 25, 26, 27, 33], openedGateIds: ["shortcut:3:return"], collectedKeyItems: ["shortcut-key:3"], focusLandmarkId: "f3-grave-lord" },
    { id: "f3-admin-complete", label: "F3 葬火井", completedLessonIds: ["f3-inner", "f3-left", "f3-self", "f3-chain", "f3-union", "f3-audit"], defeatedMonsterIds: [23, 24, 25, 26, 27, 28, 33], openedGateIds: ["shortcut:3:return"], collectedKeyItems: ["floor-key:3"], focusLandmarkId: "f3-burial-shaft" },
  ],
};
