import type {
  FloorAnchorDefinition,
  FloorExperienceDefinition,
  FloorLandmarkDefinition,
} from "./types";

function anchor(
  roomNodeId: string,
  x: number,
  y: number,
  facing: FloorAnchorDefinition["facing"] = "south",
  width = 3,
  height = 3,
): FloorAnchorDefinition {
  return {
    roomNodeId,
    position: { x, y },
    facing,
    clearance: { width, height },
  };
}

function landmark(
  input: Omit<FloorLandmarkDefinition, "minimapIcon"> & { minimapIcon?: string },
): FloorLandmarkDefinition {
  return { ...input, minimapIcon: input.minimapIcon ?? "landmark" };
}

export const FLOOR_ONE_EXPERIENCE: FloorExperienceDefinition = {
  id: "floor-01-ember-archive",
  floor: 1,
  title: "地下余烬档案",
  subtitle: "火记得你，登记册却没有你",
  version: 1,
  signature: "高水位档案地窖、铜质水轮与一张拒绝被丢弃的空白页",
  assetPack: {
    id: "floor-01-ember-archive-assets",
    version: 1,
    manifestPath: "/assets/floors/01-ember-archive/manifest.json",
    assets: [
      {
        key: "f01-cc0-floor",
        kind: "tileset",
        path: "/assets/floors/01-ember-archive/sources/0x72-dungeontileset-ii/atlas-floor-16x16.png",
        fallback: "archive-geometric",
      },
      {
        key: "f01-cc0-walls",
        kind: "tileset",
        path: "/assets/floors/01-ember-archive/sources/0x72-dungeontileset-ii/atlas-walls-low-16x16.png",
        fallback: "archive-geometric",
      },
      {
        key: "f01-cc0-door-closed",
        kind: "setpiece",
        path: "/assets/floors/01-ember-archive/sources/0x72-dungeontileset-ii/door-closed.png",
        fallback: "brass-lift",
      },
      {
        key: "f01-cc0-door-open",
        kind: "setpiece",
        path: "/assets/floors/01-ember-archive/sources/0x72-dungeontileset-ii/door-open.png",
        fallback: "brass-lift",
      },
      {
        key: "f01-cc0-lever-closed",
        kind: "setpiece",
        path: "/assets/floors/01-ember-archive/sources/0x72-dungeontileset-ii/lever-closed.png",
        fallback: "copper-wheel",
      },
      {
        key: "f01-cc0-lever-open",
        kind: "setpiece",
        path: "/assets/floors/01-ember-archive/sources/0x72-dungeontileset-ii/lever-open.png",
        fallback: "copper-wheel",
      },
    ],
  },
  regions: [
    {
      id: "f1-drainage",
      name: "青石排水渠",
      purpose: "建立移动、身份矛盾与 SELECT 的第一条可见因果链",
      lessonIds: ["select", "where"],
      material: "湿青石、铜管、浅水反光",
      ambience: "低火、滴水与远处水轮",
      landmarkIds: ["f1-spawn-ember", "f1-water-wheel", "f1-middle-fire"],
    },
    {
      id: "f1-dormitory",
      name: "无名宿舍",
      purpose: "用水位和空床牌解释 NULL 是已确认的缺失",
      lessonIds: ["is-null"],
      material: "浸水木床、湿墙姓名线、旧铜牌",
      ambience: "近水、空管回声与纸页摩擦",
      landmarkIds: ["f1-nameless-beds", "f1-back-shortcut"],
    },
    {
      id: "f1-registry",
      name: "回燃登记厅",
      purpose: "把 GROUP BY、HAVING、抄写员与登记官汇聚到同一个回环终点",
      lessonIds: ["group-by", "having"],
      material: "余烬砖、铜印、成排档案架",
      ambience: "温暖大提琴底色、印章与低沉风管",
      landmarkIds: ["f1-scribe-desk", "f1-rear-fire", "f1-registry-arena", "f1-lift"],
    },
  ],
  landmarks: [
    landmark({
      id: "f1-spawn-ember",
      name: "低燃余烬锚点",
      kind: "spawn-anchor",
      regionId: "f1-drainage",
      anchor: anchor("floor-1-entry", 0.22, 0.62, "east"),
      assetKey: "f01-cc0-floor",
      fallback: "small-ember-ring",
      interaction: null,
      stateKeys: ["always"],
    }),
    landmark({
      id: "f1-water-wheel",
      name: "铜质档案水轮",
      kind: "world-machine",
      regionId: "f1-drainage",
      anchor: anchor("floor-1-tutorial", 0.76, 0.32, "west", 5, 5),
      assetKey: "f01-cc0-lever-closed",
      fallback: "copper-wheel",
      interaction: "调查水轮控制记录",
      stateKeys: ["stalled", "turning"],
      minimapIcon: "wheel",
    }),
    landmark({
      id: "f1-middle-fire",
      name: "排水渠篝火",
      kind: "campfire",
      regionId: "f1-drainage",
      anchor: anchor("floor-1-rest", 0.5, 0.5),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f1-nameless-beds",
      name: "无名床位",
      kind: "story",
      regionId: "f1-dormitory",
      anchor: anchor("floor-1-is-null", 0.52, 0.26, "south", 6, 4),
      assetKey: "f01-cc0-floor",
      fallback: "submerged-beds",
      interaction: "读取床牌",
      stateKeys: ["submerged", "visible", "null-confirmed"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f1-back-shortcut",
      name: "登记厅背面铁门",
      kind: "shortcut",
      regionId: "f1-dormitory",
      anchor: anchor("floor-1-treasure", 0.16, 0.5, "west", 2, 4),
      assetKey: "f01-cc0-door-closed",
      fallback: "iron-floodgate",
      interaction: "从深处开启",
      stateKeys: ["closed", "open"],
      minimapIcon: "shortcut",
    }),
    landmark({
      id: "f1-scribe-desk",
      name: "抄写员记录桌",
      kind: "story",
      regionId: "f1-registry",
      anchor: anchor("floor-1-event", 0.32, 0.38, "south", 4, 3),
      assetKey: "f01-cc0-walls",
      fallback: "desk-and-pages",
      interaction: "调查身份记录",
      stateKeys: ["writing", "sorting", "binding"],
      minimapIcon: "npc",
    }),
    landmark({
      id: "f1-rear-fire",
      name: "登记厅篝火",
      kind: "campfire",
      regionId: "f1-registry",
      anchor: anchor("floor-1-event", 0.73, 0.7),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或本层答案复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f1-registry-arena",
      name: "回燃登记大厅",
      kind: "boss-arena",
      regionId: "f1-registry",
      anchor: anchor("floor-1-boss", 0.5, 0.43, "north", 8, 7),
      assetKey: "f01-cc0-walls",
      fallback: "registry-columns",
      interaction: "挑战 ID #005",
      stateKeys: ["dormant", "awake", "amended"],
      minimapIcon: "boss",
    }),
    landmark({
      id: "f1-lift",
      name: "档案升降机",
      kind: "transit",
      regionId: "f1-registry",
      anchor: anchor("floor-1-boss", 0.84, 0.18, "north", 3, 4),
      assetKey: "f01-cc0-door-closed",
      fallback: "brass-lift",
      interaction: "前往月潮群岛",
      stateKeys: ["locked", "active"],
      minimapIcon: "ascent",
    }),
  ],
  npcPlacements: [
    {
      id: "npc-scribe-f1",
      name: "抄写员",
      role: "唯一连续引导者与失名录保管人",
      regionId: "f1-registry",
      anchor: anchor("floor-1-entry", 0.62, 0.42, "south", 2, 2),
      assetKey: "shared.actor.scribe",
      alwaysShowName: true,
    },
  ],
  storyEvents: [
    {
      id: "f1-story-fire-remembers",
      title: "火记得你",
      trigger: "floor-entered",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "music-state", state: "f1-home-ember" },
        { type: "camera-focus", landmarkId: "f1-spawn-ember" },
        { type: "banner", text: "居民记录：0 行 · 恢复权限：有效" },
      ],
      completionFact: "story:f1:entry-seen",
    },
    {
      id: "f1-story-wheel-turns",
      title: "水轮不是门",
      trigger: "lesson:select:completed",
      repeat: "once",
      priority: 80,
      actions: [
        { type: "camera-focus", landmarkId: "f1-water-wheel" },
        { type: "world-effect", effect: "f1-water-wheel-start" },
        { type: "banner", text: "查询结果已写入水轮控制记录" },
      ],
      completionFact: "story:f1:wheel-seen",
    },
    {
      id: "f1-story-shortcut-return",
      title: "打开身后的门",
      trigger: "gate:shortcut:1:return:opened",
      repeat: "once",
      priority: 70,
      actions: [
        { type: "camera-focus", landmarkId: "f1-back-shortcut" },
        { type: "dialogue", speaker: "抄写员", lines: ["门后不是出口。", "它把你带回了问题开始的地方。"] },
      ],
      completionFact: "story:f1:shortcut-seen",
    },
    {
      id: "f1-story-first-page",
      title: "失名录第一页",
      trigger: "monster:5:defeated",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "world-effect", effect: "f1-registry-amended" },
        { type: "evidence", evidenceId: "lost-name:f1:restore-permission" },
        { type: "dialogue", speaker: "抄写员", lines: ["我不能替你写名字。", "但这一页不会再被当成空白丢掉。"] },
      ],
      completionFact: "story:f1:completed",
    },
  ],
  environmentRules: [
    { id: "f1-water-high", when: "select:not-completed", state: "water=high", visibleResult: "排水渠高水位，水轮停止" },
    { id: "f1-wheel-turning", when: "select:completed", state: "wheel=turning", visibleResult: "铜轮连续转动，宿舍栈桥放下" },
    { id: "f1-water-low", when: "where:completed", state: "water=low", visibleResult: "低处道路、湿墙姓名线露出" },
    { id: "f1-beds-revealed", when: "is-null:completed", state: "beds=revealed", visibleResult: "床牌由 ??? 变为 NULL" },
    { id: "f1-receipts-grouped", when: "group-by:completed", state: "receipts=grouped", visibleResult: "恢复回执按来源分堆并照亮中央路" },
    { id: "f1-registry-amended", when: "monster:5:defeated", state: "registry=amended", visibleResult: "规则改为 RESTORE TRACE ACCEPTED，升降机启动" },
  ],
  adminPresets: [
    { id: "f1-admin-entry", label: "F1 入层", completedLessonIds: [], defeatedMonsterIds: [], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f1-spawn-ember" },
    { id: "f1-admin-dormitory", label: "F1 无名宿舍", completedLessonIds: ["select", "where", "is-null"], defeatedMonsterIds: [1, 2, 3], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f1-nameless-beds" },
    { id: "f1-admin-shortcut", label: "F1 捷径回访", completedLessonIds: ["select", "where", "is-null", "group-by"], defeatedMonsterIds: [1, 2, 3, 4], openedGateIds: ["shortcut:1:return"], collectedKeyItems: ["shortcut-key:1"], focusLandmarkId: "f1-back-shortcut" },
    { id: "f1-admin-complete", label: "F1 通关", completedLessonIds: ["select", "where", "is-null", "group-by", "having"], defeatedMonsterIds: [1, 2, 3, 4, 5], openedGateIds: ["shortcut:1:return"], collectedKeyItems: ["floor-key:1"], focusLandmarkId: "f1-lift" },
  ],
};
