import type {
  FloorAnchorDefinition,
  FloorExperienceDefinition,
  FloorLandmarkDefinition,
} from "./types";

function anchor(
  roomNodeId: string,
  x: number,
  y: number,
  facing: FloorAnchorDefinition["facing"] = "south",
  width = 3,
  height = 3,
): FloorAnchorDefinition {
  return { roomNodeId, position: { x, y }, facing, clearance: { width, height } };
}

function landmark(
  input: Omit<FloorLandmarkDefinition, "minimapIcon"> & { minimapIcon?: string },
): FloorLandmarkDefinition {
  return { ...input, minimapIcon: input.minimapIcon ?? "landmark" };
}

export const FLOOR_FOUR_EXPERIENCE: FloorExperienceDefinition = {
  id: "floor-04-elemental-furnace",
  floor: 4,
  title: "三相升炉",
  subtitle: "火、冰与雷，都是同一次未完成命令的余波",
  version: 1,
  signature: "三种元素沿依赖管线汇入中央炉心，中层首领倒下后回燃门显出第一层残响",
  assetPack: {
    id: "floor-04-elemental-furnace-assets",
    version: 1,
    manifestPath: "/assets/floors/04-elemental-furnace/manifest.json",
    assets: [],
  },
  regions: [
    {
      id: "f4-fire-forge",
      navigationRegion: "front",
      name: "烈焰熔炉",
      purpose: "以标量子查询和 CTE 追到命令源头",
      lessonIds: ["f4-scalar", "f4-cte"],
      material: "黑铁炉壁、暗红熔沟与黄铜检修环",
      ambience: "低音弦乐、柔和定音鼓与缓慢炉息",
      landmarkIds: ["f4-spawn-furnace", "f4-source-core", "f4-front-fire"],
    },
    {
      id: "f4-frost-vault",
      navigationRegion: "middle",
      name: "寒霜冰库",
      purpose: "用 IN 与相关子查询辨认一组依赖记录，并挑战中层首领 ID #044",
      lessonIds: ["f4-in", "f4-correlated"],
      material: "蓝白冰槽、冻结铜管与镜面石板",
      ambience: "大提琴泛音、低木管与克制的冰裂声",
      landmarkIds: ["f4-frost-array", "f4-forge-lord", "f4-middle-fire"],
    },
    {
      id: "f4-storm-core",
      navigationRegion: "rear",
      name: "雷晶核心",
      purpose: "用 EXISTS、CTE 与递归依赖链证明三处事故来自同一命令",
      lessonIds: ["f4-exists", "f4-cte", "f4-recursive"],
      material: "紫色雷晶、黑石导轨与金色执行环",
      ambience: "圆号、低弦与逐渐扩大的庄严和声",
      landmarkIds: [
        "f4-dependency-spine",
        "f4-echo-gate",
        "f4-echo-registry",
        "f4-echo-ember",
        "f4-echo-null-bed",
        "f4-echo-return",
        "f4-sql-seal",
        "f4-elemental-throne",
        "f4-ascent",
      ],
    },
  ],
  landmarks: [
    landmark({
      id: "f4-spawn-furnace",
      name: "葬火接收炉",
      kind: "spawn-anchor",
      regionId: "f4-fire-forge",
      anchor: anchor("floor-4-entry", 0.2, 0.62, "east"),
      assetKey: "shared.setpiece.receiver-furnace",
      fallback: "receiver-furnace",
      interaction: null,
      stateKeys: ["always"],
    }),
    landmark({
      id: "f4-source-core",
      name: "命令源炉",
      kind: "world-machine",
      regionId: "f4-fire-forge",
      anchor: anchor("floor-4-lesson-1", 0.58, 0.5, "north", 6, 6),
      assetKey: "shared.setpiece.source-furnace",
      fallback: "source-furnace",
      interaction: "读取内层命令编号",
      stateKeys: ["opaque", "identified"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f4-front-fire",
      name: "熔沟篝火",
      kind: "campfire",
      regionId: "f4-fire-forge",
      anchor: anchor("floor-4-rest", 0.52, 0.62),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f4-frost-array",
      name: "冻结依赖阵列",
      kind: "world-machine",
      regionId: "f4-frost-vault",
      anchor: anchor("floor-4-lesson-2", 0.5, 0.46, "west", 7, 5),
      assetKey: "shared.setpiece.frost-array",
      fallback: "frost-array",
      interaction: "查看属于同一集合的冰槽",
      stateKeys: ["mixed", "selected"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f4-forge-lord",
      name: "镜像截流平台",
      kind: "boss-arena",
      regionId: "f4-frost-vault",
      anchor: anchor("floor-4-event", 0.44, 0.5, "north", 8, 7),
      assetKey: "shared.setpiece.mirror-forge",
      fallback: "mirror-forge",
      interaction: "挑战中层首领 ID #044",
      stateKeys: ["sealed", "defeated"],
      minimapIcon: "area-boss",
    }),
    landmark({
      id: "f4-middle-fire",
      name: "检修台篝火",
      kind: "campfire",
      regionId: "f4-frost-vault",
      anchor: anchor("floor-4-event", 0.74, 0.7),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或本层答案复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f4-dependency-spine",
      name: "三相依赖脊柱",
      kind: "world-machine",
      regionId: "f4-storm-core",
      anchor: anchor("floor-4-lesson-5", 0.52, 0.5, "north", 8, 7),
      assetKey: "shared.setpiece.dependency-spine",
      fallback: "dependency-spine",
      interaction: "沿公共表表达式追溯依赖",
      stateKeys: ["fragmented", "named", "traced"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f4-echo-gate",
      name: "回燃门",
      kind: "story",
      regionId: "f4-storm-core",
      anchor: anchor("floor-4-treasure", 0.5, 0.46, "south", 8, 7),
      assetKey: "shared.setpiece.echo-gate",
      fallback: "ember-echo-gate",
      interaction: "返回第一层的一段残响",
      stateKeys: ["absent", "sealed", "open"],
      minimapIcon: "secret",
    }),
    landmark({
      id: "f4-echo-registry",
      name: "残响登记台",
      kind: "story",
      regionId: "f4-storm-core",
      anchor: anchor("floor-4-treasure", 0.24, 0.48, "east", 3, 3),
      assetKey: "shared.setpiece.echo-registry",
      fallback: "echo-water-wheel",
      interaction: "对照第一层水轮与被反复调用的恢复印",
      stateKeys: ["sealed", "read"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f4-echo-ember",
      name: "无温余烬",
      kind: "story",
      regionId: "f4-storm-core",
      anchor: anchor("floor-4-treasure", 0.54, 0.56, "north", 3, 3),
      assetKey: "shared.setpiece.echo-ember",
      fallback: "cold-ember",
      interaction: "确认被保存的是恢复权限，而不是新的篝火",
      stateKeys: ["cold", "remembering"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f4-echo-null-bed",
      name: "NULL 床位残影",
      kind: "story",
      regionId: "f4-storm-core",
      anchor: anchor("floor-4-treasure", 0.68, 0.62, "north", 3, 3),
      assetKey: "shared.setpiece.echo-null-bed",
      fallback: "echo-null-bed",
      interaction: "核对缺失关联与记录不存在的区别",
      stateKeys: ["remembered"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f4-echo-return",
      name: "依赖返回门",
      kind: "story",
      regionId: "f4-storm-core",
      anchor: anchor("floor-4-treasure", 0.78, 0.48, "west", 3, 3),
      assetKey: "shared.setpiece.echo-return",
      fallback: "echo-return-door",
      interaction: "返回第四层当前进度，不改写第一层真实历史",
      stateKeys: ["open"],
      minimapIcon: "return",
    }),
    landmark({
      id: "f4-sql-seal",
      name: "递归炉印",
      kind: "sql-seal",
      regionId: "f4-storm-core",
      anchor: anchor("floor-4-lesson-6", 0.18, 0.56, "east", 3, 4),
      assetKey: "shared.setpiece.execution-ring",
      fallback: "query-seal",
      interaction: "用 CTE 审计提前解开执行环侧门",
      stateKeys: ["sealed", "decoded"],
      minimapIcon: "query",
    }),
    landmark({
      id: "f4-elemental-throne",
      name: "未完成命令执行环",
      kind: "boss-arena",
      regionId: "f4-storm-core",
      anchor: anchor("floor-4-lesson-6", 0.5, 0.4, "north", 9, 8),
      assetKey: "shared.setpiece.execution-ring",
      fallback: "execution-ring",
      interaction: "追溯未完成命令的完整依赖链",
      stateKeys: ["open-transaction", "audited"],
      minimapIcon: "boss",
    }),
    landmark({
      id: "f4-ascent",
      name: "垂直升炉",
      kind: "transit",
      regionId: "f4-storm-core",
      anchor: anchor("floor-4-lesson-6", 0.82, 0.72, "east", 4, 4),
      assetKey: "shared.setpiece.ascent-furnace",
      fallback: "ascent-furnace",
      interaction: "穿过云层前往黑铁外城",
      stateKeys: ["locked", "active"],
      minimapIcon: "ascent",
    }),
  ],
  npcPlacements: [{
    id: "npc-scribe-f4",
    name: "抄写员",
    role: "把三处事故抄在同一张依赖图上的同行者",
    regionId: "f4-fire-forge",
    anchor: anchor("floor-4-entry", 0.48, 0.4, "south", 2, 2),
    assetKey: "shared.actor.scribe",
    alwaysShowName: true,
  }],
  hiddenAreas: [{
    id: "f4-hidden-ember-echo",
    title: "回燃残响",
    roomNodeId: "floor-4-treasure",
    gateId: "gate:floor-4-treasure",
    landmarkId: "f4-echo-gate",
    requiredLessonIds: ["f4-scalar", "f4-in", "f4-exists"],
    requiredMonsterIds: [44],
    rewardArmorId: "ember-echo-robe",
    sealedPrompt: "E  调查没有温度的余烬轮廓",
    sealedMessage: "门内重复着第一层的火光，但依赖链仍被 ID #044 截断。完成前三种子查询并击败它。",
    openPrompt: "E  进入回燃残响",
    openedMessage: "回燃门展开。门后不是完整的第一层，而是一间被升炉保存下来的余烬登记厅残响。",
    discoveryEventId: "f4-story-ember-echo",
  }],
  storyEvents: [
    {
      id: "f4-story-one-command",
      title: "同一次命令",
      trigger: "floor-entered",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "music-state", state: "f4-low-brass-pulse" },
        { type: "camera-focus", landmarkId: "f4-source-core" },
        { type: "dialogue", speaker: "抄写员", lines: ["火、冰、雷看起来像三场灾难。", "先别分开处理。它们都在等待同一个内层结果。"] },
      ],
      completionFact: "story:f4:entry-seen",
    },
    {
      id: "f4-story-forge-lord",
      title: "霜炉主倒下",
      trigger: "monster:44:defeated",
      repeat: "once",
      priority: 95,
      actions: [
        { type: "camera-focus", landmarkId: "f4-forge-lord" },
        { type: "world-effect", effect: "f4-echo-gate-visible" },
        { type: "dialogue", speaker: "抄写员", lines: ["它守的不是通往上层的路。", "它守着一段被炉心反复调用的第一层记录。"] },
      ],
      completionFact: "story:f4:forge-lord",
    },
    {
      id: "f4-story-ember-echo",
      title: "火记得你，第二次",
      trigger: "gate:floor-4-treasure:opened",
      repeat: "once",
      priority: 96,
      actions: [
        { type: "camera-focus", landmarkId: "f4-echo-gate" },
        { type: "world-effect", effect: "f4-echo-room-open" },
        { type: "dialogue", speaker: "抄写员", lines: ["这里复制了第一层的墙和火，却没有复制那时的你。", "只有恢复权限穿过四层，仍然有效。"] },
      ],
      completionFact: "story:f4:ember-echo",
    },
    {
      id: "f4-story-cipher",
      title: "递归炉印被共同依赖解开",
      trigger: "gate:floor-4-lesson-6:opened",
      repeat: "once",
      priority: 88,
      actions: [
        { type: "camera-focus", landmarkId: "f4-sql-seal" },
        { type: "world-effect", effect: "f4-cipher-decoded" },
        { type: "banner", text: "共同依赖校验通过；执行环侧门永久开启" },
      ],
      completionFact: "story:f4:cipher",
    },
    {
      id: "f4-story-open-transaction",
      title: "数百年没有结束的命令",
      trigger: "monster:39:defeated",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "camera-focus", landmarkId: "f4-elemental-throne" },
        { type: "evidence", evidenceId: "lost-name:f4:unfinished-state" },
        { type: "dialogue", speaker: "抄写员", lines: ["状态不是失败，而是 OPEN。", "王城没有完成这条命令，也不肯把它回滚。"] },
      ],
      completionFact: "story:f4:completed",
    },
  ],
  environmentRules: [
    { id: "f4-source-identified", when: "f4-scalar:completed", state: "source=identified", visibleResult: "命令源炉显示第一条内层结果" },
    { id: "f4-frost-selected", when: "f4-in:completed", state: "frost_array=selected", visibleResult: "属于同一集合的冰槽被同时照亮" },
    { id: "f4-existence-proved", when: "f4-exists:completed", state: "storm_records=proved", visibleResult: "只有真实存在装备记录的雷晶继续导电" },
    { id: "f4-correlations-linked", when: "f4-correlated:completed", state: "pipes=correlated", visibleResult: "每条外层管线连回自己的内层读数" },
    { id: "f4-cte-named", when: "f4-cte:completed", state: "dependency=named", visibleResult: "三相依赖脊柱获得可复用的命令批次名" },
    { id: "f4-recursive-traced", when: "f4-recursive:completed", state: "dependency=traced", visibleResult: "完整依赖链追溯到未结束的王城更新" },
  ],
  adminPresets: [
    { id: "f4-admin-entry", label: "F4 葬火接收炉", completedLessonIds: [], defeatedMonsterIds: [], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f4-source-core" },
    { id: "f4-admin-forge-lord", label: "F4 中层首领 ID #044", completedLessonIds: ["f4-scalar", "f4-in", "f4-exists"], defeatedMonsterIds: [34, 35, 36], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f4-forge-lord" },
    { id: "f4-admin-echo", label: "F4 回燃残响", completedLessonIds: ["f4-scalar", "f4-in", "f4-exists"], defeatedMonsterIds: [34, 35, 36, 44], openedGateIds: ["gate:floor-4-treasure"], collectedKeyItems: [], focusLandmarkId: "f4-echo-gate" },
    { id: "f4-admin-core", label: "F4 三相依赖脊柱", completedLessonIds: ["f4-scalar", "f4-in", "f4-exists", "f4-correlated", "f4-cte"], defeatedMonsterIds: [34, 35, 36, 37, 38, 44], openedGateIds: ["shortcut:4:return"], collectedKeyItems: ["shortcut-key:4"], focusLandmarkId: "f4-dependency-spine" },
    { id: "f4-admin-complete", label: "F4 垂直升炉", completedLessonIds: ["f4-scalar", "f4-in", "f4-exists", "f4-correlated", "f4-cte", "f4-recursive"], defeatedMonsterIds: [34, 35, 36, 37, 38, 39, 44], openedGateIds: ["shortcut:4:return"], collectedKeyItems: ["floor-key:4"], focusLandmarkId: "f4-ascent" },
  ],
};
