/** 第八层固定地标、隐藏房、故事触发和终局前世界变化配置。 */
import type {
  FloorAnchorDefinition,
  FloorExperienceDefinition,
  FloorLandmarkDefinition,
} from "./types";

function anchor(
  roomNodeId: string,
  x: number,
  y: number,
  facing: FloorAnchorDefinition["facing"] = "south",
  width = 3,
  height = 3,
): FloorAnchorDefinition {
  return { roomNodeId, position: { x, y }, facing, clearance: { width, height } };
}

function landmark(
  input: Omit<FloorLandmarkDefinition, "minimapIcon"> & { minimapIcon?: string },
): FloorLandmarkDefinition {
  return { ...input, minimapIcon: input.minimapIcon ?? "landmark" };
}

export const FLOOR_EIGHT_EXPERIENCE: FloorExperienceDefinition = {
  id: "floor-08-black-gold-hall",
  floor: 8,
  title: "黑金迁移高堂",
  subtitle: "你不是某一条旧记录，而是所有未被抹去的历史共同形成的现在",
  version: 1,
  signature: "由七扇前层证据窗与四座本层事故侧翼围绕的中央长阶、只剩一道残晖的高窗、逐步提交但始终保留回滚路径的迁移王座",
  assetPack: {
    id: "floor-08-black-gold-hall-assets",
    version: 1,
    manifestPath: "/assets/floors/08-black-gold-hall/manifest.json",
    assets: [],
  },
  regions: [
    {
      id: "f8-obsidian-history",
      navigationRegion: "front",
      name: "黑曜版本长厅",
      purpose: "重建快照可见行和锁等待环，让旧版本按证据而不是传说出现",
      lessonIds: ["f8-mvcc", "f8-lock"],
      material: "黑曜地面、乳白版本窗、深红锁链与低矮金边",
      ambience: "大提琴独奏、低圆号与缓慢厅堂残响",
      landmarkIds: ["f8-spawn-door", "f8-version-gallery", "f8-deadlock-gate", "f8-front-fire"],
    },
    {
      id: "f8-void-court",
      navigationRegion: "middle",
      name: "四事故证据王庭",
      purpose: "把隔离、建模、复制和分片变成可回访的四个证据翼",
      lessonIds: ["f8-isolation", "f8-modeling", "f8-replication", "f8-sharding"],
      material: "紫黑拱廊、白金证据台、双塔镜面与分片桥",
      ambience: "克制合唱、圆号和逐渐汇聚的弦乐",
      landmarkIds: ["f8-incident-wings", "f8-zero-row-chapel", "f8-rear-fire"],
    },
    {
      id: "f8-data-throne",
      navigationRegion: "rear",
      name: "迁移王座",
      purpose: "汇总前七层证据与本层四类事故结论，完成可验证、可回滚的最终迁移",
      lessonIds: ["f8-security"],
      material: "黑金长阶、残阳高窗、旧版本白石与未熄灭的回滚灯",
      ambience: "完整大编制主题、宽阔铜管与不压迫的合唱",
      landmarkIds: ["f8-migration-dais", "f8-sql-seal", "f8-archivist-throne", "f8-sunset-vista"],
    },
  ],
  landmarks: [
    landmark({
      id: "f8-spawn-door",
      name: "黑金王门",
      kind: "spawn-anchor",
      regionId: "f8-obsidian-history",
      anchor: anchor("floor-8-entry", 0.18, 0.62, "east"),
      assetKey: "shared.setpiece.golden-door",
      fallback: "black-gold-door",
      interaction: null,
      stateKeys: ["always"],
    }),
    landmark({
      id: "f8-version-gallery",
      name: "可见版本长廊",
      kind: "world-machine",
      regionId: "f8-obsidian-history",
      anchor: anchor("floor-8-lesson-1", 0.5, 0.48, "north", 9, 6),
      assetKey: "shared.setpiece.version-gallery",
      fallback: "version-gallery",
      interaction: "按事务 12 的快照重建可见版本",
      stateKeys: ["overlapping", "snapshot"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f8-deadlock-gate",
      name: "双骑等待门",
      kind: "world-machine",
      regionId: "f8-obsidian-history",
      anchor: anchor("floor-8-lesson-2", 0.5, 0.46, "north", 8, 6),
      assetKey: "shared.setpiece.deadlock-gate",
      fallback: "deadlock-cycle-gate",
      interaction: "沿等待图找出互相阻塞的两条边",
      stateKeys: ["locked", "cycle-exposed"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f8-front-fire",
      name: "长厅篝火",
      kind: "campfire",
      regionId: "f8-obsidian-history",
      anchor: anchor("floor-8-rest", 0.52, 0.62),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f8-incident-wings",
      name: "四事故证据台",
      kind: "world-machine",
      regionId: "f8-void-court",
      anchor: anchor("floor-8-event", 0.5, 0.48, "north", 10, 8),
      assetKey: "shared.setpiece.incident-wings",
      fallback: "four-incident-wings",
      interaction: "汇总隔离、建模、复制与分片证据",
      stateKeys: ["dark", "partial", "all-lit"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f8-zero-row-chapel",
      name: "零行礼拜堂",
      kind: "story",
      regionId: "f8-void-court",
      anchor: anchor("floor-8-treasure", 0.5, 0.46, "south", 8, 7),
      assetKey: "shared.setpiece.zero-row-chapel",
      fallback: "zero-row-chapel",
      interaction: "回看第一层的 0 ROWS 与全部七层证据",
      stateKeys: ["sealed", "open"],
      minimapIcon: "secret",
    }),
    landmark({
      id: "f8-rear-fire",
      name: "王庭篝火",
      kind: "campfire",
      regionId: "f8-void-court",
      anchor: anchor("floor-8-event", 0.78, 0.72),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "最后一次休息或八层答案复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f8-migration-dais",
      name: "七步迁移台",
      kind: "world-machine",
      regionId: "f8-data-throne",
      anchor: anchor("floor-8-lesson-6", 0.5, 0.48, "north", 9, 7),
      assetKey: "shared.setpiece.migration-dais",
      fallback: "migration-seven-steps",
      interaction: "检查快照、审计、保留历史、隔离构建、验证、切换与回滚",
      stateKeys: ["collecting", "ready"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f8-sql-seal",
      name: "王令校验密文",
      kind: "sql-seal",
      regionId: "f8-data-throne",
      anchor: anchor("floor-8-lesson-7", 0.18, 0.58, "east", 3, 4),
      assetKey: "shared.setpiece.query-seal",
      fallback: "query-seal",
      interaction: "为每个区域选择健康且最新的副本",
      stateKeys: ["sealed", "decoded"],
      minimapIcon: "query",
    }),
    landmark({
      id: "f8-archivist-throne",
      name: "最终迁移王座",
      kind: "boss-arena",
      regionId: "f8-data-throne",
      anchor: anchor("floor-8-lesson-7", 0.52, 0.36, "north", 10, 9),
      assetKey: "shared.setpiece.archivist-throne",
      fallback: "black-gold-throne",
      interaction: "完成五阶段事故响应与 MIGRATE",
      stateKeys: ["waiting", "migrating", "committed"],
      minimapIcon: "boss",
    }),
    landmark({
      id: "f8-sunset-vista",
      name: "最后一道残晖",
      kind: "vista",
      regionId: "f8-data-throne",
      anchor: anchor("floor-8-lesson-7", 0.84, 0.18, "north", 4, 4),
      assetKey: "shared.setpiece.sunset-window",
      fallback: "sunset-high-window",
      interaction: "查看迁移后的王城",
      stateKeys: ["fading", "new-dawn"],
      minimapIcon: "vista",
    }),
  ],
  npcPlacements: [{
    id: "npc-scribe-f8",
    name: "抄写员",
    role: "不再替玩家作答，只负责核验每项证据来源",
    regionId: "f8-obsidian-history",
    anchor: anchor("floor-8-entry", 0.5, 0.4, "south", 2, 2),
    assetKey: "shared.actor.scribe",
    alwaysShowName: true,
  }],
  hiddenAreas: [{
    id: "f8-hidden-zero-row-chapel",
    title: "零行礼拜堂",
    roomNodeId: "floor-8-treasure",
    gateId: "gate:floor-8-treasure",
    landmarkId: "f8-zero-row-chapel",
    requiredLessonIds: ["f8-mvcc", "f8-lock", "f8-isolation", "f8-modeling"],
    rewardArmorId: "royal-armor",
    sealedPrompt: "E  调查刻着 CURRENT RECORD: 0 ROWS 的黑金侧门",
    sealedMessage: "礼拜堂要求先重建可见版本、找出等待环、识别隔离异常并完成安全建模，才能把第一层的零行证据放回完整历史。",
    openPrompt: "E  打开零行礼拜堂",
    openedMessage: "黑金侧门安静退开。第一层的空白页与七层证据在此并列，中央留下确定获得的王者甲。",
    discoveryEventId: "f8-story-zero-row-chapel",
  }],
  storyEvents: [
    {
      id: "f8-story-unfinished-kingdom",
      title: "仍未结束的王国",
      trigger: "floor-entered",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "music-state", state: "f8-full-hall-theme" },
        { type: "camera-focus", landmarkId: "f8-version-gallery" },
        { type: "dialogue", speaker: "抄写员", lines: ["七层证据都在这里。", "这一次我不替你总结；我只确认每一项从哪里来。"] },
      ],
      completionFact: "story:f8:entry-seen",
    },
    {
      id: "f8-story-zero-row-chapel",
      title: "零行回到完整历史",
      trigger: "gate:floor-8-treasure:opened",
      repeat: "once",
      priority: 94,
      actions: [
        { type: "camera-focus", landmarkId: "f8-zero-row-chapel" },
        { type: "dialogue", speaker: "抄写员", lines: ["第一层的空白页没有变成某一个名字。", "它现在能与所有历史共同解释你为什么仍站在这里。"] },
      ],
      completionFact: "story:f8:chapel",
    },
    {
      id: "f8-story-void-court-open",
      title: "王兽封锁解除",
      trigger: "monster:89:defeated",
      repeat: "once",
      priority: 95,
      actions: [
        { type: "camera-focus", landmarkId: "f8-incident-wings" },
        { type: "world-effect", effect: "f8-void-court-open" },
        { type: "banner", text: "王兽封锁解除 · 迁移王座轴开放" },
        { type: "dialogue", speaker: "抄写员", lines: ["保留事故，不等于永远拒绝修复。", "证据翼继续亮着；现在可以带着它们走向王座。"] },
      ],
      completionFact: "story:f8:void-court-open",
    },
    {
      id: "f8-story-cipher",
      title: "王令校验密文被解开",
      trigger: "gate:floor-8-lesson-7:opened",
      repeat: "once",
      priority: 88,
      actions: [
        { type: "camera-focus", landmarkId: "f8-sql-seal" },
        { type: "world-effect", effect: "f8-cipher-decoded" },
        { type: "banner", text: "健康副本路由校验通过；王座侧门永久开启" },
      ],
      completionFact: "story:f8:cipher",
    },
    {
      id: "f8-story-migrate",
      title: "最后一次迁移",
      trigger: "monster:84:defeated",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "camera-focus", landmarkId: "f8-archivist-throne" },
        { type: "evidence", evidenceId: "lost-name:f8:archivist-verdict" },
        { type: "dialogue", speaker: "最后的档案官", lines: ["你没有删除旧库，也没有让王国永远停在 OPEN。", "写权限交给你；回滚路径仍在。"] },
      ],
      completionFact: "story:f8:completed",
    },
  ],
  environmentRules: [
    { id: "f8-snapshot-visible", when: "f8-mvcc:completed", state: "gallery=snapshot", visibleResult: "事务 12 可见的历史版本在长廊中稳定显形" },
    { id: "f8-cycle-exposed", when: "f8-lock:completed", state: "deadlock=cycle-exposed", visibleResult: "双骑等待环被完整标出" },
    { id: "f8-isolation-wing", when: "f8-isolation:completed", state: "wings=isolation", visibleResult: "幻读事故翼点亮并标注阻止策略" },
    { id: "f8-model-wing", when: "f8-modeling:completed", state: "wings=model", visibleResult: "安全模型翼保留主键、唯一性和零重复证据" },
    { id: "f8-replica-wing", when: "f8-replication:completed", state: "wings=replica", visibleResult: "复制翼显示健康节点与延迟" },
    { id: "f8-shard-ready", when: "f8-sharding:completed", state: "migration=ready", visibleResult: "分片路由审计完成，七步迁移台准备就绪" },
    { id: "f8-migration-committed", when: "f8-security:completed", state: "throne=committed", visibleResult: "新版本接管王城，旧历史和回滚路径仍被保留" },
  ],
  adminPresets: [
    { id: "f8-admin-entry", label: "F8 版本长厅", completedLessonIds: [], defeatedMonsterIds: [], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f8-version-gallery" },
    { id: "f8-admin-chapel", label: "F8 零行礼拜堂", completedLessonIds: ["f8-mvcc", "f8-lock", "f8-isolation", "f8-modeling"], defeatedMonsterIds: [78, 79, 80, 81], openedGateIds: ["gate:floor-8-treasure"], collectedKeyItems: [], focusLandmarkId: "f8-zero-row-chapel" },
    { id: "f8-admin-cipher", label: "F8 王令校验密文", completedLessonIds: ["f8-mvcc", "f8-lock", "f8-isolation", "f8-modeling", "f8-replication", "f8-sharding"], defeatedMonsterIds: [78, 79, 80, 81, 82, 83], openedGateIds: ["gate:floor-8-lesson-7"], collectedKeyItems: [], focusLandmarkId: "f8-sql-seal" },
    { id: "f8-admin-void-court", label: "F8 虚空王庭", completedLessonIds: ["f8-mvcc", "f8-lock", "f8-isolation", "f8-modeling", "f8-replication", "f8-sharding"], defeatedMonsterIds: [78, 79, 80, 81, 82, 83, 89], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f8-incident-wings" },
    { id: "f8-admin-complete", label: "F8 MIGRATE 完成态", completedLessonIds: ["f8-mvcc", "f8-lock", "f8-isolation", "f8-modeling", "f8-replication", "f8-sharding", "f8-security"], defeatedMonsterIds: [78, 79, 80, 81, 82, 83, 84, 89], openedGateIds: [], collectedKeyItems: ["floor-key:8"], focusLandmarkId: "f8-archivist-throne" },
  ],
};
