import type {
  FloorAnchorDefinition,
  FloorExperienceDefinition,
  FloorLandmarkDefinition,
} from "./types";

function anchor(
  roomNodeId: string,
  x: number,
  y: number,
  facing: FloorAnchorDefinition["facing"] = "south",
  width = 3,
  height = 3,
): FloorAnchorDefinition {
  return { roomNodeId, position: { x, y }, facing, clearance: { width, height } };
}

function landmark(
  input: Omit<FloorLandmarkDefinition, "minimapIcon"> & { minimapIcon?: string },
): FloorLandmarkDefinition {
  return { ...input, minimapIcon: input.minimapIcon ?? "landmark" };
}

export const FLOOR_FIVE_EXPERIENCE: FloorExperienceDefinition = {
  id: "floor-05-black-iron-order",
  floor: 5,
  title: "黑铁轮值城",
  subtitle: "事实没有改变，公开它的顺序却能决定谁先被清除",
  version: 1,
  signature: "宽阔双环城墙、可读取的换岗队列、逐段上升的警戒灯与一座按窗口结果转动的军钟",
  assetPack: {
    id: "floor-05-black-iron-order-assets",
    version: 1,
    manifestPath: "/assets/floors/05-black-iron-order/manifest.json",
    assets: [],
  },
  regions: [
    {
      id: "f5-outer-watch",
      name: "黑铁外城",
      purpose: "用 OVER 与 ROW_NUMBER 看见分区、岗次和仍被保留的每一行",
      lessonIds: ["f5-over", "f5-row-number"],
      material: "宽石路、铆钉城墙、低垂战旗与琥珀岗灯",
      ambience: "克制铜管、稳定军鼓与远处换岗钟",
      landmarkIds: ["f5-spawn-bridge", "f5-muster-board", "f5-front-fire"],
    },
    {
      id: "f5-barracks-ring",
      name: "轮值兵营",
      purpose: "用排名和前后行读取并列岗位与巡逻空档",
      lessonIds: ["f5-rank", "f5-lag-lead"],
      material: "黑铁寝台、红色队列线、双标准旗与侧向箭孔",
      ambience: "中提琴脉冲、木质脚步与不尖锐的短号",
      landmarkIds: ["f5-rank-standards", "f5-patrol-chain", "f5-silent-roster", "f5-rear-fire"],
    },
    {
      id: "f5-inner-clock",
      name: "内城军钟",
      purpose: "用窗口范围和分组 Top-N 证明警戒并非不可改变的命运",
      lessonIds: ["f5-frame", "f5-top-n"],
      material: "高耸钟架、金属轨道、层叠警戒窗与黑金吊桥",
      ambience: "低圆号、温和定音鼓与逐渐拉宽的夕阳和声",
      landmarkIds: ["f5-alert-wall", "f5-sql-seal", "f5-command-clock", "f5-ascent"],
    },
  ],
  landmarks: [
    landmark({
      id: "f5-spawn-bridge",
      name: "云上吊桥头",
      kind: "spawn-anchor",
      regionId: "f5-outer-watch",
      anchor: anchor("floor-5-entry", 0.18, 0.6, "east"),
      assetKey: "shared.setpiece.iron-bridge",
      fallback: "black-iron-bridge",
      interaction: null,
      stateKeys: ["always"],
    }),
    landmark({
      id: "f5-muster-board",
      name: "外城分区轮值表",
      kind: "world-machine",
      regionId: "f5-outer-watch",
      anchor: anchor("floor-5-lesson-1", 0.54, 0.46, "north", 7, 5),
      assetKey: "shared.setpiece.roster-board",
      fallback: "window-roster",
      interaction: "读取每个分区仍被保留的守卫明细",
      stateKeys: ["folded", "partitioned", "numbered"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f5-front-fire",
      name: "城墙篝火",
      kind: "campfire",
      regionId: "f5-outer-watch",
      anchor: anchor("floor-5-rest", 0.52, 0.62),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f5-rank-standards",
      name: "并列双旗",
      kind: "world-machine",
      regionId: "f5-barracks-ring",
      anchor: anchor("floor-5-lesson-3", 0.5, 0.45, "west", 7, 6),
      assetKey: "shared.setpiece.rank-standards",
      fallback: "rank-standards",
      interaction: "比较 RANK 与 DENSE_RANK 留下的空档",
      stateKeys: ["single-order", "ties-visible"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f5-patrol-chain",
      name: "前后岗次灯链",
      kind: "world-machine",
      regionId: "f5-barracks-ring",
      anchor: anchor("floor-5-lesson-4", 0.5, 0.5, "north", 8, 5),
      assetKey: "shared.setpiece.patrol-chain",
      fallback: "patrol-light-chain",
      interaction: "读取当前岗次的前一位与后一位",
      stateKeys: ["isolated", "linked"],
      minimapIcon: "route",
    }),
    landmark({
      id: "f5-silent-roster",
      name: "静默名册室",
      kind: "story",
      regionId: "f5-barracks-ring",
      anchor: anchor("floor-5-treasure", 0.5, 0.46, "south", 7, 6),
      assetKey: "shared.setpiece.archive-vault",
      fallback: "silent-roster-room",
      interaction: "读取未被公开的居民顺序",
      stateKeys: ["sealed", "open"],
      minimapIcon: "secret",
    }),
    landmark({
      id: "f5-rear-fire",
      name: "内环篝火",
      kind: "campfire",
      regionId: "f5-barracks-ring",
      anchor: anchor("floor-5-event", 0.72, 0.7),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或本层答案复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f5-alert-wall",
      name: "累计警戒墙",
      kind: "world-machine",
      regionId: "f5-inner-clock",
      anchor: anchor("floor-5-lesson-5", 0.5, 0.48, "north", 8, 6),
      assetKey: "shared.setpiece.alert-wall",
      fallback: "running-alert-wall",
      interaction: "查看从第一岗累计到当前岗的警戒值",
      stateKeys: ["opaque", "framed"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f5-sql-seal",
      name: "轮值密文门",
      kind: "sql-seal",
      regionId: "f5-inner-clock",
      anchor: anchor("floor-5-lesson-6", 0.18, 0.56, "east", 3, 4),
      assetKey: "shared.setpiece.query-seal",
      fallback: "query-seal",
      interaction: "用窗口军阵提前解开内城侧门",
      stateKeys: ["sealed", "decoded"],
      minimapIcon: "query",
    }),
    landmark({
      id: "f5-command-clock",
      name: "黑铁军钟",
      kind: "boss-arena",
      regionId: "f5-inner-clock",
      anchor: anchor("floor-5-lesson-6", 0.52, 0.4, "north", 9, 8),
      assetKey: "shared.setpiece.command-clock",
      fallback: "command-clock",
      interaction: "挑战 ID #050 并重排城防",
      stateKeys: ["enforcing", "reordered"],
      minimapIcon: "boss",
    }),
    landmark({
      id: "f5-ascent",
      name: "黑铁上行桥",
      kind: "transit",
      regionId: "f5-inner-clock",
      anchor: anchor("floor-5-lesson-6", 0.84, 0.72, "east", 4, 4),
      assetKey: "shared.setpiece.iron-bridge",
      fallback: "black-iron-bridge",
      interaction: "前往龙脊王室工坊",
      stateKeys: ["raised", "lowered"],
      minimapIcon: "ascent",
    }),
  ],
  npcPlacements: [{
    id: "npc-scribe-f5",
    name: "抄写员",
    role: "第一次质疑证据公开顺序的同行者",
    regionId: "f5-outer-watch",
    anchor: anchor("floor-5-entry", 0.5, 0.4, "south", 2, 2),
    assetKey: "shared.actor.scribe",
    alwaysShowName: true,
  }],
  hiddenAreas: [{
    id: "f5-hidden-silent-roster",
    title: "静默名册室",
    roomNodeId: "floor-5-treasure",
    gateId: "gate:floor-5-treasure",
    landmarkId: "f5-silent-roster",
    requiredLessonIds: ["f5-over", "f5-row-number", "f5-rank"],
    rewardArmorId: "iron-armor",
    sealedPrompt: "E  调查没有编号的兵营铁门",
    sealedMessage: "门锁要求先保留全部明细、建立稳定岗次，再正确处理并列。完成 OVER、ROW_NUMBER 与 RANK。",
    openPrompt: "E  打开静默名册室",
    openedMessage: "铁门向内折叠。这里保存着没有被公开的居民轮值表，以及一套确定获得的黑铁甲。",
    discoveryEventId: "f5-story-silent-roster",
  }],
  storyEvents: [
    {
      id: "f5-story-ordered-people",
      title: "被排序的人",
      trigger: "floor-entered",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "music-state", state: "f5-measured-brass" },
        { type: "camera-focus", landmarkId: "f5-muster-board" },
        { type: "dialogue", speaker: "抄写员", lines: ["外城没有删除任何一行。", "它只是决定谁先被看见、谁先被带走。"] },
      ],
      completionFact: "story:f5:entry-seen",
    },
    {
      id: "f5-story-silent-roster",
      title: "没有公开的顺序",
      trigger: "gate:floor-5-treasure:opened",
      repeat: "once",
      priority: 92,
      actions: [
        { type: "camera-focus", landmarkId: "f5-silent-roster" },
        { type: "dialogue", speaker: "抄写员", lines: ["我在第四层认出了档案官的签名。", "我没有立刻告诉你，因为公开顺序也会伤人。"] },
      ],
      completionFact: "story:f5:silent-roster",
    },
    {
      id: "f5-story-cipher",
      title: "军钟侧门被查询解开",
      trigger: "gate:floor-5-lesson-6:opened",
      repeat: "once",
      priority: 88,
      actions: [
        { type: "camera-focus", landmarkId: "f5-sql-seal" },
        { type: "world-effect", effect: "f5-cipher-decoded" },
        { type: "banner", text: "窗口军阵完成校验；内城侧门永久开启" },
      ],
      completionFact: "story:f5:cipher",
    },
    {
      id: "f5-story-clock-reordered",
      title: "唯一名次被撤销",
      trigger: "monster:50:defeated",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "camera-focus", landmarkId: "f5-command-clock" },
        { type: "evidence", evidenceId: "lost-name:f5:overlap" },
        { type: "dialogue", speaker: "抄写员", lines: ["事实没有改变。", "改变的是王城再也不能用一个名次覆盖其余历史。"] },
      ],
      completionFact: "story:f5:completed",
    },
  ],
  environmentRules: [
    { id: "f5-partitions-visible", when: "f5-over:completed", state: "roster=partitioned", visibleResult: "分区轮值表保留每名守卫的独立行" },
    { id: "f5-positions-numbered", when: "f5-row-number:completed", state: "roster=numbered", visibleResult: "外城岗次获得稳定编号" },
    { id: "f5-ties-visible", when: "f5-rank:completed", state: "standards=ties-visible", visibleResult: "并列双旗同时升起" },
    { id: "f5-patrol-linked", when: "f5-lag-lead:completed", state: "patrol=linked", visibleResult: "前后岗次灯链形成可见巡逻空档" },
    { id: "f5-alert-framed", when: "f5-frame:completed", state: "alert=framed", visibleResult: "累计警戒墙显示明确窗口边界" },
    { id: "f5-clock-reordered", when: "f5-top-n:completed", state: "clock=reordered", visibleResult: "军钟停止宣告唯一第一名，吊桥落下" },
  ],
  adminPresets: [
    { id: "f5-admin-entry", label: "F5 外城轮值表", completedLessonIds: [], defeatedMonsterIds: [], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f5-muster-board" },
    { id: "f5-admin-roster", label: "F5 静默名册室", completedLessonIds: ["f5-over", "f5-row-number", "f5-rank"], defeatedMonsterIds: [45, 46, 47], openedGateIds: ["gate:floor-5-treasure"], collectedKeyItems: [], focusLandmarkId: "f5-silent-roster" },
    { id: "f5-admin-cipher", label: "F5 轮值密文门", completedLessonIds: ["f5-over", "f5-row-number", "f5-rank"], defeatedMonsterIds: [45, 46, 47], openedGateIds: ["gate:floor-5-lesson-6"], collectedKeyItems: [], focusLandmarkId: "f5-sql-seal" },
    { id: "f5-admin-complete", label: "F5 黑铁军钟", completedLessonIds: ["f5-over", "f5-row-number", "f5-rank", "f5-lag-lead", "f5-frame", "f5-top-n"], defeatedMonsterIds: [45, 46, 47, 48, 49, 50], openedGateIds: ["shortcut:5:return"], collectedKeyItems: ["floor-key:5"], focusLandmarkId: "f5-command-clock" },
  ],
};
