/**
 * 第六层世界体验、地标和作者化楼层布局真源。
 *
 * 本模块只登记静态世界定义；公共算法由父级服务向下提供，避免楼层拆分后复制规则。
 */
import type {
  FloorAnchorDefinition,
  FloorExperienceDefinition,
  FloorLandmarkDefinition,
} from "../../types";

function anchor(
  roomNodeId: string,
  x: number,
  y: number,
  facing: FloorAnchorDefinition["facing"] = "south",
  width = 3,
  height = 3,
): FloorAnchorDefinition {
  return { roomNodeId, position: { x, y }, facing, clearance: { width, height } };
}

function landmark(
  input: Omit<FloorLandmarkDefinition, "minimapIcon"> & { minimapIcon?: string },
): FloorLandmarkDefinition {
  return { ...input, minimapIcon: input.minimapIcon ?? "landmark" };
}

export const FLOOR_SIX_EXPERIENCE: FloorExperienceDefinition = {
  id: "floor-06-dragon-ridge-workshop",
  floor: 6,
  title: "龙脊回滚工坊",
  subtitle: "能改变记录的人，首先要证明自己知道怎样撤销",
  version: 1,
  signature: "岩浆孵化台、原始与候选状态并排的龙晶洞窟、沿山脊分布的保存点和一座拒绝盲目提交的古龙巢",
  assetPack: {
    id: "floor-06-dragon-ridge-workshop-assets",
    version: 1,
    manifestPath: "/assets/floors/06-dragon-ridge-workshop/manifest.json",
    assets: [],
  },
  regions: [
    {
      id: "f6-magma-workshop",
      navigationRegion: "front",
      name: "岩浆孵化工坊",
      purpose: "在一次性副本里练习明确写入和定向更新",
      lessonIds: ["f6-insert", "f6-update"],
      material: "玄武岩平台、铜制孵化槽、温和熔光与安全隔离线",
      ambience: "低弦脉冲、大提琴和缓慢炉息",
      landmarkIds: ["f6-spawn-minecart", "f6-sandbox-incubator", "f6-front-fire"],
    },
    {
      id: "f6-crystal-repair",
      navigationRegion: "middle",
      name: "龙晶修复洞",
      purpose: "让删除、约束冲突和失败结果都在候选状态中可见",
      lessonIds: ["f6-delete", "f6-constraint"],
      material: "蓝绿龙晶、白色约束刻线、碎鳞回收槽与双状态观察窗",
      ambience: "低木管、晶体泛音与克制金属敲击",
      landmarkIds: ["f6-cleanup-sluice", "f6-constraint-door", "f6-uncommitted-rookery", "f6-rear-fire"],
    },
    {
      id: "f6-rollback-summit",
      navigationRegion: "rear",
      name: "回滚山巅",
      purpose: "用事务、ROLLBACK 与 SAVEPOINT 证明安全改变不是提交或撤销的二选一",
      lessonIds: ["f6-transaction", "f6-savepoint"],
      material: "雪线黑石、龙骨拱门、红蓝双轨和王室升降台",
      ambience: "圆号、大提琴与逐渐开阔的庄严长音",
      landmarkIds: ["f6-state-bridge", "f6-savepoint-altar", "f6-sql-seal", "f6-dragon-throne", "f6-ascent"],
    },
  ],
  landmarks: [
    landmark({
      id: "f6-spawn-minecart",
      name: "龙脊矿车站",
      kind: "spawn-anchor",
      regionId: "f6-magma-workshop",
      anchor: anchor("floor-6-entry", 0.18, 0.62, "east"),
      assetKey: "shared.setpiece.minecart",
      fallback: "ridge-minecart",
      interaction: null,
      stateKeys: ["always"],
    }),
    landmark({
      id: "f6-sandbox-incubator",
      name: "一次性孵化副本",
      kind: "world-machine",
      regionId: "f6-magma-workshop",
      anchor: anchor("floor-6-lesson-1", 0.52, 0.48, "north", 8, 6),
      assetKey: "shared.setpiece.incubator",
      fallback: "sandbox-incubator",
      interaction: "比较写入前后的 repair_queue",
      stateKeys: ["pristine", "written", "updated"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f6-front-fire",
      name: "龙息篝火",
      kind: "campfire",
      regionId: "f6-magma-workshop",
      anchor: anchor("floor-6-rest", 0.52, 0.62),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f6-cleanup-sluice",
      name: "重复鳞片清理槽",
      kind: "world-machine",
      regionId: "f6-crystal-repair",
      anchor: anchor("floor-6-lesson-3", 0.5, 0.48, "west", 7, 5),
      assetKey: "shared.setpiece.cleanup-sluice",
      fallback: "cleanup-sluice",
      interaction: "只删除明确锁定的重复记录",
      stateKeys: ["duplicated", "targeted"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f6-constraint-door",
      name: "龙晶约束门",
      kind: "world-machine",
      regionId: "f6-crystal-repair",
      anchor: anchor("floor-6-lesson-4", 0.5, 0.46, "north", 7, 6),
      assetKey: "shared.setpiece.constraint-door",
      fallback: "constraint-crystal-door",
      interaction: "观察无效候选怎样被约束拒绝",
      stateKeys: ["testing", "protected"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f6-uncommitted-rookery",
      name: "未提交育龙室",
      kind: "story",
      regionId: "f6-crystal-repair",
      anchor: anchor("floor-6-treasure", 0.5, 0.45, "south", 7, 6),
      assetKey: "shared.setpiece.rookery",
      fallback: "uncommitted-rookery",
      interaction: "读取被回滚却没有被遗忘的孵化记录",
      stateKeys: ["sealed", "open"],
      minimapIcon: "secret",
    }),
    landmark({
      id: "f6-rear-fire",
      name: "修复台篝火",
      kind: "campfire",
      regionId: "f6-crystal-repair",
      anchor: anchor("floor-6-event", 0.72, 0.68),
      assetKey: "shared.setpiece.campfire",
      fallback: "animated-campfire",
      interaction: "休息或本层答案复盘",
      stateKeys: ["unlit", "active"],
      minimapIcon: "campfire",
    }),
    landmark({
      id: "f6-state-bridge",
      name: "原始／候选双轨桥",
      kind: "world-machine",
      regionId: "f6-rollback-summit",
      anchor: anchor("floor-6-lesson-5", 0.5, 0.48, "north", 8, 6),
      assetKey: "shared.setpiece.state-bridge",
      fallback: "original-candidate-bridge",
      interaction: "比较事务开始前、修改后与回滚后的状态",
      stateKeys: ["candidate-damaged", "rolled-back"],
      minimapIcon: "route",
    }),
    landmark({
      id: "f6-savepoint-altar",
      name: "保存点祭台",
      kind: "world-machine",
      regionId: "f6-rollback-summit",
      anchor: anchor("floor-6-lesson-6", 0.5, 0.5, "north", 8, 7),
      assetKey: "shared.setpiece.savepoint-altar",
      fallback: "savepoint-altar",
      interaction: "局部撤销错误步骤并保留已验证部分",
      stateKeys: ["unverified", "validated"],
      minimapIcon: "evidence",
    }),
    landmark({
      id: "f6-sql-seal",
      name: "逆鳞密文门",
      kind: "sql-seal",
      regionId: "f6-rollback-summit",
      anchor: anchor("floor-6-lesson-6", 0.18, 0.58, "east", 3, 4),
      assetKey: "shared.setpiece.query-seal",
      fallback: "query-seal",
      interaction: "用只读分区预演提前解开龙巢侧门",
      stateKeys: ["sealed", "decoded"],
      minimapIcon: "query",
    }),
    landmark({
      id: "f6-dragon-throne",
      name: "事务提交巢",
      kind: "boss-arena",
      regionId: "f6-rollback-summit",
      anchor: anchor("floor-6-lesson-6", 0.52, 0.38, "north", 9, 8),
      assetKey: "shared.setpiece.dragon-throne",
      fallback: "dragon-commit-throne",
      interaction: "挑战 ID #061 并验证局部回滚",
      stateKeys: ["forcing-commit", "validated"],
      minimapIcon: "boss",
    }),
    landmark({
      id: "f6-ascent",
      name: "王室升降台",
      kind: "transit",
      regionId: "f6-rollback-summit",
      anchor: anchor("floor-6-lesson-6", 0.84, 0.72, "east", 4, 4),
      assetKey: "shared.setpiece.royal-lift",
      fallback: "royal-lift",
      interaction: "前往残照索引王苑",
      stateKeys: ["locked", "active"],
      minimapIcon: "ascent",
    }),
  ],
  npcPlacements: [{
    id: "npc-scribe-f6",
    name: "抄写员",
    role: "主张完全回滚、随后接受隔离验证的同行者",
    regionId: "f6-magma-workshop",
    anchor: anchor("floor-6-entry", 0.5, 0.4, "south", 2, 2),
    assetKey: "shared.actor.scribe",
    alwaysShowName: true,
  }],
  hiddenAreas: [{
    id: "f6-hidden-uncommitted-rookery",
    title: "未提交育龙室",
    roomNodeId: "floor-6-treasure",
    gateId: "gate:floor-6-treasure",
    landmarkId: "f6-uncommitted-rookery",
    requiredLessonIds: ["f6-insert", "f6-update", "f6-delete"],
    rewardArmorId: "dragon-armor",
    sealedPrompt: "E  调查写着 ROLLED BACK 的育龙室",
    sealedMessage: "育龙室要求先完成一次明确写入、一次定向更新和一次精确删除，证明改变不会越过目标边界。",
    openPrompt: "E  打开未提交育龙室",
    openedMessage: "育龙室恢复照明。被回滚的孵化记录仍保存审计痕迹，中央鳞架留有一套确定获得的龙鳞甲。",
    discoveryEventId: "f6-story-rookery",
  }],
  storyEvents: [
    {
      id: "f6-story-change-can-return",
      title: "可以撤销的工坊",
      trigger: "floor-entered",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "music-state", state: "f6-cello-workshop" },
        { type: "camera-focus", landmarkId: "f6-sandbox-incubator" },
        { type: "dialogue", speaker: "抄写员", lines: ["我曾以为最安全的答案是全部回滚。", "这里要求我们先改变，再证明自己能安全回来。"] },
      ],
      completionFact: "story:f6:entry-seen",
    },
    {
      id: "f6-story-rookery",
      title: "撤销不等于遗忘",
      trigger: "gate:floor-6-treasure:opened",
      repeat: "once",
      priority: 92,
      actions: [
        { type: "camera-focus", landmarkId: "f6-uncommitted-rookery" },
        { type: "dialogue", speaker: "抄写员", lines: ["这些生命没有被提交，却留下了完整的审计轨迹。", "回滚保护了现在，也不能假装候选从未存在。"] },
      ],
      completionFact: "story:f6:rookery",
    },
    {
      id: "f6-story-crystal-cavern-open",
      title: "晶洞守卫解除",
      trigger: "monster:66:defeated",
      repeat: "once",
      priority: 95,
      actions: [
        { type: "camera-focus", landmarkId: "f6-constraint-door" },
        { type: "world-effect", effect: "f6-crystal-cavern-open" },
        { type: "banner", text: "晶洞守卫解除 · 保存点后区开放" },
        { type: "dialogue", speaker: "抄写员", lines: ["一条候选被拒绝，不等于所有修改都该回滚。", "约束守住边界，通往保存点的路已经开放。"] },
      ],
      completionFact: "story:f6:crystal-cavern-open",
    },
    {
      id: "f6-story-cipher",
      title: "逆鳞密文被只读预演解开",
      trigger: "gate:floor-6-lesson-6:opened",
      repeat: "once",
      priority: 88,
      actions: [
        { type: "camera-focus", landmarkId: "f6-sql-seal" },
        { type: "world-effect", effect: "f6-cipher-decoded" },
        { type: "banner", text: "只读预演通过；龙巢侧门永久开启" },
      ],
      completionFact: "story:f6:cipher",
    },
    {
      id: "f6-story-safe-change",
      title: "第三条路",
      trigger: "monster:61:defeated",
      repeat: "once",
      priority: 100,
      actions: [
        { type: "camera-focus", landmarkId: "f6-dragon-throne" },
        { type: "evidence", evidenceId: "lost-name:f6:write-carrier" },
        { type: "dialogue", speaker: "抄写员", lines: ["不是盲目提交，也不是抹掉所有候选。", "先隔离、再验证、保留回滚——这是一条真正能前进的路。"] },
      ],
      completionFact: "story:f6:completed",
    },
  ],
  environmentRules: [
    { id: "f6-row-inserted", when: "f6-insert:completed", state: "sandbox=written", visibleResult: "孵化副本出现一条字段完整的新记录" },
    { id: "f6-row-updated", when: "f6-update:completed", state: "sandbox=updated", visibleResult: "只有被 WHERE 锁定的鳞甲状态改变" },
    { id: "f6-duplicate-targeted", when: "f6-delete:completed", state: "cleanup=targeted", visibleResult: "重复鳞片中只有指定 id 被移除" },
    { id: "f6-constraint-protected", when: "f6-constraint:completed", state: "constraint=protected", visibleResult: "无效候选撞上约束后没有污染表状态" },
    { id: "f6-transaction-rolled-back", when: "f6-transaction:completed", state: "bridge=rolled-back", visibleResult: "损坏的候选桥回到原始状态" },
    { id: "f6-savepoint-validated", when: "f6-savepoint:completed", state: "savepoint=validated", visibleResult: "保存点只撤销错误步骤并保留已验证修改" },
  ],
  adminPresets: [
    { id: "f6-admin-entry", label: "F6 孵化副本", completedLessonIds: [], defeatedMonsterIds: [], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f6-sandbox-incubator" },
    { id: "f6-admin-rookery", label: "F6 未提交育龙室", completedLessonIds: ["f6-insert", "f6-update", "f6-delete"], defeatedMonsterIds: [56, 57, 58], openedGateIds: ["gate:floor-6-treasure"], collectedKeyItems: [], focusLandmarkId: "f6-uncommitted-rookery" },
    { id: "f6-admin-cipher", label: "F6 逆鳞密文门", completedLessonIds: ["f6-insert", "f6-update", "f6-delete", "f6-constraint"], defeatedMonsterIds: [56, 57, 58, 59], openedGateIds: ["gate:floor-6-lesson-6"], collectedKeyItems: [], focusLandmarkId: "f6-sql-seal" },
    { id: "f6-admin-crystal-cavern", label: "F6 龙晶修复洞", completedLessonIds: ["f6-insert", "f6-update", "f6-delete", "f6-constraint"], defeatedMonsterIds: [56, 57, 58, 59, 66], openedGateIds: [], collectedKeyItems: [], focusLandmarkId: "f6-constraint-door" },
    { id: "f6-admin-complete", label: "F6 事务提交巢", completedLessonIds: ["f6-insert", "f6-update", "f6-delete", "f6-constraint", "f6-transaction", "f6-savepoint"], defeatedMonsterIds: [56, 57, 58, 59, 60, 61, 66], openedGateIds: ["shortcut:6:return"], collectedKeyItems: ["floor-key:6"], focusLandmarkId: "f6-dragon-throne" },
  ],
};
