import type {
  LessonDefinition,
  Monster,
  Weapon,
} from "../../domain/shared/types";

export const ROYAL_SWORD: Weapon = {
  id: "royal-sword",
  name: "王者剑",
  damage: 28,
  heatReduction: 3,
  description: "黑曜数据王座的最终武器。正确事故查询造成 28 点伤害，并减少 3 点查询热量。",
};

export const FLOOR_EIGHT_MONSTERS: readonly Monster[] = [
  {
    floor: 8, id: 78, lessonId: "f8-mvcc", roomId: 91, name: "幽魂",
    species: "version_ghost", kind: "lich", x: 1, y: 1, hp: 24, maxHp: 24,
    armor: 1, damage: 5, attackName: "旧版侵蚀", status: "reading",
    weakness: "snapshot", masterId: 84, isBoss: false, rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 8, id: 79, lessonId: "f8-lock", roomId: 92, name: "锁骑",
    species: "lock_knight", kind: "dark-knight", x: 1, y: 1, hp: 28, maxHp: 28,
    armor: 1, damage: 5, attackName: "锁链", status: "waiting",
    weakness: "deadlock", masterId: 84, isBoss: false, rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 8, id: 80, lessonId: "f8-isolation", roomId: 93, name: "巫妖",
    species: "isolation_lich", kind: "lich", x: 1, y: 1, hp: 28, maxHp: 28,
    armor: 1, damage: 6, attackName: "幻读", status: "shifting",
    weakness: "serializable", masterId: 84, isBoss: false, rank: "normal",
    encounterType: "curriculum",
  },
  {
    floor: 8, id: 81, lessonId: "f8-modeling", roomId: 94, name: "魔像",
    species: "schema_golem", kind: "obsidian-golem", x: 1, y: 1, hp: 28, maxHp: 28,
    armor: 2, damage: 5, attackName: "重复重压", status: "duplicating",
    weakness: "normalization", masterId: 84, isBoss: false, rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 8, id: 82, lessonId: "f8-replication", roomId: 95, name: "双子",
    species: "replica_twins", kind: "replica-twin", x: 1, y: 1, hp: 28, maxHp: 28,
    armor: 2, damage: 6, attackName: "延迟回声", status: "replicating",
    weakness: "lag", masterId: 84, isBoss: false, rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 8, id: 83, lessonId: "f8-sharding", roomId: 96, name: "巨兽",
    species: "shard_beast", kind: "shard-beast", x: 1, y: 1, hp: 28, maxHp: 28,
    armor: 2, damage: 6, attackName: "分片冲撞", status: "routing",
    weakness: "balance", masterId: 84, isBoss: false, rank: "elite",
    encounterType: "curriculum",
  },
  {
    floor: 8, id: 84, lessonId: "f8-security", roomId: 97, name: "档案王",
    species: "data_demon_king", kind: "demon-king", x: 1, y: 1, hp: 140, maxHp: 140,
    armor: 3, damage: 7, attackName: "数据终焉", status: "ruling",
    weakness: "evidence", masterId: null, isBoss: true, rank: "boss",
    encounterType: "curriculum",
  },
] as const;

export const INCIDENT_SCHEMA = [
  "tx_versions(row_id, version_id, value, created_tx, expired_tx)",
  "lock_waits(waiter_tx, blocker_tx, resource)",
  "isolation_cases(id, phenomenon, first_count, second_count, prevented_by)",
  "schema_choices(id, model, has_primary_key, has_unique_email, duplicate_groups, score)",
  "replica_status(node, region, lag_ms, healthy, role)",
  "shard_routes(account_id, shard_id, region, route_ok)",
  "security_cases(id, method, parameterized, least_privilege, allowed)",
  "这些是固定的教学事故记录；查询结果用于推理，不声称 SQLite 本身实现分布式复制、分片或 MVCC 行版本。",
];

export const FLOOR_EIGHT_LESSON_DEFINITIONS: readonly LessonDefinition[] = [
  {
    id: "f8-mvcc",
    concept: "MVCC 可见性",
    title: "版本厅 · 快照可见行",
    intro: "教学表显式记录创建与过期事务。用事务号 12 重建快照可见版本，不把夹具冒充 SQLite 内部实现。",
    schema: INCIDENT_SCHEMA,
    primaryMonsterId: 78,
    stages: [{
      id: "f8-mvcc-visible",
      objective: "查询事务 12 可见的 row_id、value：created_tx <= 12，且 expired_tx 为空或大于 12；按 row_id。",
      queryTemplate: "",
      answerSql: "SELECT row_id, value FROM tx_versions WHERE created_tx <= 12 AND (expired_tx IS NULL OR expired_tx > 12) ORDER BY row_id;",
      hints: [
        "返回 row_id、value。",
        "创建事务必须不晚于 12。",
        "还要保留未过期，或在 12 之后才过期的版本。",
        "最后按 row_id 排序。",
        "完整写法：SELECT row_id, value FROM tx_versions WHERE created_tx <= 12 AND (expired_tx IS NULL OR expired_tx > 12) ORDER BY row_id;",
      ],
      locks: ["WHERE", "AND", "IS NULL", "ORDER BY"],
      requiredFeatures: ["where", "and", "is-null", "order-by"],
      attackTargetIds: [78],
    }],
  },
  {
    id: "f8-lock",
    concept: "等待图与死锁",
    title: "双骑门 · 找出互相等待",
    intro: "死锁是等待图中的环。本题从锁等待记录自连接，找出两条方向相反的边。",
    schema: INCIDENT_SCHEMA,
    primaryMonsterId: 79,
    stages: [{
      id: "f8-lock-cycle",
      objective: "自连接 lock_waits，找出互相等待的一对 waiter_tx、blocker_tx，只保留 waiter_tx 较小的一行。",
      queryTemplate: "",
      answerSql: "SELECT a.waiter_tx, a.blocker_tx FROM lock_waits a INNER JOIN lock_waits b ON a.waiter_tx = b.blocker_tx AND a.blocker_tx = b.waiter_tx WHERE a.waiter_tx < a.blocker_tx;",
      hints: [
        "同一张表使用 a、b 两个别名。",
        "a 的等待者要等于 b 的阻塞者。",
        "a 的阻塞者也要等于 b 的等待者。",
        "WHERE 只保留一个方向，避免重复。",
        "完整写法：SELECT a.waiter_tx, a.blocker_tx FROM lock_waits a INNER JOIN lock_waits b ON a.waiter_tx = b.blocker_tx AND a.blocker_tx = b.waiter_tx WHERE a.waiter_tx < a.blocker_tx;",
      ],
      locks: ["JOIN", "ON", "WHERE"],
      requiredFeatures: ["join", "on", "where"],
      attackTargetIds: [79],
    }],
  },
  {
    id: "f8-isolation",
    concept: "隔离级别与幻读",
    title: "幻境 · 识别隔离异常",
    intro: "同一条件两次计数变多，说明范围内出现新行。根据事故记录选择能阻止它的隔离策略。",
    schema: INCIDENT_SCHEMA,
    primaryMonsterId: 80,
    stages: [{
      id: "f8-isolation-phantom",
      objective: "查询 second_count 大于 first_count 的 phenomenon、prevented_by，按 id 排序。",
      queryTemplate: "",
      answerSql: "SELECT phenomenon, prevented_by FROM isolation_cases WHERE second_count > first_count ORDER BY id;",
      hints: [
        "返回 phenomenon、prevented_by。",
        "比较第二次数量与第一次数量。",
        "只保留 second_count > first_count。",
        "按 id 排序。",
        "完整写法：SELECT phenomenon, prevented_by FROM isolation_cases WHERE second_count > first_count ORDER BY id;",
      ],
      locks: ["WHERE", "ORDER BY"],
      requiredFeatures: ["where", "order-by"],
      attackTargetIds: [80],
    }],
  },
  {
    id: "f8-modeling",
    concept: "主键、唯一性与规范化",
    title: "石像庭 · 选择安全模型",
    intro: "模型不是越拆越好；先确保稳定主键、业务唯一约束与零重复组，再比较综合评分。",
    schema: INCIDENT_SCHEMA,
    primaryMonsterId: 81,
    stages: [{
      id: "f8-modeling-safe",
      objective: "筛出有主键、有唯一邮箱且无重复组的 model，按 score 降序只取一行。",
      queryTemplate: "",
      answerSql: "SELECT model FROM schema_choices WHERE has_primary_key = 1 AND has_unique_email = 1 AND duplicate_groups = 0 ORDER BY score DESC LIMIT 1;",
      hints: [
        "返回 model。",
        "三个安全条件都必须为真。",
        "用 AND 连接主键、唯一邮箱和零重复组。",
        "按 score DESC，LIMIT 1。",
        "完整写法：SELECT model FROM schema_choices WHERE has_primary_key = 1 AND has_unique_email = 1 AND duplicate_groups = 0 ORDER BY score DESC LIMIT 1;",
      ],
      locks: ["WHERE", "AND", "ORDER BY", "LIMIT"],
      requiredFeatures: ["where", "and", "order-by", "limit"],
      attackTargetIds: [81],
    }],
  },
  {
    id: "f8-replication",
    concept: "复制延迟与读路由",
    title: "双塔 · 选择新鲜副本",
    intro: "复制题只查询教学状态表。先过滤健康只读副本，再选择延迟最低的节点。",
    schema: INCIDENT_SCHEMA,
    primaryMonsterId: 82,
    stages: [{
      id: "f8-replication-fresh",
      objective: "查询健康 replica 的 node、lag_ms，按 lag_ms 升序只取一行。",
      queryTemplate: "",
      answerSql: "SELECT node, lag_ms FROM replica_status WHERE role = 'replica' AND healthy = 1 ORDER BY lag_ms LIMIT 1;",
      hints: [
        "返回 node、lag_ms。",
        "role 必须是 replica。",
        "再过滤 healthy = 1。",
        "延迟升序，LIMIT 1。",
        "完整写法：SELECT node, lag_ms FROM replica_status WHERE role = 'replica' AND healthy = 1 ORDER BY lag_ms LIMIT 1;",
      ],
      locks: ["WHERE", "AND", "ORDER BY", "LIMIT"],
      requiredFeatures: ["where", "and", "order-by", "limit"],
      attackTargetIds: [82],
    }],
  },
  {
    id: "f8-sharding",
    concept: "分片键与路由均衡",
    title: "分片桥 · 审计路由",
    intro: "分片记录已经给出路由结果。按 shard_id 统计有效路由，找出至少承载两户的分片。",
    schema: INCIDENT_SCHEMA,
    primaryMonsterId: 83,
    stages: [{
      id: "f8-sharding-balance",
      objective: "统计 route_ok = 1 的每个 shard_id 账户数 total，只保留 total >= 2，按 shard_id。",
      queryTemplate: "",
      answerSql: "SELECT shard_id, COUNT(*) AS total FROM shard_routes WHERE route_ok = 1 GROUP BY shard_id HAVING COUNT(*) >= 2 ORDER BY shard_id;",
      hints: [
        "返回 shard_id、COUNT(*) AS total。",
        "先过滤 route_ok = 1。",
        "按 shard_id 分组。",
        "HAVING 保留数量至少 2 的组，最后排序。",
        "完整写法：SELECT shard_id, COUNT(*) AS total FROM shard_routes WHERE route_ok = 1 GROUP BY shard_id HAVING COUNT(*) >= 2 ORDER BY shard_id;",
      ],
      locks: ["WHERE", "GROUP BY", "HAVING", "ORDER BY"],
      requiredFeatures: ["where", "group-by", "having", "order-by"],
      attackTargetIds: [83],
    }],
  },
  {
    id: "f8-security",
    concept: "综合事故响应与查询安全",
    title: "黑曜王座 · 五阶段事故响应",
    intro: "最终战把本层五类证据串成一次事故响应。每阶段仍是可复现的 SQLite 查询，最后用参数化与最小权限关闭入口。",
    schema: INCIDENT_SCHEMA,
    primaryMonsterId: 84,
    stages: [
      {
        id: "f8-final-snapshot",
        objective: "第一阶段：返回事务 12 可见且 row_id = 2 的 value。",
        queryTemplate: "",
        answerSql: "SELECT value FROM tx_versions WHERE row_id = 2 AND created_tx <= 12 AND (expired_tx IS NULL OR expired_tx > 12);",
        hints: [
          "返回 value。",
          "锁定 row_id = 2。",
          "created_tx 不晚于 12。",
          "还要判断未过期或 12 后过期。",
          "完整写法：SELECT value FROM tx_versions WHERE row_id = 2 AND created_tx <= 12 AND (expired_tx IS NULL OR expired_tx > 12);",
        ],
        locks: ["WHERE", "AND", "IS NULL"],
        requiredFeatures: ["where", "and", "is-null"],
        attackTargetIds: [84],
      },
      {
        id: "f8-final-deadlock",
        objective: "第二阶段：找出被 T2 阻塞的 waiter_tx、resource。",
        queryTemplate: "",
        answerSql: "SELECT waiter_tx, resource FROM lock_waits WHERE blocker_tx = 'T2' ORDER BY waiter_tx;",
        hints: [
          "返回 waiter_tx、resource。",
          "过滤 blocker_tx = 'T2'。",
          "按 waiter_tx 排序。",
          "完整写法：SELECT waiter_tx, resource FROM lock_waits WHERE blocker_tx = 'T2' ORDER BY waiter_tx;",
        ],
        locks: ["WHERE", "ORDER BY"],
        requiredFeatures: ["where", "order-by"],
        attackTargetIds: [84],
      },
      {
        id: "f8-final-anomaly",
        objective: "第三阶段：查询 phenomenon = 'phantom_read' 的 prevented_by。",
        queryTemplate: "",
        answerSql: "SELECT prevented_by FROM isolation_cases WHERE phenomenon = 'phantom_read';",
        hints: [
          "只返回 prevented_by。",
          "表是 isolation_cases。",
          "过滤 phenomenon = 'phantom_read'。",
          "完整写法：SELECT prevented_by FROM isolation_cases WHERE phenomenon = 'phantom_read';",
        ],
        locks: ["WHERE"],
        requiredFeatures: ["where"],
        attackTargetIds: [84],
      },
      {
        id: "f8-final-route",
        objective: "第四阶段：查询不健康副本的 node、lag_ms，按 lag_ms 降序。",
        queryTemplate: "",
        answerSql: "SELECT node, lag_ms FROM replica_status WHERE role = 'replica' AND healthy = 0 ORDER BY lag_ms DESC;",
        hints: [
          "返回 node、lag_ms。",
          "先过滤 replica。",
          "再过滤 healthy = 0。",
          "按 lag_ms DESC。",
          "完整写法：SELECT node, lag_ms FROM replica_status WHERE role = 'replica' AND healthy = 0 ORDER BY lag_ms DESC;",
        ],
        locks: ["WHERE", "AND", "ORDER BY"],
        requiredFeatures: ["where", "and", "order-by"],
        attackTargetIds: [84],
      },
      {
        id: "f8-final-security",
        objective: "最终阶段：查询同时参数化、最小权限且允许执行的 method，按 id。",
        queryTemplate: "",
        answerSql: "SELECT method FROM security_cases WHERE parameterized = 1 AND least_privilege = 1 AND allowed = 1 ORDER BY id;",
        hints: [
          "只返回 method。",
          "parameterized 必须为 1。",
          "least_privilege 与 allowed 也必须为 1。",
          "三个条件用 AND，最后按 id。",
          "完整写法：SELECT method FROM security_cases WHERE parameterized = 1 AND least_privilege = 1 AND allowed = 1 ORDER BY id;",
        ],
        locks: ["WHERE", "AND", "ORDER BY"],
        requiredFeatures: ["where", "and", "order-by"],
        attackTargetIds: [84],
      },
    ],
  },
];
